#!/usr/bin/env python3
r"""build.py - jp_f_tansu (intact + ransacked) from the recipe (tansu.py) to jp_efftest_max.pbo.

  python build.py [--no-binarize] [--no-pack]

  1. MLOD for both states -> out/*.p3d (kept), copied to src/JP/effort_test/max/
  2. config.cpp (CfgPatches JP_EffTest_max; JP_EffTest_max_Tansu, JP_EffTest_max_Tansu_Ransacked) -> CfgConvert
     (-bin, then -txt back and a class read-back)
  3. binarize.exe (cwd P:\) -> the ODOL replaces the MLOD copy in src (the MLOD stays in out/)
  4. pack src/JP/effort_test/max -> ..\@Japan\addons\jp_efftest_max.pbo, prefix JP\effort_test\max (a lock -> the
     PBO goes to out/ instead and the step reports it)
  5. sidecar jp_f_tansu.json (loot surfaces, front zone, LOD faces, materials) in src
  6. checks (checks.json): the kit's per-part checks (C2 library paths, C5 LODs, C7 closed+convex components, fire
     penetration mats) on the MLOD read back from disk, + C4 dimensions, face budgets, C6 base on the floor and no
     interpenetration of the moving pieces, loot clearance, C19 matte finish, ODOL read-back
Never touches the server, the game or any GUI program.
"""
import json
import math
import os
import re
import shutil
import subprocess
import sys

sys.dont_write_bytecode = True
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import tansu  # noqa: E402  (puts parts/kit on sys.path)
from jpparts import mlod, checks  # noqa: E402

DEV = tansu.DEV
ROOT = os.path.abspath(os.path.join(DEV, ".."))
LEVEL = "max"
SRC = os.path.join(DEV, "src", "JP", "effort_test", LEVEL)
OUT = os.path.join(HERE, "out")
PBO_NAME = "jp_efftest_%s.pbo" % LEVEL
PBO_OUT = os.path.join(ROOT, "@Japan", "addons", PBO_NAME)
PREFIX = "JP\\effort_test\\%s" % LEVEL
PATCH = "JP_EffTest_%s" % LEVEL
TOOLS = r"C:\Program Files (x86)\Steam\steamapps\common\DayZ Tools\Bin"
BINARIZE = os.path.join(TOOLS, "Binarize", "binarize.exe")
CFGCONVERT = os.path.join(TOOLS, "CfgConvert", "CfgConvert.exe")
MASS = 45.0          # kg (assumed): a two-part sugi isho-dansu, empty
STATES = [("intact", "jp_f_tansu", "%s_Tansu" % PATCH, "Tansu (clothing chest)"),
          ("ransacked", "jp_f_tansu_ransacked", "%s_Tansu_Ransacked" % PATCH, "Tansu (clothing chest), ransacked")]
BUDGET = {"Resolution 1": 1000, "Resolution 2": 400, "Resolution 3": 130}   # PLAYBOOK §12 furniture <= 1000 LOD0
GEO_PROPS = {"autocenter": "0"}   # vanilla furniture sets autocenter; origin = base centre on the floor


def wb(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "wb") as f:
        f.write(text if isinstance(text, bytes) else text.replace("\r\n", "\n").encode("utf-8"))


def copy_retry(src, dst, tries=5):
    import time
    for k in range(tries):
        try:
            shutil.copyfile(src, dst)
            return
        except OSError as e:
            if k == tries - 1:
                raise
            print("  copy retry (%s)" % e)
            time.sleep(2.0)


# ------------------------------------------------------------------------------------------------ config
def config_cpp():
    cls = ""
    for state, name, cname, disp in STATES:
        cls += ("\t// %s: BUILD_LIST row 26 jp_f_tansu, state %s. Placeable static prop (scope 2); a furnished house\n"
                "\t// uses the same p3d as a proxy.\n"
                "\tclass %s: HouseNoDestruct\n\t{\n\t\tscope=2;\n\t\tdisplayName=\"%s\";\n"
                "\t\tmodel=\"\\%s\\%s.p3d\";\n\t};\n" % (cname, state, cname, disp, PREFIX, name))
    return ("// %s - effort test (level %s): one prop, jp_f_tansu, in two states.\n"
            "// GENERATED by japan_dev/spikes/effort_test/%s/build.py - edit the generator, not this file.\n"
            "class CfgPatches\n{\n\tclass %s\n\t{\n\t\tunits[]={\"%s\",\"%s\"};\n\t\tweapons[]={};\n"
            "\t\trequiredVersion=0.1;\n\t\trequiredAddons[]=\n\t\t{\n\t\t\t\"DZ_Data\",\n\t\t\t\"JP_Common\"\n\t\t};\n"
            "\t};\n};\nclass CfgVehicles\n{\n\tclass HouseNoDestruct;\n%s};\n"
            % (PATCH, LEVEL, LEVEL, PATCH, STATES[0][2], STATES[1][2], cls))


def cfgconvert(path):
    tmp = os.path.join(OUT, "cfgconvert")
    os.makedirs(tmp, exist_ok=True)
    binp = os.path.join(tmp, "config.bin")
    txtp = os.path.join(tmp, "config_roundtrip.cpp")
    for p in (binp, txtp):
        if os.path.isfile(p):
            os.remove(p)
    r1 = subprocess.run([CFGCONVERT, "-bin", "-dst", binp, path], capture_output=True, text=True, errors="replace")
    r2 = subprocess.run([CFGCONVERT, "-txt", "-dst", txtp, binp], capture_output=True, text=True, errors="replace")
    ok = r1.returncode == 0 and os.path.isfile(binp) and r2.returncode == 0 and os.path.isfile(txtp)
    log = "CfgConvert -bin: rc=%d %s\nCfgConvert -txt: rc=%d %s\n" % (r1.returncode, (r1.stdout + r1.stderr).strip(),
                                                                    r2.returncode, (r2.stdout + r2.stderr).strip())
    classes = []
    if ok:
        txt = open(txtp, "rb").read().decode("utf-8", "replace")
        classes = re.findall(r"class\s+(\w+)", txt)
        want = [PATCH, "HouseNoDestruct", STATES[0][2], STATES[1][2]]
        miss = [c for c in want if c not in classes]
        models = re.findall(r'model\s*=\s*"([^"]+)"', txt)
        ok = ok and not miss and len(models) == 2
        log += "round trip classes: %s; models: %s; missing: %s\n" % (classes, models, miss)
    wb(os.path.join(OUT, "cfgconvert.log"), log)
    print("  CfgConvert config.cpp: %s (%s)" % ("OK" if ok else "FAILED", os.path.join(OUT, "cfgconvert.log")))
    return ok, log


# ------------------------------------------------------------------------------------------------ steps
def write_models():
    os.makedirs(OUT, exist_ok=True)
    os.makedirs(SRC, exist_ok=True)
    res = {}
    for state, name, cname, disp in STATES:
        part, meta = tansu.build(state)
        lods = part.lods(geo_props=GEO_PROPS, mass=MASS)
        mp = os.path.join(OUT, name + ".p3d")
        mlod.write_mlod(mp, lods)
        copy_retry(mp, os.path.join(SRC, name + ".p3d"))
        faces = {mlod.lod_name(l.resolution): len(l.faces) for l in lods}
        print("MLOD %s: %s" % (mp, faces))
        res[state] = dict(part=part, meta=meta, lods=lods, mlod=mp, name=name, cls=cname, faces=faces)
    return res


def binarize(res):
    if not os.path.isdir(r"P:\DZ") or not os.path.isdir(r"P:\JP\effort_test\%s" % LEVEL):
        print(r"binarize: P:\DZ or P:\JP\effort_test\%s missing (subst P: D:\DayZToolsExtract; P:\JP junction)" % LEVEL)
        return False, ""
    out = os.path.join(OUT, "binarized")
    shutil.rmtree(out, ignore_errors=True)
    os.makedirs(out)
    cmd = [BINARIZE, "-always", "-addon=P:\\%s" % PREFIX, "-binpath=P:\\bin", "P:\\%s" % PREFIX, out, "*.p3d"]
    r = subprocess.run(cmd, cwd="P:\\", capture_output=True, text=True, errors="replace")
    log = os.path.join(OUT, "binarize.log")
    wb(log, " ".join(cmd) + "\n\n" + r.stdout + "\n" + r.stderr)
    text = r.stdout + r.stderr
    # the lines that are about OUR models or files (the rest is binarize's usual world/config noise, as in the
    # machiya log: No entry '.CfgWorlds' ..., Terrain grid ...)
    # Known benign: "Note: 'HouseNoDestruct' is declared, but definition was not found. Creating empty class" -
    # binarize loads only this addon's config, not DZ_Data (the machiya log has the same note).
    ours = [l for l in text.splitlines() if re.search(r"jp_f_tansu|effort_test|jp\\common", l, re.I)
            and re.search(r"error|warning|cannot|not found|missing|failed", l, re.I)
            and not re.search(r"'HouseNoDestruct' is declared, but definition was not found", l)]
    ok = r.returncode == 0
    for state, d in res.items():
        found = os.path.join(out, d["name"] + ".p3d")
        if os.path.isfile(found) and open(found, "rb").read(4) == b"ODOL":
            copy_retry(found, os.path.join(SRC, d["name"] + ".p3d"))
            d["odol"] = found
        else:
            ok = False
    bc = re.findall(r"BoundingCenter of (\S+): ([-\d., ]+)", text)
    print("binarize %s: rc=%d, %d problem lines about our files, bounding centres %s (%s)"
          % ("OK" if ok and not ours else "FAILED", r.returncode, len(ours), bc, log))
    return ok and not ours, text


def pack():
    stage = os.path.join(OUT, "pbo_stage")
    shutil.rmtree(stage, ignore_errors=True)
    shutil.copytree(SRC, stage, ignore=shutil.ignore_patterns("model.cfg", "*.blend", "*.png", "*.log"))
    import pbo
    try:
        pbo.cmd_pack(stage, PBO_OUT, PREFIX)
        where = PBO_OUT
    except PermissionError as e:
        where = os.path.join(OUT, PBO_NAME)
        print("PBO write to @Japan FAILED (a running server or game locks it): %s -> packing into %s" % (e, where))
        pbo.cmd_pack(stage, where, PREFIX)
    print("packed", where, os.path.getsize(where), "bytes")
    return where


def sidecar(res):
    states = {}
    for state, d in res.items():
        states[state] = {"p3d": "%s\\%s.p3d" % (PREFIX, d["name"]), "class": d["cls"], "lod_faces": d["faces"],
                         "loot_surfaces": tansu.loot_surfaces(state, d["meta"]),
                         "front_zone_xz": tansu.front_zone(state, d["meta"])}
    doc = {"id": "jp_f_tansu", "build_list_row": 26, "name": "Clothing chest of drawers (isho-dansu), two stacked parts",
           "tiers": [2, 3], "room_tags": ["zashiki", "sleeping"], "level": "standard",
           "frame": "origin = base centre on the floor (autocenter=0); +y up; +z = front (drawers); p3d x right",
           "dims_m": {"width": tansu.W, "depth": tansu.D, "height": tansu.H, "box_height": tansu.HS,
                      "drawers": 4, "drawer_front": [round(2 * (tansu.XI - tansu.GAP), 3),
                                                     round(tansu.OH - 2 * tansu.GAP, 3)], "drawer_depth": tansu.DD},
           "footprint_xz": [tansu.X0, tansu.Z0, tansu.X1, tansu.Z1],
           "materials": {"body": "JP\\common\\materials\\wood\\jp_m_wood_street_dark_w2.rvmat (stand-in for "
                                 "jp_m_wood_interior; palette timber_street_dark, C1 vs timber_interior dE 8.8/14)",
                         "drawer_boxes": "JP\\common\\materials\\wood\\jp_m_wood_weathered_w2.rvmat (raw wood inside; "
                                         "C1 vs timber_interior dE 10.2/14)",
                         "cavity": "JP\\common\\materials\\wood\\jp_m_wood_sooted_w0.rvmat (faces looking into the "
                                   "carcass: stands in for shadow)",
                         "fittings": "JP\\common\\materials\\metal\\jp_m_metal_iron_w1.rvmat (iron_black)",
                         "fire": "dz\\data\\data\\penetration\\wood.rvmat"},
           "mass_kg": MASS, "states": states,
           "loot_note": "BUILD_LIST row 26: top at 1.00: 2 points (range 0.2); ransacked: 1 point in the dropped drawer "
                        "(floor). Container lootshelves / tag shelves (Q5). ce_points = CE frame (mz, my, -mx).",
           "made_by": "japan_dev/spikes/effort_test/%s/build.py" % LEVEL}
    p = os.path.join(SRC, "jp_f_tansu.json")
    wb(p, json.dumps(doc, indent=1))
    print("sidecar", p)
    return doc


# ------------------------------------------------------------------------------------------------ checks
def _footprint(comp):
    """xz polygon (convex hull of the component's points) + y range: every component here is a vertical prism."""
    pts = comp["pts"]
    hull = tansu.core.hull2d([(round(p[0], 6), round(p[2], 6)) for p in pts])
    ys = [p[1] for p in pts]
    return hull, (min(ys), max(ys))


def _sat2d(a, b, pad=0.0):
    """True if convex polygons a and b overlap by more than pad (separating axis test)."""
    for poly in (a, b):
        for i in range(len(poly)):
            p0, p1 = poly[i], poly[(i + 1) % len(poly)]
            ax = (-(p1[1] - p0[1]), p1[0] - p0[0])
            ln = math.hypot(*ax) or 1.0
            ax = (ax[0] / ln, ax[1] / ln)
            pa = [q[0] * ax[0] + q[1] * ax[1] for q in a]
            pb = [q[0] * ax[0] + q[1] * ax[1] for q in b]
            if max(pa) <= min(pb) + pad or max(pb) <= min(pa) + pad:
                return False
    return True


def run_checks(res, bin_ok, bin_text, cfg_ok, pbo_path):
    out = {"level": LEVEL, "states": {}}
    allok = True
    for state, d in res.items():
        rows = []
        lods = mlod.read_mlod(d["mlod"])                      # read back from disk
        kit, counts = checks.check_part(d["part"], d["mlod"], lods)
        for name, ok, detail in kit:
            if name.startswith("C3"):
                continue                                     # grid snap: a prop has no post/sill connectors
            rows.append((name, ok, detail))
        L = {mlod.lod_name(l.resolution): l for l in lods}
        # LOD set (BUILD_LIST Q5 rule 2: furniture Res 1-3, Geometry, View, Fire; no Memory, no Roadway)
        want = ["Resolution 1", "Resolution 2", "Resolution 3", "Geometry", "View Geometry", "Fire Geometry"]
        rows.append(("C5 LOD set = vanilla furniture (Res 1-3, Geometry, View, Fire)", sorted(L) == sorted(want),
                     ", ".join(sorted(L))))
        for k, lim in BUDGET.items():
            rows.append(("C5 budget %s <= %d" % (k, lim), counts.get(k, 0) <= lim, "%d faces" % counts.get(k, 0)))
        g = L["Geometry"]
        rows.append(("Geometry props + mass", g.properties.get("autocenter") == "0" and abs(sum(g.mass) - MASS) < 0.01,
                     "props %s, mass %.2f kg on %d points" % (g.properties, sum(g.mass), len(g.points))))
        # C4 dimensions on the Res 1 wood carcass (fittings stand 2-11 mm proud and are excluded)
        r1 = L["Resolution 1"]
        wood_pts = set()
        for verts, _, tex, _ in r1.faces:
            if "wood_street_dark" in tex or "wood_sooted" in tex:
                wood_pts.update(v[0] for v in verts)
        body = [r1.points[i] for i in wood_pts if r1.points[i][2] <= tansu.Z1 + 1e-4 and
                -tansu.Z1 - 1e-4 <= r1.points[i][2] and r1.points[i][1] >= -1e-6]
        xs, ys, zs = [p[0] for p in body], [p[1] for p in body], [p[2] for p in body]
        # the two boxes = the two Geometry blocks tagged coll_box (components are numbered in solid order)
        gtags = [s.tag for s in d["part"].solids if s.geo and s.closed]
        blocks = sorted(c["bbox"] for c, tg in zip(checks.components(L["Geometry"]), gtags) if tg == "coll_box")
        joint = blocks[0][3] if len(blocks) == 2 and abs(blocks[0][3] - blocks[1][2]) < 1e-4 else -1.0
        dims = [("width", 1.00, max(xs) - min(xs)), ("depth", 0.45, max(zs) - min(zs)), ("height", 1.00, max(ys)),
                ("two stacked boxes of 0.50 (joint height)", 0.50, joint)]
        for nm, exp, got in dims:
            ok = abs(got - exp) <= max(0.005, 0.02 * exp)
            rows.append(("C4 %s" % nm, ok, "expected %.3f (BUILD_LIST row 26), measured %.4f" % (exp, got)))
        allp = r1.points
        miny = min(p[1] for p in allp)
        maxy = max(p[1] for p in allp)
        rows.append(("C4 drawers: 4, iron ring pulls 2 per drawer, side handles 4",
                     sum(1 for s in d["part"].solids if s.tag == "ring") == 8 and
                     sum(1 for s in d["part"].solids if s.tag == "grip") == 4, "rings %d, grips %d, locks %d" % (
                         sum(1 for s in d["part"].solids if s.tag == "ring"),
                         sum(1 for s in d["part"].solids if s.tag == "grip"),
                         sum(1 for s in d["part"].solids if s.tag == "lock"))))
        # C6 placement: base on the floor, no Res-1 point below it, top loot surface clear
        rows.append(("C6 base on the floor (0-2 cm)", abs(miny) <= 1e-4, "lowest point y = %.4f, top %.4f" % (miny, maxy)))
        comps = checks.components(g)
        fps = [(c["name"], _footprint(c)) for c in comps]
        # which component is which (order = the order of geo solids in the part)
        geo_tags = [s.tag for s in d["part"].solids if s.geo and s.closed]
        clash = []
        for i in range(len(fps)):
            for j in range(i + 1, len(fps)):
                ti, tj = geo_tags[i], geo_tags[j]
                same = (ti == tj == "geo_fd") or ({ti, tj} <= {"coll_box"})
                if same or {ti, tj} == {"coll_box", "coll_drawer"}:
                    continue                               # wall-to-wall joints of one piece / drawer against its box
                (pa, ya), (pb, yb) = fps[i][1], fps[j][1]
                if min(ya[1], yb[1]) - max(ya[0], yb[0]) > 0.01 and _sat2d(pa, pb, pad=0.01):
                    clash.append("%s(%s) x %s(%s)" % (fps[i][0], ti, fps[j][0], tj))
        rows.append(("C6 no interpenetration > 1 cm between separate pieces (Geometry)", not clash,
                     "%d components, %s" % (len(comps), "clear" if not clash else "; ".join(clash[:4]))))
        # loot: top points on the top, nothing above; dropped-drawer point inside its bottom, 25 cm clear above
        ls = tansu.loot_surfaces(state, d["meta"])
        lp_ok, det = True, []
        for s in ls:
            for p in s["points"]:
                # vertical rays at the point and at 8 points on its range circle, against the convex components
                samples = [(p[0], p[2])] + [(p[0] + s["range"] * math.cos(k * math.pi / 4),
                                             p[2] + s["range"] * math.sin(k * math.pi / 4)) for k in range(8)]
                above = []
                for x, z in samples:
                    for c in comps:
                        r = checks.ray_y(c, x, z)
                        if r and r[0] > p[1] + 0.005:
                            above.append(r[0] - p[1])
                support = []
                for c in comps:
                    r = checks.ray_y(c, p[0], p[2])
                    if r and abs(r[1] - p[1]) < 0.003:
                        support.append(c)
                clear = min(above) if above else 9.9
                okp = bool(support) and clear >= 0.25
                lp_ok = lp_ok and okp
                det.append("%s (%.3f, %.3f, %.3f): on %s, clear above %.2f m" % (s["name"], p[0], p[1], p[2],
                                                                                 support[0]["name"] if support else "NOTHING",
                                                                                 clear))
        rows.append(("C6 loot points on a Geometry top, >= 0.25 m clear above", lp_ok, "; ".join(det)))
        if state == "ransacked":
            # every drawer-box vertex inside the carcass depth lies in a drawer cavity (no board is pierced), the
            # drooped drawer included; its rear corner must end 0-2 mm under the board above
            cav = [tansu.opening(y0, sl) for _, y0, sl in tansu.DRAWERS]
            bad, worst = [], 1.0
            for s in d["part"].solids:
                if s.tag not in ("dside", "dback", "dbottom", "front") or 1 not in s.vis:
                    continue
                for v in s.verts:
                    if v[2] >= tansu.Z1 - 1e-6:
                        continue                               # in front of the carcass: nothing to pierce
                    inside = [(bb, tt) for bb, tt in cav if bb - 1e-6 <= v[1] <= tt + 1e-6]
                    okv = inside and abs(v[0]) <= tansu.XI + 1e-6 and v[2] >= tansu.Z0 + tansu.TB - 1e-6
                    if not okv:
                        bad.append(tuple(round(c, 4) for c in v))
                    else:
                        worst = min(worst, min(tt - v[1] for bb, tt in inside))
            dr = d["meta"].get("droop_deg", {})
            rows.append(("C6 drawer boxes inside their cavities (drooped drawer included)", not bad,
                         "%s; droop %s; closest approach to the board above %.4f m" % (
                             "all vertices inside" if not bad else "%d vertices outside, e.g. %s" % (len(bad), bad[:2]),
                             dr, worst)))
            fi = d["meta"]["floor_drawer"]
            fz = tansu.front_zone(state, d["meta"])
            inside = fz["z"][0] <= fi["z_rear"] and fi["z_front"] <= fz["z"][1]
            rows.append(("Dropped drawer inside the front zone", inside,
                         "drawer z %.3f..%.3f, zone z %.3f..%.3f, x %.3f..%.3f" % (fi["z_rear"], fi["z_front"], fz["z"][0],
                                                                                  fz["z"][1], fz["x"][0], fz["x"][1])))
        # C19 matte: the wood rvmats used carry the black env map; iron is glossy by design (T12)
        mats = sorted({f[3] for f in r1.faces})
        bad = []
        for m in mats:
            txt = open(os.path.join(DEV, "src", m), "rb").read().decode("latin-1")
            glossy = "metal_iron" in m
            black = "color(0,0,0,1,CO)" in txt and "fresnel(0.01,0.01)" in txt
            if not glossy and not black:
                bad.append(m)
        rows.append(("C19 matte finish (non-glossy rvmats have the black env map)", not bad,
                     "%d rvmats: %s" % (len(mats), ", ".join(os.path.basename(m) for m in mats))))
        # ODOL read-back
        if d.get("odol"):
            data = open(os.path.join(SRC, d["name"] + ".p3d"), "rb").read()
            nl = int.from_bytes(data[8:12], "little")
            import struct
            ress = struct.unpack_from("<%df" % nl, data, 12)
            rows.append(("ODOL in src (binarized, version %d)" % int.from_bytes(data[4:8], "little"),
                         data[:4] == b"ODOL" and nl == len(lods),
                         "%d LODs: %s" % (nl, ", ".join(mlod.lod_name(r) for r in ress))))
        n_ok = sum(1 for r in rows if r[1])
        allok = allok and n_ok == len(rows)
        out["states"][state] = {"faces": counts, "checks": [{"check": a, "ok": bool(b), "detail": c} for a, b, c in rows]}
        print("\n== checks %s: %d/%d" % (state, n_ok, len(rows)))
        for a, b, c in rows:
            print("  %s %s: %s" % ("OK  " if b else "FAIL", a, c))
    out["binarize_ok"] = bin_ok
    out["cfgconvert_ok"] = cfg_ok
    out["pbo"] = pbo_path
    wb(os.path.join(HERE, "checks.json"), json.dumps(out, indent=1))
    return allok


def main(argv):
    res = write_models()
    wb(os.path.join(SRC, "config.cpp"), config_cpp())
    cfg_ok, _ = cfgconvert(os.path.join(SRC, "config.cpp"))
    bin_ok, bin_text = (None, "")
    if "--no-binarize" not in argv:
        bin_ok, bin_text = binarize(res)
    sidecar(res)
    pbo_path = None
    if "--no-pack" not in argv and bin_ok:
        sys.path.insert(0, os.path.join(DEV, "tools", "common"))
        pbo_path = pack()
    ok = run_checks(res, bin_ok, bin_text, cfg_ok, pbo_path)
    print("\nALL CHECKS %s" % ("PASS" if ok and cfg_ok and (bin_ok or "--no-binarize" in argv) else "NOT PASSING"))
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
