#!/usr/bin/env python3
r"""build.py - effort test (LEVEL = high): jp_f_tansu in two states -> jp_efftest_high.pbo

  python build.py [--no-binarize] [--no-pack]

  1. MLOD for both states (tansu.py) -> out/*.p3d, copied to src/JP/effort_test/high/data/
  2. config.cpp (CfgPatches JP_EffTest_high, two HouseNoDestruct statics) + model.cfg -> CfgConvert
  3. binarize.exe (cwd P:\) -> ODOL replaces the MLOD copies in src (MLODs stay in out/)
  4. pack src/JP/effort_test/high (minus model.cfg and sidecars) -> ..\@Japan\addons\jp_efftest_high.pbo
  5. checks -> checks.json
Never touches the server, the game or any GUI program. Writes only in this folder, src/JP/effort_test/high and
the one PBO.
"""
import json
import os
import re
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DEV = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
ROOT = os.path.abspath(os.path.join(DEV, ".."))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(DEV, "tools", "common"))
import tansu as TZ  # noqa: E402
from jpparts import core, mlod  # noqa: E402

LEVEL = "high"
PATCH = "JP_EffTest_%s" % LEVEL
SRC = os.path.join(DEV, "src", "JP", "effort_test", LEVEL)
DDIR = os.path.join(SRC, "data")
OUT = os.path.join(HERE, "out")
TEMP = os.path.join(HERE, "_build")
PBO_OUT = os.path.join(ROOT, "@Japan", "addons", "jp_efftest_%s.pbo" % LEVEL)
PBO_FALLBACK = os.path.join(HERE, "jp_efftest_%s.pbo" % LEVEL)
PREFIX = "JP\\effort_test\\%s" % LEVEL
TOOLS = r"C:\Program Files (x86)\Steam\steamapps\common\DayZ Tools\Bin"
BINARIZE = os.path.join(TOOLS, "Binarize", "binarize.exe")
CFGCONVERT = os.path.join(TOOLS, "CfgConvert", "CfgConvert.exe")

MODELS = {   # state -> (p3d name, class, display name)
    "intact": ("jp_efftest_%s_tansu" % LEVEL, "JP_EffTest_%s_Tansu" % LEVEL, "Tansu (clothing chest)"),
    "ransacked": ("jp_efftest_%s_tansu_ransacked" % LEVEL, "JP_EffTest_%s_Tansu_Ransacked" % LEVEL,
                  "Tansu (clothing chest, ransacked)"),
}


def wb(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "wb") as f:
        f.write(text if isinstance(text, bytes) else text.replace("\r\n", "\n").encode("utf-8"))


def model_path(p3d):
    return "\\%s\\data\\%s.p3d" % (PREFIX, p3d)


def config_cpp():
    cls = ""
    for st, (p3d, cname, disp) in MODELS.items():
        cls += ("\t// %s\n\tclass %s: HouseNoDestruct\n\t{\n\t\tscope=1;\n\t\tdisplayName=\"%s\";\n"
                "\t\tmodel=\"%s\";\n\t};\n" % (st, cname, disp, model_path(p3d)))
    units = ", ".join('"%s"' % m[1] for m in MODELS.values())
    return ("// %s - effort test prop jp_f_tansu (BUILD_LIST row 26), two states. Placeable statics like vanilla\n"
            "// StaticObj_Furniture_* (HouseNoDestruct, scope 1: object spawner / init.c).\n"
            "// GENERATED by japan_dev/spikes/effort_test/%s/build.py - edit the generator, not this file.\n"
            "class CfgPatches\n{\n\tclass %s\n\t{\n\t\tunits[]={%s};\n\t\tweapons[]={};\n"
            "\t\trequiredVersion=0.1;\n\t\trequiredAddons[]=\n\t\t{\n\t\t\t\"DZ_Data\",\n\t\t\t\"JP_Common\"\n"
            "\t\t};\n\t};\n};\nclass CfgVehicles\n{\n\tclass HouseNoDestruct;\n%s};\n"
            % (PATCH, LEVEL, PATCH, units, cls))


def model_cfg():
    models = "".join("\tclass %s: Default\n\t{\n\t};\n" % m[0] for m in MODELS.values())
    return ("class CfgSkeletons\n{\n\tclass Default\n\t{\n\t\tisDiscrete=1;\n\t\tskeletonInherit=\"\";\n"
            "\t\tskeletonBones[]={};\n\t};\n};\nclass CfgModels\n{\n\tclass Default\n\t{\n\t\tsectionsInherit=\"\";\n"
            "\t\tsections[]={};\n\t\tskeletonName=\"\";\n\t};\n%s};\n" % models)


def cfgconvert(path):
    os.makedirs(TEMP, exist_ok=True)
    dst = os.path.join(TEMP, os.path.basename(path) + ".bin")
    if os.path.exists(dst):
        os.remove(dst)
    r = subprocess.run([CFGCONVERT, "-bin", "-dst", dst, path], capture_output=True, text=True, errors="replace")
    ok = r.returncode == 0 and os.path.isfile(dst)
    back = dst + ".cpp"
    if ok:   # round trip: bin -> txt, proves the binary parses too
        r2 = subprocess.run([CFGCONVERT, "-txt", "-dst", back, dst], capture_output=True, text=True, errors="replace")
        ok = r2.returncode == 0 and os.path.isfile(back)
    msg = "CfgConvert %s: %s %s" % (os.path.basename(path), "OK" if ok else "FAILED", (r.stdout + r.stderr).strip())
    print("  " + msg)
    return ok, msg


def write_models():
    os.makedirs(OUT, exist_ok=True)
    os.makedirs(DDIR, exist_ok=True)
    res = {}
    for st, (p3d, cname, _) in MODELS.items():
        P = TZ.model(st)
        lods = P.lods(TZ.geo_props(), TZ.MASS)
        mp = os.path.join(OUT, p3d + ".p3d")
        mlod.write_mlod(mp, lods)
        shutil.copyfile(mp, os.path.join(DDIR, p3d + ".p3d"))
        res[st] = (P, lods, mp)
        print("MLOD %s: %s" % (p3d, {mlod.lod_name(l.resolution): len(l.faces) for l in lods}))
    note = {"id": "jp_f_tansu", "build_list_row": 26, "frame": "model: origin = footprint centre on the floor, +z = "
            "drawer front, autocenter=0", "loot_surfaces": {}}
    for st, (P, lods, mp) in res.items():
        pts = []
        for k in sorted(P.memory):
            if k.startswith("loot_"):
                p = P.memory[k][0]
                pts.append({"memory_point": k, "model": [round(c, 4) for c in p],
                            "range": 0.2 if k.startswith("loot_top") else 0.15,
                            "kind": "shelf (top at 1.00)" if k.startswith("loot_top") else "floor (dropped drawer)"})
        note["loot_surfaces"][MODELS[st][1]] = pts
    note["rule"] = "BUILD_LIST 26: top at 1.00: 2 points (range 0.2); ransacked: 1 point in the dropped drawer (floor)"
    wb(os.path.join(DDIR, "jp_f_tansu.loot.json"), json.dumps(note, indent=1))
    wb(os.path.join(DDIR, "model.cfg"), model_cfg())
    wb(os.path.join(SRC, "config.cpp"), config_cpp())
    return res


def binarize():
    out = os.path.join(TEMP, "binarized")
    shutil.rmtree(out, ignore_errors=True)
    os.makedirs(out)
    cmd = [BINARIZE, "-always", "-addon=P:\\" + PREFIX, "-binpath=P:\\bin", "P:\\%s\\data" % PREFIX, out, "*.p3d"]
    r = subprocess.run(cmd, cwd="P:\\", capture_output=True, text=True, errors="replace")
    log = os.path.join(HERE, "binarize.log")
    wb(log, " ".join(cmd) + "\n\n" + r.stdout + "\n" + r.stderr)
    # the same 8 environment lines appear in every JP binarize log (machiya_t3_01/out/binarize.log): binarize runs
    # without the game's global config (CfgDefaultSettings, CfgWorlds, PreloadConfig). Anything else is a finding.
    noise = (r"^Warning: Terrain grid", r"^Warning: CfgVehicles missing in PreloadConfig", r"^Trying to access error value")
    lines = (r.stdout + r.stderr).splitlines()
    bad = [l for l in lines if re.search(r"error|warning|cannot|not loaded|missing", l, re.I)
           and not any(re.search(n, l) for n in noise)]
    boiler = sum(1 for l in lines if any(re.search(n, l) for n in noise))
    ok = True
    info = {}
    for st, (p3d, _, _) in MODELS.items():
        found = None
        for root_, _, files in os.walk(out):
            if p3d + ".p3d" in files:
                found = os.path.join(root_, p3d + ".p3d")
        if found and open(found, "rb").read(4) == b"ODOL":
            shutil.copyfile(found, os.path.join(DDIR, p3d + ".p3d"))
            info[st] = os.path.getsize(found)
        else:
            ok = False
            info[st] = None
    print("binarize %s: %s; %d warning/error lines (log %s)" % ("OK" if ok else "FAILED", info, len(bad), log))
    for l in bad[:20]:
        print("   ", l)
    return ok, {"odol_bytes": info, "warning_lines": bad, "boilerplate_lines": boiler, "exit": r.returncode}


def pack():
    stage = os.path.join(TEMP, "pbo_stage")
    shutil.rmtree(stage, ignore_errors=True)
    shutil.copytree(SRC, stage, ignore=shutil.ignore_patterns("model.cfg", "*.json", "*.png", "*.log"))
    import pbo
    try:
        pbo.cmd_pack(stage, PBO_OUT, PREFIX)
        return True, PBO_OUT
    except PermissionError as e:
        print("PBO write to @Japan FAILED (locked by a running server/game?):", e)
        pbo.cmd_pack(stage, PBO_FALLBACK, PREFIX)
        return False, PBO_FALLBACK


# ------------------------------------------------------------------------------------------------ checks
def _srgb_to_lab(rgb):
    def lin(c):
        c /= 255.0
        return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4
    r, g, b = (lin(float(c)) for c in rgb)
    x = (0.4124 * r + 0.3576 * g + 0.1805 * b) / 0.95047
    y = 0.2126 * r + 0.7152 * g + 0.0722 * b
    z = (0.0193 * r + 0.1192 * g + 0.9505 * b) / 1.08883
    f = lambda t: t ** (1 / 3) if t > 0.008856 else 7.787 * t + 16 / 116   # noqa: E731
    return (116 * f(y) - 16, 500 * (f(x) - f(y)), 200 * (f(y) - f(z)))


def de76(a, b):
    la, lb = _srgb_to_lab(a), _srgb_to_lab(b)
    return sum((p - q) ** 2 for p, q in zip(la, lb)) ** 0.5


def palette_check():
    from PIL import Image
    import numpy as np
    pal = json.load(open(os.path.join(DEV, "playbook", "palette.json"), encoding="utf-8"))
    ent = pal.get("entries", pal)
    items = ent.items() if isinstance(ent, dict) else [(e.get("id"), e) for e in ent]
    P = {k: v for k, v in items if isinstance(v, dict) and "srgb" in v}
    out = []
    for key, wear, pid in ((TZ.WOOD, "_w1", "timber_interior"), (TZ.WOOD, "_w1", "timber_street_dark"),
                           (TZ.WOOD, "_w2", "timber_interior"), (TZ.IRON, "_w1", "iron_black")):
        a = np.asarray(Image.open(core.png_path(key, wear)).convert("RGB"), dtype=float).reshape(-1, 3).mean(axis=0)
        d = de76(a, P[pid]["srgb"])
        out.append({"material": core.mat_info(key)["id"] + wear, "mean_srgb": [round(float(c), 1) for c in a],
                    "palette": pid, "target": P[pid]["srgb"], "dE76": round(d, 1),
                    "tolerance": P[pid]["tolerance_dE76"], "pass": d <= P[pid]["tolerance_dE76"]})
    return out


def lod_bbox(l):
    xs = [p[0] for p in l.points]
    ys = [p[1] for p in l.points]
    zs = [p[2] for p in l.points]
    return [min(xs), max(xs), min(ys), max(ys), min(zs), max(zs)]


def comp_boxes(l):
    out = []
    for name, (pw, fs) in l.selections.items():
        if name.lower().startswith("component"):
            pts = [l.points[i] for i in pw]
            out.append((name, [min(p[0] for p in pts), max(p[0] for p in pts), min(p[1] for p in pts),
                               max(p[1] for p in pts), min(p[2] for p in pts), max(p[2] for p in pts)]))
    return out


def checks(res, conv, bz, packed):
    rec = {"asset": "jp_f_tansu (effort test %s)" % LEVEL, "checks": []}

    def add(cid, name, ok, detail):
        rec["checks"].append({"id": cid, "name": name, "pass": bool(ok), "detail": detail})

    for st, (P, lods, mp) in res.items():
        back = mlod.read_mlod(mp)                                   # round trip of the written file
        L = {mlod.lod_name(l.resolution): l for l in back}
        add("RT", "%s: MLOD reads back" % st, len(back) == len(lods), sorted(L))
        # C2 library only
        bad = set()
        for n, l in L.items():
            for f in l.faces:
                tex, mat = f[2], f[3]
                if n.startswith("Resolution"):
                    if not (tex.startswith("JP\\common\\materials\\") and mat.startswith("JP\\common\\materials\\")):
                        bad.add((tex, mat))
                elif n == "Fire Geometry":
                    if not mat.startswith("dz\\data\\data\\penetration\\"):
                        bad.add(mat)
        mats = sorted({f[3] for n, l in L.items() if n.startswith("Resolution") for f in l.faces})
        add("C2", "%s: library materials only" % st, not bad, {"materials": mats, "bad": sorted(map(str, bad))})
        # C5 LODs and budget
        need = ["Resolution 1", "Resolution 2", "Resolution 3", "Geometry", "Memory", "View Geometry", "Fire Geometry"]
        faces = {n: len(l.faces) for n, l in L.items()}
        r1 = faces["Resolution 1"]
        add("C5", "%s: LOD set + budget (furniture <=1000, brief <=1500)" % st,
            all(n in L for n in need) and r1 <= 1000,
            {"faces": faces, "res2_ratio": round(faces["Resolution 2"] / r1, 2),
             "res3_ratio": round(faces["Resolution 3"] / r1, 2)})
        # C4 dimensions (carcass: the wood boxes; overall incl. iron)
        car = [s for s in P.solids if s.tag == "carcass" and 1 in s.vis]
        xs = [v[0] for s in car for v in s.verts]
        ys = [v[1] for s in car for v in s.verts]
        zs = [v[2] for s in car for v in s.verts]
        dims = {"width": (max(xs) - min(xs), 1.00), "depth": (max(zs) - min(zs), 0.45), "height": (max(ys) - min(ys), 1.00)}
        ok = all(abs(m - e) <= 0.02 * e for m, e in dims.values())
        add("C4", "%s: carcass 1.00 x 0.45 x 1.00 (+-2 %%)" % st, ok,
            {k: round(v[0], 4) for k, v in dims.items()} | {"overall_res1_bbox": [round(c, 4) for c in lod_bbox(L["Resolution 1"])]})
        # C6 base on the floor
        vb = lod_bbox(L["Resolution 1"])
        gb = lod_bbox(L["Geometry"])
        add("C6a", "%s: base at y=0 (visual and Geometry within 0-2 cm)" % st, abs(vb[2]) <= 0.02 and abs(gb[2]) <= 0.02,
            {"res1_min_y": round(vb[2], 4), "geo_min_y": round(gb[2], 4)})
        # Geometry: closed convex components, mass, properties
        g = L["Geometry"]
        comps = [n for n in g.selections if n.lower().startswith("component")]
        probs = {n: mlod.component_report(g, n) for n in comps}
        add("GEO", "%s: Geometry components closed + convex, mass, autocenter=0" % st,
            all(not p for p in probs.values()) and abs(sum(g.mass) - TZ.MASS) < 0.01 and g.properties.get("autocenter") == "0",
            {"components": len(comps), "problems": {k: v for k, v in probs.items() if v},
             "mass": round(sum(g.mass), 2), "props": g.properties})
        for nm in ("View Geometry", "Fire Geometry", "LOD 10000"):
            l = L[nm]
            cs = [n for n in l.selections if n.lower().startswith("component")]
            pr = {n: mlod.component_report(l, n) for n in cs}
            add("GEO", "%s: %s components closed + convex" % (st, nm), all(not p for p in pr.values()),
                {"components": len(cs), "problems": {k: v for k, v in pr.items() if v}} if cs else
                {"note": "no Component selections (shadow volume)", "faces": len(l.faces)})
        # C6b geometry overlap (AABB; all boxes are axis aligned except the dropped drawer, which clears by 3.5 cm)
        cb = comp_boxes(g)
        worst = 0.0
        for i in range(len(cb)):
            for j in range(i + 1, len(cb)):
                a, b = cb[i][1], cb[j][1]
                ov = [min(a[1], b[1]) - max(a[0], b[0]), min(a[3], b[3]) - max(a[2], b[2]), min(a[5], b[5]) - max(a[4], b[4])]
                if min(ov) > 0:
                    worst = max(worst, min(ov))
        add("C6b", "%s: no Geometry interpenetration > 1 cm" % st, worst <= 0.01, {"worst_m": round(worst, 4)})
        # loot surface
        mem = L["Memory"]
        pts = {n: [mem.points[i] for i in pw] for n, (pw, fs) in mem.selections.items()}
        top = [pts.get("loot_top_1", [None])[0], pts.get("loot_top_2", [None])[0]]
        ok = all(p is not None and abs(p[1] - 1.00) < 0.005 and abs(p[0]) <= 0.5 - 0.2 and abs(p[2]) <= 0.225 for p in top)
        det = {"loot_top": [list(map(lambda c: round(c, 3), p)) for p in top if p]}
        if st == "ransacked":
            ld = pts.get("loot_drawer", [None])[0]
            dro = [s for s in P.solids if s.tag == "dropped"]
            dx = [v[0] for s in dro for v in s.verts]
            dzs = [v[2] for s in dro for v in s.verts]
            zone = {"x": [round(min(dx), 3), round(max(dx), 3)], "z": [round(min(dzs), 3), round(max(dzs), 3)],
                    "zone_x": [-0.5, 0.5], "zone_z": [TZ.Z1, round(TZ.Z1 + TZ.FRONT_ZONE, 3)]}
            inzone = min(dx) >= -0.5 - 1e-3 and max(dx) <= 0.5 + 1e-3 and min(dzs) >= TZ.Z1 and max(dzs) <= TZ.Z1 + TZ.FRONT_ZONE
            ok = ok and ld is not None and ld[1] < 0.05 and inzone
            det.update({"loot_drawer": [round(c, 3) for c in ld] if ld else None, "dropped_drawer": zone,
                        "in_front_zone": inzone})
        add("LOOT", "%s: loot points (top at 1.00 x2%s)" % (st, ", 1 in the dropped drawer" if st == "ransacked" else ""),
            ok, det)
    # C19 matte finish of the wood rvmats used, iron glossy by design (T12)
    t = {}
    for w in ("_w1", "_w2"):
        txt = open(os.path.join(DEV, "src", core.rvmat_path(TZ.WOOD, w)), encoding="utf-8").read()
        t[TZ.WOOD + w] = ("color(0,0,0,1,CO)" in txt, "fresnel(0.01,0.01)" in txt)
    add("C19", "matte wood rvmats: black env map + fresnel(0.01,0.01)", all(a and b for a, b in t.values()), t)
    pc = palette_check()
    add("C1", "palette (mean _co vs palette entry, dE76)", pc[0]["pass"] and pc[3]["pass"], pc)
    add("CFG", "CfgConvert config.cpp + model.cfg (to bin and back)", all(c[0] for c in conv), [c[1] for c in conv])
    if bz is not None:
        add("BIN", "binarize: both ODOL, no warning/error lines", all(bz[1]["odol_bytes"].values()) and not bz[1]["warning_lines"],
            bz[1])
    if packed is not None:
        add("PBO", "packed", packed[0], packed[1])
    wb(os.path.join(HERE, "checks.json"), json.dumps(rec, indent=1))
    fails = [c for c in rec["checks"] if not c["pass"]]
    print("checks: %d / %d pass" % (len(rec["checks"]) - len(fails), len(rec["checks"])))
    for c in fails:
        print("  FAIL", c["id"], c["name"], json.dumps(c["detail"])[:400])
    return rec


def main(argv):
    res = write_models()
    conv = [cfgconvert(os.path.join(SRC, "config.cpp")), cfgconvert(os.path.join(DDIR, "model.cfg"))]
    bz = binarize() if "--no-binarize" not in argv else None
    packed = pack() if "--no-pack" not in argv else None
    if packed:
        print("packed:", packed)
    checks(res, conv, bz, packed)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
