// JP_Plants - spike F (flora) of japan_dev. Generated by spikes/F_flora/tools/build.py; edit the generator.
// One CfgPatches class for this PBO, declared once.
class CfgPatches
{
	class JP_Plants
	{
		units[] = {"JP_Sakura_01_Static", "JP_Sakura_02_Static", "JP_BambooClump_01_Static", "JP_BambooPole"};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Data", "DZ_Plants", "DZ_Gear_Crafting", "DZ_Scripts"};
	};
};
class CfgMods
{
	class JP_Plants
	{
		dir = "Japan";
		picture = "";
		action = "";
		hideName = 1;
		hidePicture = 1;
		name = "JP Plants";
		credits = "";
		author = "japan_dev";
		authorID = "0";
		version = "0.1";
		extra = 0;
		type = "mod";
		dependencies[] = {"World"};
		class defs
		{
			class worldScriptModule
			{
				value = "";
				files[] = {"JP/plants/scripts/4_World"};
			};
		};
	};
};
class CfgVehicles
{
	class HouseNoDestruct;
	class LongWoodenStick;
	// Runtime-spawnable copies of the plants (object spawner / init.c). Visual fallback only: the engine
	// matches CfgNonAIVehicles by p3d name on TERRAIN objects, so these are never cuttable.
	class JP_Sakura_01_Static: HouseNoDestruct
	{
		scope = 1;
		model = "\JP\plants\tree\jp_sakura_01.p3d";
	};
	class JP_Sakura_02_Static: HouseNoDestruct
	{
		scope = 1;
		model = "\JP\plants\tree\jp_sakura_02.p3d";
	};
	class JP_BambooClump_01_Static: HouseNoDestruct
	{
		scope = 1;
		model = "\JP\plants\bamboo\jp_bamboo_clump_01.p3d";
	};
	// A green bamboo pole. Inherits LongWoodenStick so it gets the stick's in-hands profile (profiles follow
	// class inheritance), its Shoulder/Melee slots, melee modes and every recipe that takes a long stick.
	class JP_BambooPole: LongWoodenStick
	{
		scope = 2;
		displayName = "Bamboo Pole";
		descriptionShort = "A freshly cut length of madake bamboo, about two and a half metres long. Hollow, light for its size and very strong.";
		model = "\JP\plants\items\jp_bamboo_pole.p3d";
		weight = 1800;
		itemSize[] = {1, 10};
		absorbency = 0.2;
		class DamageSystem
		{
			class GlobalHealth
			{
				class Health
				{
					hitpoints = 100;
					healthLevels[] =
					{
						{1.0, {"JP\plants\items\data\jp_bamboo_pole.rvmat"}},
						{0.7, {"JP\plants\items\data\jp_bamboo_pole.rvmat"}},
						{0.5, {"JP\plants\items\data\jp_bamboo_pole_damage.rvmat"}},
						{0.3, {"JP\plants\items\data\jp_bamboo_pole_damage.rvmat"}},
						{0.0, {"JP\plants\items\data\jp_bamboo_pole_destruct.rvmat"}}
					};
				};
			};
		};
	};
};
class CfgNonAIVehicles
{
	class TreeHard;
	class BushHard;
	// <PlantType>_<p3d file name>: the engine gives terrain objects of that p3d this class (see
	// P:\scripts\4_world\entities\core\inherited\plant.c). Values follow vanilla's TreeHard_t_prunusDomestica_2s.
	class TreeHard_jp_sakura_01: TreeHard
	{
		isCuttable = 1;
		primaryDropsAmount = 1;
		secondaryDropsAmount = 1;
		toolDamage = 4;
		cycleTimeOverride = 3;
		primaryOutput = "WoodenLog";
		secondaryOutput = "LongWoodenStick";
	};
	class TreeHard_jp_sakura_02: TreeHard
	{
		isCuttable = 1;
		primaryDropsAmount = 1;
		secondaryDropsAmount = 1;
		toolDamage = 4;
		cycleTimeOverride = 3;
		primaryOutput = "WoodenLog";
		secondaryOutput = "LongWoodenStick";
	};
	// Bamboo as a HARD BUSH: every vanilla blade and axe can cut it (ActionMineBush: hatchet, wood axe,
	// firefighter axe, machete, knives, saws, sickle...), standing or crouched, and its geometry blocks walkers.
	// 3 cycles of 3 s each drop one pole; when it falls, the thin leafy tops drop as a stack of sticks.
	class BushHard_jp_bamboo_clump_01: BushHard
	{
		isCuttable = 1;
		primaryDropsAmount = 3;
		secondaryDropsAmount = 3;
		toolDamage = 4;
		cycleTimeOverride = 3;
		primaryOutput = "JP_BambooPole";
		secondaryOutput = "WoodenStick";
	};
};
