// japantest.japantestisland - GENERATED by japan_dev/spikes/T_terrain/build_mission.py. Do not edit by hand:
// edit the test/ drop-ins (or the template in build_mission.py) and rerun the script.
// Vanilla dayzOffline init.c, minus the September date reset (this island is spring), plus the test layout:
//   * every class from test/items/*.txt on the ground, rows from (1000, 975) at 1.5 m (35 items)
//   * every line of test/spawns/*_creatures.txt standing at ground height (3 creatures)
// Both are spawned once, when the first player connects (so CE cleanup cannot run before anyone is near), and are
// not saved to storage (ECE_NOPERSISTENCY_WORLD), so a restart never duplicates them.
// New characters spawn at the yard, (1024, 985), facing north.

void main()
{
	//INIT ECONOMY--------------------------------------
	Hive ce = CreateHive();
	if ( ce )
		ce.InitOffline();
}

class CustomMission: MissionServer
{
	protected bool m_JPTestSpawned;
	protected int m_JPTestItemsOk;
	protected int m_JPTestItemsBad;
	protected int m_JPTestCreaturesOk;
	protected int m_JPTestCreaturesBad;

	void SetRandomHealth(EntityAI itemEnt)
	{
		if ( itemEnt )
		{
			float rndHlt = Math.RandomFloat( 0.45, 0.65 );
			itemEnt.SetHealth01( "", "", rndHlt );
		}
	}

	void JPTest_Item(string cls, float x, float z)
	{
		vector pos = Vector(x, 25.0, z);
		Object obj = GetGame().CreateObjectEx(cls, pos, ECE_PLACE_ON_SURFACE | ECE_NOPERSISTENCY_WORLD);
		if ( !obj )
		{
			m_JPTestItemsBad = m_JPTestItemsBad + 1;
			Print("[JPTest] item class not found: " + cls);
			return;
		}
		EntityAI ent = EntityAI.Cast(obj);
		if ( ent )
			ent.SetLifetime(3888000);
		m_JPTestItemsOk = m_JPTestItemsOk + 1;
	}

	void JPTest_Creature(string cls, float x, float z, float yaw)
	{
		float y = GetGame().SurfaceY(x, z);
		vector pos = Vector(x, y, z);
		Object obj = GetGame().CreateObjectEx(cls, pos, ECE_PLACE_ON_SURFACE | ECE_INITAI | ECE_EQUIP_ATTACHMENTS | ECE_NOPERSISTENCY_WORLD);
		if ( !obj )
		{
			m_JPTestCreaturesBad = m_JPTestCreaturesBad + 1;
			Print("[JPTest] creature class not found: " + cls);
			return;
		}
		obj.SetOrientation(Vector(yaw, 0, 0));
		m_JPTestCreaturesOk = m_JPTestCreaturesOk + 1;
	}

	void JPTest_SpawnAll()
	{
		if ( m_JPTestSpawned )
			return;
		m_JPTestSpawned = true;
		Print("[JPTest] spawning the test layout");
		JPTest_Item("JP_Katana", 1000.00, 975.00);
		JPTest_Item("JP_Yari", 1001.50, 975.00);
		JPTest_Item("JP_Yumi", 1003.00, 975.00);
		JPTest_Item("JP_Yumi_XB", 1004.50, 975.00);
		JPTest_Item("JP_Ammo_Ya", 1006.00, 975.00);
		JPTest_Item("JP_Ammo_Ya", 1007.50, 975.00);
		JPTest_Item("JP_Ammo_Ya", 1009.00, 975.00);
		JPTest_Item("Sword", 1010.50, 975.00);
		JPTest_Item("SpearStone", 1012.00, 975.00);
		JPTest_Item("RecurveBow", 1013.50, 975.00);
		JPTest_Item("Crossbow", 1015.00, 975.00);
		JPTest_Item("Ammo_HuntingBolt", 1016.50, 975.00);
		JPTest_Item("Ammo_HuntingBolt", 1018.00, 975.00);
		JPTest_Item("Hatchet", 1019.50, 975.00);
		JPTest_Item("WoodAxe", 1021.00, 975.00);
		JPTest_Item("Machete", 1022.50, 975.00);
		JPTest_Item("JP_BambooPole", 1024.00, 975.00);
		JPTest_Item("JP_BambooPole", 1025.50, 975.00);
		JPTest_Item("Canteen", 1027.00, 975.00);
		JPTest_Item("Hatchet", 1028.50, 975.00);
		JPTest_Item("ChernarusMap", 1030.00, 975.00);
		JPTest_Item("OrienteeringCompass", 1031.50, 975.00);
		JPTest_Item("Binoculars", 1033.00, 975.00);
		JPTest_Item("JP_Kasa", 1034.50, 975.00);
		JPTest_Item("JP_Kasa", 1036.00, 975.00);
		JPTest_Item("JP_Kimono_Short", 1037.50, 975.00);
		JPTest_Item("JP_Kimono_Short", 1039.00, 975.00);
		JPTest_Item("JP_Kimono_Long", 1040.50, 975.00);
		JPTest_Item("JP_Kimono_Long", 1042.00, 975.00);
		JPTest_Item("JP_Tabi_Waraji", 1043.50, 975.00);
		JPTest_Item("JP_Tabi_Waraji", 1045.00, 975.00);
		JPTest_Item("CowboyHat_Brown", 1046.50, 975.00);
		JPTest_Item("Raincoat_Orange", 1000.00, 973.50);
		JPTest_Item("NurseDress_Blue", 1001.50, 973.50);
		JPTest_Item("Sneakers_Black", 1003.00, 973.50);
		JPTest_Creature("ZmbM_CitizenASkinny_Blue", 1010.00, 950.00, 0.0);
		JPTest_Creature("ZmbF_CitizenANormal_Beige", 1022.00, 938.00, 0.0);
		JPTest_Creature("Animal_CervusElaphus", 1037.00, 942.00, 90.0);
		string msg = "[JPTest] items ok " + m_JPTestItemsOk.ToString();
		msg += ", items missing " + m_JPTestItemsBad.ToString();
		msg += ", creatures ok " + m_JPTestCreaturesOk.ToString();
		msg += ", creatures missing " + m_JPTestCreaturesBad.ToString();
		Print(msg);
	}

	override void InvokeOnConnect(PlayerBase player, PlayerIdentity identity)
	{
		super.InvokeOnConnect(player, identity);
		JPTest_SpawnAll();
	}

	override PlayerBase CreateCharacter(PlayerIdentity identity, vector pos, ParamsReadContext ctx, string characterName)
	{
		Entity playerEnt;
		float sx = 1024.0 + Math.RandomFloatInclusive(-1.5, 1.5);
		float sz = 985.0;
		float sy = GetGame().SurfaceY(sx, sz);
		vector spawnPos = Vector(sx, sy, sz);
		playerEnt = GetGame().CreatePlayer( identity, characterName, spawnPos, 0, "NONE" );
		Class.CastTo( m_player, playerEnt );

		GetGame().SelectPlayer( identity, m_player );
		m_player.SetOrientation(Vector(0, 0, 0));

		return m_player;
	}

	override void StartingEquipSetup(PlayerBase player, bool clothesChosen)
	{
		EntityAI itemClothing;
		EntityAI itemEnt;
		float rand;

		itemClothing = player.FindAttachmentBySlotName( "Body" );
		if ( itemClothing )
		{
			SetRandomHealth( itemClothing );

			itemEnt = itemClothing.GetInventory().CreateInInventory( "BandageDressing" );
			player.SetQuickBarEntityShortcut(itemEnt, 2);

			string chemlightArray[] = { "Chemlight_White", "Chemlight_Yellow", "Chemlight_Green", "Chemlight_Red" };
			int rndIndex = Math.RandomInt( 0, 4 );
			itemEnt = itemClothing.GetInventory().CreateInInventory( chemlightArray[rndIndex] );
			SetRandomHealth( itemEnt );
			player.SetQuickBarEntityShortcut(itemEnt, 1);

			rand = Math.RandomFloatInclusive( 0.0, 1.0 );
			if ( rand < 0.35 )
				itemEnt = player.GetInventory().CreateInInventory( "Apple" );
			else if ( rand > 0.65 )
				itemEnt = player.GetInventory().CreateInInventory( "Pear" );
			else
				itemEnt = player.GetInventory().CreateInInventory( "Plum" );
			player.SetQuickBarEntityShortcut(itemEnt, 3);
			SetRandomHealth( itemEnt );
		}

		itemClothing = player.FindAttachmentBySlotName( "Legs" );
		if ( itemClothing )
			SetRandomHealth( itemClothing );

		itemClothing = player.FindAttachmentBySlotName( "Feet" );
	}
};

Mission CreateCustomMission(string path)
{
	return new CustomMission();
}
