// JP_EffTest_high - effort test prop jp_f_tansu (BUILD_LIST row 26), two states. Placeable statics like vanilla
// StaticObj_Furniture_* (HouseNoDestruct, scope 1: object spawner / init.c).
// GENERATED by japan_dev/spikes/effort_test/high/build.py - edit the generator, not this file.
class CfgPatches
{
	class JP_EffTest_high
	{
		units[]={"JP_EffTest_high_Tansu", "JP_EffTest_high_Tansu_Ransacked"};
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"DZ_Data",
			"JP_Common"
		};
	};
};
class CfgVehicles
{
	class HouseNoDestruct;
	// intact
	class JP_EffTest_high_Tansu: HouseNoDestruct
	{
		scope=1;
		displayName="Tansu (clothing chest)";
		model="\JP\effort_test\high\data\jp_efftest_high_tansu.p3d";
	};
	// ransacked
	class JP_EffTest_high_Tansu_Ransacked: HouseNoDestruct
	{
		scope=1;
		displayName="Tansu (clothing chest, ransacked)";
		model="\JP\effort_test\high\data\jp_efftest_high_tansu_ransacked.p3d";
	};
};
