// JP_EffTest_xhigh - effort test (level xhigh): jp_f_tansu, the clothing chest of drawers (BUILD_LIST row 26), two states.
// GENERATED by japan_dev/spikes/effort_test/xhigh/build.py - edit the generator, not this file.
// Static furniture like vanilla StaticObj_Furniture_* (HouseNoDestruct, scope 1): placed by the object
// spawner, init.c or as a proxy. Asset only: no world, map or mission dependency.
class CfgPatches
{
	class JP_EffTest_xhigh
	{
		units[]={};
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"DZ_Data",
			"JP_Common"
		};
	};
};
class CfgVehicles
{
	class HouseNoDestruct;
	// state A: intact, every drawer shut, dusty
	class JP_EffTest_xhigh_Tansu: HouseNoDestruct
	{
		scope=1;
		displayName="Tansu (clothing chest of drawers)";
		model="\JP\effort_test\xhigh\jp_f_tansu.p3d";
	};
	// state B: ransacked, the lock drawer on the floor in front, three drawers pulled out
	class JP_EffTest_xhigh_Tansu_Ransacked: HouseNoDestruct
	{
		scope=1;
		displayName="Tansu (clothing chest of drawers, ransacked)";
		model="\JP\effort_test\xhigh\jp_f_tansu_ransacked.p3d";
	};
};
