// Generated by spikes/W_wearables/tools/configgen.py - do not edit by hand.
class CfgPatches
{
	class JP_Characters
	{
		units[] = {"JP_Kasa", "JP_Kimono_Short", "JP_Kimono_Long", "JP_Tabi_Waraji"};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Data", "DZ_Characters", "DZ_Characters_Headgear", "DZ_Characters_Tops", "DZ_Characters_Shoes"};
	};
};
class CfgVehicles
{
	class CowboyHat_ColorBase;
	class Shirt_ColorBase;
	class Sneakers_ColorBase;
	class JP_Kasa: CowboyHat_ColorBase
	{
		scope = 2;
		displayName = "Kasa (straw hat)";
		descriptionShort = "A conical traveller's hat of woven sedge. Keeps the sun and the rain off.";
		model = "\JP\characters\kasa\jp_kasa_g.p3d";
		inventorySlot[] = {"Headgear"};
		itemInfo[] = {"Clothing", "Headgear"};
		hiddenSelections[] = {"camoGround", "camoMale", "camoFemale"};
		hiddenSelectionsTextures[] =
		{
			"JP\characters\kasa\data\jp_kasa_co.paa",
			"JP\characters\kasa\data\jp_kasa_co.paa",
			"JP\characters\kasa\data\jp_kasa_co.paa"
		};
		class ClothingTypes
		{
			male = "\JP\characters\kasa\jp_kasa_m.p3d";
			female = "\JP\characters\kasa\jp_kasa_f.p3d";
		};
		class DamageSystem
		{
			class GlobalHealth
			{
				class Health
				{
					hitpoints = 100;
					healthLevels[] = {
						{1, {"JP\characters\kasa\data\jp_kasa.rvmat"}},
						{0.7, {"JP\characters\kasa\data\jp_kasa.rvmat"}},
						{0.5, {"JP\characters\kasa\data\jp_kasa_damage.rvmat"}},
						{0.3, {"JP\characters\kasa\data\jp_kasa_damage.rvmat"}},
						{0, {"JP\characters\kasa\data\jp_kasa_destruct.rvmat"}}
					};
				};
			};
		};
	};
	class JP_Kimono_Short: Shirt_ColorBase
	{
		scope = 2;
		displayName = "Kimono (short, indigo)";
		descriptionShort = "A thigh-length cotton kimono dyed with indigo, tied with an obi.";
		model = "\JP\characters\kimono\jp_kimono_short_g.p3d";
		inventorySlot[] = {"Body"};
		itemInfo[] = {"Clothing", "Body"};
		hiddenSelections[] = {"camoGround", "camoMale", "camoFemale", "personality"};
		hiddenSelectionsTextures[] =
		{
			"JP\characters\kimono\data\jp_kimono_short_co.paa",
			"JP\characters\kimono\data\jp_kimono_short_co.paa",
			"JP\characters\kimono\data\jp_kimono_short_co.paa"
		};
		class ClothingTypes
		{
			male = "\JP\characters\kimono\jp_kimono_short_m.p3d";
			female = "\JP\characters\kimono\jp_kimono_short_f.p3d";
		};
		class DamageSystem
		{
			class GlobalHealth
			{
				class Health
				{
					hitpoints = 70;
					healthLevels[] = {
						{1, {"JP\characters\kimono\data\jp_kimono_short.rvmat"}},
						{0.7, {"JP\characters\kimono\data\jp_kimono_short.rvmat"}},
						{0.5, {"JP\characters\kimono\data\jp_kimono_short_damage.rvmat"}},
						{0.3, {"JP\characters\kimono\data\jp_kimono_short_damage.rvmat"}},
						{0, {"JP\characters\kimono\data\jp_kimono_short_destruct.rvmat"}}
					};
				};
			};
			class GlobalArmor
			{
				class Melee
				{
					class Health { damage=0.95; };
					class Blood { damage=1; };
					class Shock { damage=1; };
				};
				class Infected
				{
					class Health { damage=0.95; };
					class Blood { damage=1; };
					class Shock { damage=1; };
				};
			};
		};
	};
	class JP_Kimono_Long: Shirt_ColorBase
	{
		scope = 2;
		displayName = "Kimono (long, indigo)";
		descriptionShort = "A floor-length cotton kimono dyed with indigo, tied with an obi.";
		model = "\JP\characters\kimono\jp_kimono_long_g.p3d";
		inventorySlot[] = {"Body"};
		itemInfo[] = {"Clothing", "Body"};
		hiddenSelections[] = {"camoGround", "camoMale", "camoFemale", "personality"};
		hiddenSelectionsTextures[] =
		{
			"JP\characters\kimono\data\jp_kimono_long_co.paa",
			"JP\characters\kimono\data\jp_kimono_long_co.paa",
			"JP\characters\kimono\data\jp_kimono_long_co.paa"
		};
		class ClothingTypes
		{
			male = "\JP\characters\kimono\jp_kimono_long_m.p3d";
			female = "\JP\characters\kimono\jp_kimono_long_f.p3d";
		};
		class DamageSystem
		{
			class GlobalHealth
			{
				class Health
				{
					hitpoints = 70;
					healthLevels[] = {
						{1, {"JP\characters\kimono\data\jp_kimono_long.rvmat"}},
						{0.7, {"JP\characters\kimono\data\jp_kimono_long.rvmat"}},
						{0.5, {"JP\characters\kimono\data\jp_kimono_long_damage.rvmat"}},
						{0.3, {"JP\characters\kimono\data\jp_kimono_long_damage.rvmat"}},
						{0, {"JP\characters\kimono\data\jp_kimono_long_destruct.rvmat"}}
					};
				};
			};
			class GlobalArmor
			{
				class Melee
				{
					class Health { damage=0.95; };
					class Blood { damage=1; };
					class Shock { damage=1; };
				};
				class Infected
				{
					class Health { damage=0.95; };
					class Blood { damage=1; };
					class Shock { damage=1; };
				};
			};
		};
	};
	class JP_Tabi_Waraji: Sneakers_ColorBase
	{
		scope = 2;
		displayName = "Tabi and waraji";
		descriptionShort = "Split-toe cotton socks worn with straw sandals.";
		model = "\JP\characters\tabi\jp_tabi_waraji_g.p3d";
		inventorySlot[] = {"Feet"};
		itemInfo[] = {"Clothing", "Feet"};
		hiddenSelections[] = {"camoGround", "camoMale", "camoFemale"};
		hiddenSelectionsTextures[] =
		{
			"JP\characters\tabi\data\jp_tabi_waraji_co.paa",
			"JP\characters\tabi\data\jp_tabi_waraji_co.paa",
			"JP\characters\tabi\data\jp_tabi_waraji_co.paa"
		};
		class ClothingTypes
		{
			male = "\JP\characters\tabi\jp_tabi_waraji_m.p3d";
			female = "\JP\characters\tabi\jp_tabi_waraji_f.p3d";
		};
		class DamageSystem
		{
			class GlobalHealth
			{
				class Health
				{
					hitpoints = 80;
					healthLevels[] = {
						{1, {"JP\characters\tabi\data\jp_tabi_waraji.rvmat"}},
						{0.7, {"JP\characters\tabi\data\jp_tabi_waraji.rvmat"}},
						{0.5, {"JP\characters\tabi\data\jp_tabi_waraji_damage.rvmat"}},
						{0.3, {"JP\characters\tabi\data\jp_tabi_waraji_damage.rvmat"}},
						{0, {"JP\characters\tabi\data\jp_tabi_waraji_destruct.rvmat"}}
					};
				};
			};
		};
	};
};
