// JP_Furniture - interior props (jp_f_*), placed as proxies inside JP buildings like vanilla
// \dz\structures\furniture, plus a StaticObj_JP_F_<name> class each (HouseNoDestruct, scope 1) as vanilla
// StaticObj_Furniture_<name>. No script, no vanilla change, no map dependency.
// GENERATED by japan_dev/spikes/B3a/build.py - edit the generator, not this file.
class CfgPatches
{
	class JP_Furniture
	{
		units[]={};
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"DZ_Data",
			"JP_Common"
		};
	};
};
class CfgVehicles
{
	class HouseNoDestruct;
	// jp_f_kama (kitchen)
	class StaticObj_JP_F_Kama: HouseNoDestruct
	{
		scope=1;
		displayName="Rice pot (kama) with lid";
		model="\JP\furniture\kitchen\jp_f_kama.p3d";
	};
	class StaticObj_JP_F_Kama_Nolid: HouseNoDestruct
	{
		scope=1;
		displayName="Rice pot, lid off, rusted";
		model="\JP\furniture\kitchen\jp_f_kama_nolid.p3d";
	};
	class StaticObj_JP_F_Kama_Nabe: HouseNoDestruct
	{
		scope=1;
		displayName="Small pot (nabe) with bail";
		model="\JP\furniture\kitchen\jp_f_kama_nabe.p3d";
	};
	class StaticObj_JP_F_Kama_Nabe_Rusted: HouseNoDestruct
	{
		scope=1;
		displayName="Small pot, rusted, burnt crust";
		model="\JP\furniture\kitchen\jp_f_kama_nabe_rusted.p3d";
	};
	// jp_f_jizai_kagi (kitchen)
	class StaticObj_JP_F_Jizai_Kagi: HouseNoDestruct
	{
		scope=1;
		displayName="Pot hook (jizai-kagi) with fish lever";
		model="\JP\furniture\kitchen\jp_f_jizai_kagi.p3d";
	};
	class StaticObj_JP_F_Jizai_Kagi_Abandoned: HouseNoDestruct
	{
		scope=1;
		displayName="Pot hook, lever jammed high, rusted pot";
		model="\JP\furniture\kitchen\jp_f_jizai_kagi_abandoned.p3d";
	};
	class StaticObj_JP_F_Jizai_Kagi_Plain: HouseNoDestruct
	{
		scope=1;
		displayName="Pot hook, plain bar lever";
		model="\JP\furniture\kitchen\jp_f_jizai_kagi_plain.p3d";
	};
	class StaticObj_JP_F_Jizai_Kagi_Plain_Abandoned: HouseNoDestruct
	{
		scope=1;
		displayName="Pot hook (plain), jammed, rusted pot";
		model="\JP\furniture\kitchen\jp_f_jizai_kagi_plain_abandoned.p3d";
	};
	// jp_f_mizugame (kitchen)
	class StaticObj_JP_F_Mizugame: HouseNoDestruct
	{
		scope=1;
		displayName="Water jar (mizugame), lid and dipper";
		model="\JP\furniture\kitchen\jp_f_mizugame.p3d";
	};
	class StaticObj_JP_F_Mizugame_Open: HouseNoDestruct
	{
		scope=1;
		displayName="Water jar, lid off leaning, dry";
		model="\JP\furniture\kitchen\jp_f_mizugame_open.p3d";
	};
	class StaticObj_JP_F_Mizugame_Broken: HouseNoDestruct
	{
		scope=1;
		displayName="Water jar, cracked, piece on the floor";
		model="\JP\furniture\kitchen\jp_f_mizugame_broken.p3d";
	};
	// jp_f_oke (kitchen)
	class StaticObj_JP_F_Oke_Bucket: HouseNoDestruct
	{
		scope=1;
		displayName="Handled bucket (oke)";
		model="\JP\furniture\kitchen\jp_f_oke_bucket.p3d";
	};
	class StaticObj_JP_F_Oke_Tipped: HouseNoDestruct
	{
		scope=1;
		displayName="Bucket on its side";
		model="\JP\furniture\kitchen\jp_f_oke_tipped.p3d";
	};
	class StaticObj_JP_F_Oke_Tarai: HouseNoDestruct
	{
		scope=1;
		displayName="Shallow washing tub (tarai)";
		model="\JP\furniture\kitchen\jp_f_oke_tarai.p3d";
	};
	class StaticObj_JP_F_Oke_Tarai_Dry: HouseNoDestruct
	{
		scope=1;
		displayName="Tarai, dried out, stave and hoop off";
		model="\JP\furniture\kitchen\jp_f_oke_tarai_dry.p3d";
	};
	class StaticObj_JP_F_Oke_Pickle: HouseNoDestruct
	{
		scope=1;
		displayName="Pickle tub with lid and stone";
		model="\JP\furniture\kitchen\jp_f_oke_pickle.p3d";
	};
	class StaticObj_JP_F_Oke_Pickle_Open: HouseNoDestruct
	{
		scope=1;
		displayName="Pickle tub, lid off, stone on the floor";
		model="\JP\furniture\kitchen\jp_f_oke_pickle_open.p3d";
	};
	// jp_f_tana (kitchen)
	class StaticObj_JP_F_Tana_091_1: HouseNoDestruct
	{
		scope=1;
		displayName="Wall shelf 0.91 m, 1 board";
		model="\JP\furniture\kitchen\jp_f_tana_091_1.p3d";
	};
	class StaticObj_JP_F_Tana_091_1_Sag: HouseNoDestruct
	{
		scope=1;
		displayName="Wall shelf 0.91 m, 1 board, sagging";
		model="\JP\furniture\kitchen\jp_f_tana_091_1_sag.p3d";
	};
	class StaticObj_JP_F_Tana_091_3: HouseNoDestruct
	{
		scope=1;
		displayName="Wall shelf 0.91 m, 3 boards";
		model="\JP\furniture\kitchen\jp_f_tana_091_3.p3d";
	};
	class StaticObj_JP_F_Tana_091_3_Sag: HouseNoDestruct
	{
		scope=1;
		displayName="Wall shelf 0.91 m, 3 boards, sagging";
		model="\JP\furniture\kitchen\jp_f_tana_091_3_sag.p3d";
	};
	class StaticObj_JP_F_Tana_136_1: HouseNoDestruct
	{
		scope=1;
		displayName="Wall shelf 1.36 m, 1 board";
		model="\JP\furniture\kitchen\jp_f_tana_136_1.p3d";
	};
	class StaticObj_JP_F_Tana_136_1_Sag: HouseNoDestruct
	{
		scope=1;
		displayName="Wall shelf 1.36 m, 1 board, sagging";
		model="\JP\furniture\kitchen\jp_f_tana_136_1_sag.p3d";
	};
	class StaticObj_JP_F_Tana_136_3: HouseNoDestruct
	{
		scope=1;
		displayName="Wall shelf 1.36 m, 3 boards";
		model="\JP\furniture\kitchen\jp_f_tana_136_3.p3d";
	};
	class StaticObj_JP_F_Tana_136_3_Sag: HouseNoDestruct
	{
		scope=1;
		displayName="Wall shelf 1.36 m, 3 boards, sagging";
		model="\JP\furniture\kitchen\jp_f_tana_136_3_sag.p3d";
	};
	class StaticObj_JP_F_Tana_182_1: HouseNoDestruct
	{
		scope=1;
		displayName="Wall shelf 1.82 m, 1 board";
		model="\JP\furniture\kitchen\jp_f_tana_182_1.p3d";
	};
	class StaticObj_JP_F_Tana_182_1_Sag: HouseNoDestruct
	{
		scope=1;
		displayName="Wall shelf 1.82 m, 1 board, sagging";
		model="\JP\furniture\kitchen\jp_f_tana_182_1_sag.p3d";
	};
	class StaticObj_JP_F_Tana_182_3: HouseNoDestruct
	{
		scope=1;
		displayName="Wall shelf 1.82 m, 3 boards";
		model="\JP\furniture\kitchen\jp_f_tana_182_3.p3d";
	};
	class StaticObj_JP_F_Tana_182_3_Sag: HouseNoDestruct
	{
		scope=1;
		displayName="Wall shelf 1.82 m, 3 boards, sagging";
		model="\JP\furniture\kitchen\jp_f_tana_182_3_sag.p3d";
	};
	// jp_f_firewood (kitchen)
	class StaticObj_JP_F_Firewood_Stack: HouseNoDestruct
	{
		scope=1;
		displayName="Firewood stack (maki)";
		model="\JP\furniture\kitchen\jp_f_firewood_stack.p3d";
	};
	class StaticObj_JP_F_Firewood_Low: HouseNoDestruct
	{
		scope=1;
		displayName="Firewood stack, half used, logs rolled";
		model="\JP\furniture\kitchen\jp_f_firewood_low.p3d";
	};
	class StaticObj_JP_F_Firewood_Bundle: HouseNoDestruct
	{
		scope=1;
		displayName="Brushwood bundles (soda)";
		model="\JP\furniture\kitchen\jp_f_firewood_bundle.p3d";
	};
	class StaticObj_JP_F_Firewood_Bundle_Loose: HouseNoDestruct
	{
		scope=1;
		displayName="Brushwood bundle burst, sticks scattered";
		model="\JP\furniture\kitchen\jp_f_firewood_bundle_loose.p3d";
	};
	// jp_f_jar (kitchen)
	class StaticObj_JP_F_Jar_S: HouseNoDestruct
	{
		scope=1;
		displayName="Storage jar S";
		model="\JP\furniture\kitchen\jp_f_jar_s.p3d";
	};
	class StaticObj_JP_F_Jar_M: HouseNoDestruct
	{
		scope=1;
		displayName="Storage jar M";
		model="\JP\furniture\kitchen\jp_f_jar_m.p3d";
	};
	class StaticObj_JP_F_Jar_L: HouseNoDestruct
	{
		scope=1;
		displayName="Storage jar L";
		model="\JP\furniture\kitchen\jp_f_jar_l.p3d";
	};
	class StaticObj_JP_F_Jar_S_Pale: HouseNoDestruct
	{
		scope=1;
		displayName="Storage jar S (pale glaze)";
		model="\JP\furniture\kitchen\jp_f_jar_s_pale.p3d";
	};
	class StaticObj_JP_F_Jar_M_Pale: HouseNoDestruct
	{
		scope=1;
		displayName="Storage jar M (pale glaze)";
		model="\JP\furniture\kitchen\jp_f_jar_m_pale.p3d";
	};
	class StaticObj_JP_F_Jar_S_Open: HouseNoDestruct
	{
		scope=1;
		displayName="Storage jar S, lid off";
		model="\JP\furniture\kitchen\jp_f_jar_s_open.p3d";
	};
	class StaticObj_JP_F_Jar_M_Open: HouseNoDestruct
	{
		scope=1;
		displayName="Storage jar M, lid off";
		model="\JP\furniture\kitchen\jp_f_jar_m_open.p3d";
	};
	class StaticObj_JP_F_Jar_L_Open: HouseNoDestruct
	{
		scope=1;
		displayName="Storage jar L, lid off";
		model="\JP\furniture\kitchen\jp_f_jar_l_open.p3d";
	};
	class StaticObj_JP_F_Jar_M_Broken: HouseNoDestruct
	{
		scope=1;
		displayName="Storage jar M, broken";
		model="\JP\furniture\kitchen\jp_f_jar_m_broken.p3d";
	};
	// jp_f_andon (heat_light)
	class StaticObj_JP_F_Andon_Kaku: HouseNoDestruct
	{
		scope=1;
		displayName="Standing paper lamp (andon)";
		model="\JP\furniture\heat_light\jp_f_andon_kaku.p3d";
	};
	class StaticObj_JP_F_Andon_Kaku_Tipped: HouseNoDestruct
	{
		scope=1;
		displayName="Andon, knocked over, paper torn";
		model="\JP\furniture\heat_light\jp_f_andon_kaku_tipped.p3d";
	};
	class StaticObj_JP_F_Andon_Ariake: HouseNoDestruct
	{
		scope=1;
		displayName="Bedside lamp (ariake andon)";
		model="\JP\furniture\heat_light\jp_f_andon_ariake.p3d";
	};
	class StaticObj_JP_F_Andon_Ariake_Tipped: HouseNoDestruct
	{
		scope=1;
		displayName="Bedside lamp, knocked over";
		model="\JP\furniture\heat_light\jp_f_andon_ariake_tipped.p3d";
	};
	// jp_f_hibachi (heat_light)
	class StaticObj_JP_F_Hibachi_Round: HouseNoDestruct
	{
		scope=1;
		displayName="Round ceramic brazier (hibachi)";
		model="\JP\furniture\heat_light\jp_f_hibachi_round.p3d";
	};
	class StaticObj_JP_F_Hibachi_Round_Tipped: HouseNoDestruct
	{
		scope=1;
		displayName="Round brazier, tipped, ash spilled";
		model="\JP\furniture\heat_light\jp_f_hibachi_round_tipped.p3d";
	};
	class StaticObj_JP_F_Hibachi_Box: HouseNoDestruct
	{
		scope=1;
		displayName="Wooden box brazier";
		model="\JP\furniture\heat_light\jp_f_hibachi_box.p3d";
	};
	class StaticObj_JP_F_Hibachi_Box_Tipped: HouseNoDestruct
	{
		scope=1;
		displayName="Box brazier, tipped, ash spilled";
		model="\JP\furniture\heat_light\jp_f_hibachi_box_tipped.p3d";
	};
	// jp_f_tabakobon (heat_light)
	class StaticObj_JP_F_Tabakobon: HouseNoDestruct
	{
		scope=1;
		displayName="Tobacco tray (tabako-bon)";
		model="\JP\furniture\heat_light\jp_f_tabakobon.p3d";
	};
	class StaticObj_JP_F_Tabakobon_Spilled: HouseNoDestruct
	{
		scope=1;
		displayName="Tobacco tray on its side, ash spilled";
		model="\JP\furniture\heat_light\jp_f_tabakobon_spilled.p3d";
	};
	// jp_f_nagamochi (storage)
	class StaticObj_JP_F_Nagamochi: HouseNoDestruct
	{
		scope=1;
		displayName="Long chest (nagamochi)";
		model="\JP\furniture\storage\jp_f_nagamochi.p3d";
	};
	class StaticObj_JP_F_Nagamochi_Open: HouseNoDestruct
	{
		scope=1;
		displayName="Long chest, lid thrown back, cloth spilling";
		model="\JP\furniture\storage\jp_f_nagamochi_open.p3d";
	};
	// jp_f_tansu (storage)
	class StaticObj_JP_F_Tansu: HouseNoDestruct
	{
		scope=1;
		displayName="Tansu (clothing chest)";
		model="\JP\furniture\storage\jp_f_tansu.p3d";
	};
	class StaticObj_JP_F_Tansu_Ransacked: HouseNoDestruct
	{
		scope=1;
		displayName="Tansu (ransacked)";
		model="\JP\furniture\storage\jp_f_tansu_ransacked.p3d";
	};
	class StaticObj_JP_F_Tansu_Single: HouseNoDestruct
	{
		scope=1;
		displayName="Tansu, single box";
		model="\JP\furniture\storage\jp_f_tansu_single.p3d";
	};
	class StaticObj_JP_F_Tansu_Single_Ransacked: HouseNoDestruct
	{
		scope=1;
		displayName="Tansu, single box (ransacked)";
		model="\JP\furniture\storage\jp_f_tansu_single_ransacked.p3d";
	};
	// jp_f_kori (storage)
	class StaticObj_JP_F_Kori: HouseNoDestruct
	{
		scope=1;
		displayName="Wicker trunk (kori)";
		model="\JP\furniture\storage\jp_f_kori.p3d";
	};
	class StaticObj_JP_F_Kori_2: HouseNoDestruct
	{
		scope=1;
		displayName="Wicker trunks, stack of two";
		model="\JP\furniture\storage\jp_f_kori_2.p3d";
	};
	class StaticObj_JP_F_Kori_Open: HouseNoDestruct
	{
		scope=1;
		displayName="Wicker trunk, lid off, garment out";
		model="\JP\furniture\storage\jp_f_kori_open.p3d";
	};
	// jp_f_box (storage)
	class StaticObj_JP_F_Box_S: HouseNoDestruct
	{
		scope=1;
		displayName="Wooden box, small";
		model="\JP\furniture\storage\jp_f_box_s.p3d";
	};
	class StaticObj_JP_F_Box_M: HouseNoDestruct
	{
		scope=1;
		displayName="Wooden box, medium";
		model="\JP\furniture\storage\jp_f_box_m.p3d";
	};
	class StaticObj_JP_F_Box_L: HouseNoDestruct
	{
		scope=1;
		displayName="Wooden box, large";
		model="\JP\furniture\storage\jp_f_box_l.p3d";
	};
	class StaticObj_JP_F_Box_Stack3: HouseNoDestruct
	{
		scope=1;
		displayName="Wooden boxes, stack of three";
		model="\JP\furniture\storage\jp_f_box_stack3.p3d";
	};
	class StaticObj_JP_F_Box_S_Lacquer: HouseNoDestruct
	{
		scope=1;
		displayName="Lacquered box, small (T3)";
		model="\JP\furniture\storage\jp_f_box_s_lacquer.p3d";
	};
	class StaticObj_JP_F_Box_M_Lacquer: HouseNoDestruct
	{
		scope=1;
		displayName="Lacquered box, medium (T3)";
		model="\JP\furniture\storage\jp_f_box_m_lacquer.p3d";
	};
	class StaticObj_JP_F_Box_Open: HouseNoDestruct
	{
		scope=1;
		displayName="Wooden box, lid off, spilled";
		model="\JP\furniture\storage\jp_f_box_open.p3d";
	};
	class StaticObj_JP_F_Box_Stack3_Toppled: HouseNoDestruct
	{
		scope=1;
		displayName="Box stack, small box knocked off";
		model="\JP\furniture\storage\jp_f_box_stack3_toppled.p3d";
	};
	// jp_f_tawara (storage)
	class StaticObj_JP_F_Tawara: HouseNoDestruct
	{
		scope=1;
		displayName="Straw rice bale (tawara)";
		model="\JP\furniture\storage\jp_f_tawara.p3d";
	};
	class StaticObj_JP_F_Tawara_Burst: HouseNoDestruct
	{
		scope=1;
		displayName="Rice bale, burst, rice spilled";
		model="\JP\furniture\storage\jp_f_tawara_burst.p3d";
	};
	class StaticObj_JP_F_Tawara_Stack6: HouseNoDestruct
	{
		scope=1;
		displayName="Rice bales, pyramid of six";
		model="\JP\furniture\storage\jp_f_tawara_stack6.p3d";
	};
	class StaticObj_JP_F_Tawara_Stack6_Burst: HouseNoDestruct
	{
		scope=1;
		displayName="Rice bales, top one burst";
		model="\JP\furniture\storage\jp_f_tawara_stack6_burst.p3d";
	};
	class StaticObj_JP_F_Tawara_Kamasu: HouseNoDestruct
	{
		scope=1;
		displayName="Straw bag (kamasu)";
		model="\JP\furniture\storage\jp_f_tawara_kamasu.p3d";
	};
	class StaticObj_JP_F_Tawara_Kamasu_Stack3: HouseNoDestruct
	{
		scope=1;
		displayName="Straw bags, stack of three";
		model="\JP\furniture\storage\jp_f_tawara_kamasu_stack3.p3d";
	};
	class StaticObj_JP_F_Tawara_Kamasu_Burst: HouseNoDestruct
	{
		scope=1;
		displayName="Straw bag, split and slumped";
		model="\JP\furniture\storage\jp_f_tawara_kamasu_burst.p3d";
	};
	// jp_f_rack (storage)
	class StaticObj_JP_F_Rack_1ken: HouseNoDestruct
	{
		scope=1;
		displayName="Board shelving 1.82 m (kura shelves)";
		model="\JP\furniture\storage\jp_f_rack_1ken.p3d";
	};
	class StaticObj_JP_F_Rack_1ken_Collapsed: HouseNoDestruct
	{
		scope=1;
		displayName="Board shelving 1.82 m, board down, goods on the floor";
		model="\JP\furniture\storage\jp_f_rack_1ken_collapsed.p3d";
	};
	class StaticObj_JP_F_Rack_Half: HouseNoDestruct
	{
		scope=1;
		displayName="Board shelving 0.91 m";
		model="\JP\furniture\storage\jp_f_rack_half.p3d";
	};
	class StaticObj_JP_F_Rack_Half_Collapsed: HouseNoDestruct
	{
		scope=1;
		displayName="Board shelving 0.91 m, board down";
		model="\JP\furniture\storage\jp_f_rack_half_collapsed.p3d";
	};
	// jp_f_futon_stack (bedding)
	class StaticObj_JP_F_Futon_Stack: HouseNoDestruct
	{
		scope=1;
		displayName="Folded bedding stack (futon, yogi)";
		model="\JP\furniture\bedding\jp_f_futon_stack.p3d";
	};
	class StaticObj_JP_F_Futon_Stack_Slumped: HouseNoDestruct
	{
		scope=1;
		displayName="Bedding stack slumped, quilt dragged off";
		model="\JP\furniture\bedding\jp_f_futon_stack_slumped.p3d";
	};
	// jp_f_futon_laid (bedding)
	class StaticObj_JP_F_Futon_Laid: HouseNoDestruct
	{
		scope=1;
		displayName="Laid-out bedding, quilt thrown back";
		model="\JP\furniture\bedding\jp_f_futon_laid.p3d";
	};
	class StaticObj_JP_F_Futon_Laid_Dragged: HouseNoDestruct
	{
		scope=1;
		displayName="Laid-out bedding, quilt dragged aside, stained";
		model="\JP\furniture\bedding\jp_f_futon_laid_dragged.p3d";
	};
	// jp_f_mushiro (bedding)
	class StaticObj_JP_F_Mushiro: HouseNoDestruct
	{
		scope=1;
		displayName="Straw floor mat (mushiro)";
		model="\JP\furniture\bedding\jp_f_mushiro.p3d";
	};
	class StaticObj_JP_F_Mushiro_Torn: HouseNoDestruct
	{
		scope=1;
		displayName="Straw mat, torn, corner curled";
		model="\JP\furniture\bedding\jp_f_mushiro_torn.p3d";
	};
	class StaticObj_JP_F_Mushiro_Rolled: HouseNoDestruct
	{
		scope=1;
		displayName="Straw mat, rolled";
		model="\JP\furniture\bedding\jp_f_mushiro_rolled.p3d";
	};
	class StaticObj_JP_F_Mushiro_Rolled_Loose: HouseNoDestruct
	{
		scope=1;
		displayName="Straw mat, half unrolled";
		model="\JP\furniture\bedding\jp_f_mushiro_rolled_loose.p3d";
	};
	class StaticObj_JP_F_Mushiro_Pile: HouseNoDestruct
	{
		scope=1;
		displayName="Straw mats, small pile";
		model="\JP\furniture\bedding\jp_f_mushiro_pile.p3d";
	};
	class StaticObj_JP_F_Mushiro_Pile_Spread: HouseNoDestruct
	{
		scope=1;
		displayName="Straw mats, pile slid apart";
		model="\JP\furniture\bedding\jp_f_mushiro_pile_spread.p3d";
	};
	// jp_f_zukue (shop)
	class StaticObj_JP_F_Zukue_Choba: HouseNoDestruct
	{
		scope=1;
		displayName="Account desk (choba-zukue)";
		model="\JP\furniture\shop\jp_f_zukue_choba.p3d";
	};
	class StaticObj_JP_F_Zukue_Choba_Tipped: HouseNoDestruct
	{
		scope=1;
		displayName="Account desk on its side, ledger scattered";
		model="\JP\furniture\shop\jp_f_zukue_choba_tipped.p3d";
	};
	class StaticObj_JP_F_Zukue_Plain: HouseNoDestruct
	{
		scope=1;
		displayName="Low writing desk (fuzukue)";
		model="\JP\furniture\shop\jp_f_zukue_plain.p3d";
	};
	class StaticObj_JP_F_Zukue_Plain_Tipped: HouseNoDestruct
	{
		scope=1;
		displayName="Writing desk on its side";
		model="\JP\furniture\shop\jp_f_zukue_plain_tipped.p3d";
	};
	// jp_f_choba_goshi (shop)
	class StaticObj_JP_F_Choba_Goshi_3: HouseNoDestruct
	{
		scope=1;
		displayName="Counting-desk lattice, three folds";
		model="\JP\furniture\shop\jp_f_choba_goshi_3.p3d";
	};
	class StaticObj_JP_F_Choba_Goshi_3_Knocked: HouseNoDestruct
	{
		scope=1;
		displayName="Counting-desk lattice, one fold knocked flat";
		model="\JP\furniture\shop\jp_f_choba_goshi_3_knocked.p3d";
	};
	class StaticObj_JP_F_Choba_Goshi_2: HouseNoDestruct
	{
		scope=1;
		displayName="Counting-desk lattice, two folds";
		model="\JP\furniture\shop\jp_f_choba_goshi_2.p3d";
	};
	class StaticObj_JP_F_Choba_Goshi_2_Knocked: HouseNoDestruct
	{
		scope=1;
		displayName="Counting-desk lattice (two folds), one knocked flat";
		model="\JP\furniture\shop\jp_f_choba_goshi_2_knocked.p3d";
	};
	// jp_f_misedana (shop)
	class StaticObj_JP_F_Misedana_1ken: HouseNoDestruct
	{
		scope=1;
		displayName="Stepped goods stand 1.82 m";
		model="\JP\furniture\shop\jp_f_misedana_1ken.p3d";
	};
	class StaticObj_JP_F_Misedana_1ken_Toppled: HouseNoDestruct
	{
		scope=1;
		displayName="Goods stand 1.82 m, toppled forward";
		model="\JP\furniture\shop\jp_f_misedana_1ken_toppled.p3d";
	};
	class StaticObj_JP_F_Misedana_Half: HouseNoDestruct
	{
		scope=1;
		displayName="Stepped goods stand 0.91 m";
		model="\JP\furniture\shop\jp_f_misedana_half.p3d";
	};
	class StaticObj_JP_F_Misedana_Half_Toppled: HouseNoDestruct
	{
		scope=1;
		displayName="Goods stand 0.91 m, toppled forward";
		model="\JP\furniture\shop\jp_f_misedana_half_toppled.p3d";
	};
	// jp_f_goods_general (shop)
	class StaticObj_JP_F_Goods_General_Cloth: HouseNoDestruct
	{
		scope=1;
		displayName="Goods: cloth bolts and sandals, stacked";
		model="\JP\furniture\shop\jp_f_goods_general_cloth.p3d";
	};
	class StaticObj_JP_F_Goods_General_Cloth_Swept: HouseNoDestruct
	{
		scope=1;
		displayName="Goods: cloth swept off, a bolt unrolled";
		model="\JP\furniture\shop\jp_f_goods_general_cloth_swept.p3d";
	};
	class StaticObj_JP_F_Goods_General_Paper: HouseNoDestruct
	{
		scope=1;
		displayName="Goods: paper bundles, packages, a box";
		model="\JP\furniture\shop\jp_f_goods_general_paper.p3d";
	};
	class StaticObj_JP_F_Goods_General_Paper_Swept: HouseNoDestruct
	{
		scope=1;
		displayName="Goods: paper and packages swept off";
		model="\JP\furniture\shop\jp_f_goods_general_paper_swept.p3d";
	};
	// jp_f_debris (debris)
	class StaticObj_JP_F_Debris_Leaves: HouseNoDestruct
	{
		scope=1;
		displayName="Litter: autumn leaves blown in";
		model="\JP\furniture\debris\jp_f_debris_leaves.p3d";
	};
	class StaticObj_JP_F_Debris_Straw: HouseNoDestruct
	{
		scope=1;
		displayName="Litter: straw and dust";
		model="\JP\furniture\debris\jp_f_debris_straw.p3d";
	};
	class StaticObj_JP_F_Debris_Paper: HouseNoDestruct
	{
		scope=1;
		displayName="Litter: torn paper and shoji squares";
		model="\JP\furniture\debris\jp_f_debris_paper.p3d";
	};
	class StaticObj_JP_F_Debris_Shards: HouseNoDestruct
	{
		scope=1;
		displayName="Litter: broken bowls";
		model="\JP\furniture\debris\jp_f_debris_shards.p3d";
	};
	// jp_f_kamidana (fittings)
	class StaticObj_JP_F_Kamidana_Plain: HouseNoDestruct
	{
		scope=1;
		displayName="God shelf (kamidana) with shrine box";
		model="\JP\furniture\fittings\jp_f_kamidana_plain.p3d";
	};
	// jp_f_nagashi (fittings)
	class StaticObj_JP_F_Nagashi_Wood: HouseNoDestruct
	{
		scope=1;
		displayName="Kitchen sink (nagashi), wooden trough on legs";
		model="\JP\furniture\fittings\jp_f_nagashi_wood.p3d";
	};
	// jp_f_mino_pegs (wall)
	class StaticObj_JP_F_Mino_Pegs: HouseNoDestruct
	{
		scope=1;
		displayName="Wall pegs: straw raincoat, hat, hoe, sickle";
		model="\JP\furniture\wall\jp_f_mino_pegs.p3d";
	};
	class StaticObj_JP_F_Mino_Pegs_Rain: HouseNoDestruct
	{
		scope=1;
		displayName="Wall pegs: straw raincoat and hat";
		model="\JP\furniture\wall\jp_f_mino_pegs_rain.p3d";
	};
	class StaticObj_JP_F_Mino_Pegs_Fallen: HouseNoDestruct
	{
		scope=1;
		displayName="Wall pegs, the hat fallen, one peg empty";
		model="\JP\furniture\wall\jp_f_mino_pegs_fallen.p3d";
	};
	// jp_f_ofuda (wall)
	class StaticObj_JP_F_Ofuda_Single: HouseNoDestruct
	{
		scope=1;
		displayName="Paper charm (Ise taima) on a post";
		model="\JP\furniture\wall\jp_f_ofuda_single.p3d";
	};
	class StaticObj_JP_F_Ofuda_Akiba: HouseNoDestruct
	{
		scope=1;
		displayName="Fire charm (Akiba) on a kitchen post";
		model="\JP\furniture\wall\jp_f_ofuda_akiba.p3d";
	};
	class StaticObj_JP_F_Ofuda_Row: HouseNoDestruct
	{
		scope=1;
		displayName="Three paper charms on a post, old and new";
		model="\JP\furniture\wall\jp_f_ofuda_row.p3d";
	};
	class StaticObj_JP_F_Ofuda_Torn: HouseNoDestruct
	{
		scope=1;
		displayName="Paper charms, faded, one peeling, one torn away";
		model="\JP\furniture\wall\jp_f_ofuda_torn.p3d";
	};
	// jp_f_koyomi (wall)
	class StaticObj_JP_F_Koyomi: HouseNoDestruct
	{
		scope=1;
		displayName="Printed calendar (Kyoho 15) on the wall";
		model="\JP\furniture\wall\jp_f_koyomi.p3d";
	};
	class StaticObj_JP_F_Koyomi_Curled: HouseNoDestruct
	{
		scope=1;
		displayName="Calendar, faded, a corner curling off";
		model="\JP\furniture\wall\jp_f_koyomi_curled.p3d";
	};
	// jp_f_utensil_board (wall)
	class StaticObj_JP_F_Utensil_Board: HouseNoDestruct
	{
		scope=1;
		displayName="Kitchen utensil board: dipper, paddle, ladles, knives, board";
		model="\JP\furniture\wall\jp_f_utensil_board.p3d";
	};
	class StaticObj_JP_F_Utensil_Board_Small: HouseNoDestruct
	{
		scope=1;
		displayName="Small utensil board";
		model="\JP\furniture\wall\jp_f_utensil_board_small.p3d";
	};
	class StaticObj_JP_F_Utensil_Board_Fallen: HouseNoDestruct
	{
		scope=1;
		displayName="Utensil board, board and ladle on the floor";
		model="\JP\furniture\wall\jp_f_utensil_board_fallen.p3d";
	};
	// jp_f_tool_wall (wall)
	class StaticObj_JP_F_Tool_Wall: HouseNoDestruct
	{
		scope=1;
		displayName="Tool wall: saw, adze, axe, hatchet";
		model="\JP\furniture\wall\jp_f_tool_wall.p3d";
	};
	class StaticObj_JP_F_Tool_Wall_Wood: HouseNoDestruct
	{
		scope=1;
		displayName="Tool wall: axes, saw, hatchet";
		model="\JP\furniture\wall\jp_f_tool_wall_wood.p3d";
	};
	class StaticObj_JP_F_Tool_Wall_Taken: HouseNoDestruct
	{
		scope=1;
		displayName="Tool wall, axe taken, saw on the floor";
		model="\JP\furniture\wall\jp_f_tool_wall_taken.p3d";
	};
	// jp_f_rope_pegs (wall)
	class StaticObj_JP_F_Rope_Pegs_2: HouseNoDestruct
	{
		scope=1;
		displayName="Two rope coils on pegs";
		model="\JP\furniture\wall\jp_f_rope_pegs_2.p3d";
	};
	class StaticObj_JP_F_Rope_Pegs_3: HouseNoDestruct
	{
		scope=1;
		displayName="Three rope coils on pegs";
		model="\JP\furniture\wall\jp_f_rope_pegs_3.p3d";
	};
	class StaticObj_JP_F_Rope_Pegs_Fallen: HouseNoDestruct
	{
		scope=1;
		displayName="Rope coils, one fallen and paid out";
		model="\JP\furniture\wall\jp_f_rope_pegs_fallen.p3d";
	};
	// jp_f_sandals_hung (wall)
	class StaticObj_JP_F_Sandals_Hung_Wall: HouseNoDestruct
	{
		scope=1;
		displayName="Straw sandals in bunches on wall pegs";
		model="\JP\furniture\wall\jp_f_sandals_hung_wall.p3d";
	};
	class StaticObj_JP_F_Sandals_Hung_Beam: HouseNoDestruct
	{
		scope=1;
		displayName="A bunch of straw sandals on a beam hook";
		model="\JP\furniture\wall\jp_f_sandals_hung_beam.p3d";
	};
	class StaticObj_JP_F_Sandals_Hung_Fallen: HouseNoDestruct
	{
		scope=1;
		displayName="Straw sandals, one bunch burst on the floor";
		model="\JP\furniture\wall\jp_f_sandals_hung_fallen.p3d";
	};
	// jp_f_hoshigaki (wall)
	class StaticObj_JP_F_Hoshigaki_3: HouseNoDestruct
	{
		scope=1;
		displayName="Dried persimmons, three strings";
		model="\JP\furniture\wall\jp_f_hoshigaki_3.p3d";
	};
	class StaticObj_JP_F_Hoshigaki_5: HouseNoDestruct
	{
		scope=1;
		displayName="Dried persimmons, five strings";
		model="\JP\furniture\wall\jp_f_hoshigaki_5.p3d";
	};
	class StaticObj_JP_F_Hoshigaki_Rotten: HouseNoDestruct
	{
		scope=1;
		displayName="Dried persimmons, blackened, gaps, a broken string";
		model="\JP\furniture\wall\jp_f_hoshigaki_rotten.p3d";
	};
	// jp_f_drying (wall)
	class StaticObj_JP_F_Drying_Daikon: HouseNoDestruct
	{
		scope=1;
		displayName="Radishes drying on a pole";
		model="\JP\furniture\wall\jp_f_drying_daikon.p3d";
	};
	class StaticObj_JP_F_Drying_Chilli: HouseNoDestruct
	{
		scope=1;
		displayName="Chilli strings drying";
		model="\JP\furniture\wall\jp_f_drying_chilli.p3d";
	};
	class StaticObj_JP_F_Drying_Fish: HouseNoDestruct
	{
		scope=1;
		displayName="Small fish drying on straws";
		model="\JP\furniture\wall\jp_f_drying_fish.p3d";
	};
	class StaticObj_JP_F_Drying_Daikon_Shrivelled: HouseNoDestruct
	{
		scope=1;
		displayName="Radishes shrivelled, two fallen";
		model="\JP\furniture\wall\jp_f_drying_daikon_shrivelled.p3d";
	};
	// jp_f_chochin (wall)
	class StaticObj_JP_F_Chochin_Crest: HouseNoDestruct
	{
		scope=1;
		displayName="Paper lantern with a family crest";
		model="\JP\furniture\wall\jp_f_chochin_crest.p3d";
	};
	class StaticObj_JP_F_Chochin_Crest2: HouseNoDestruct
	{
		scope=1;
		displayName="Paper lantern, three-bar crest";
		model="\JP\furniture\wall\jp_f_chochin_crest2.p3d";
	};
	class StaticObj_JP_F_Chochin_Shop: HouseNoDestruct
	{
		scope=1;
		displayName="Paper lantern, shop name Iseya";
		model="\JP\furniture\wall\jp_f_chochin_shop.p3d";
	};
	class StaticObj_JP_F_Chochin_Shop2: HouseNoDestruct
	{
		scope=1;
		displayName="Paper lantern, shop name Yamatoya";
		model="\JP\furniture\wall\jp_f_chochin_shop2.p3d";
	};
	class StaticObj_JP_F_Chochin_Torn: HouseNoDestruct
	{
		scope=1;
		displayName="Paper lantern, torn, hanging askew";
		model="\JP\furniture\wall\jp_f_chochin_torn.p3d";
	};
	class StaticObj_JP_F_Chochin_Fallen: HouseNoDestruct
	{
		scope=1;
		displayName="Paper lantern fallen and crushed";
		model="\JP\furniture\wall\jp_f_chochin_fallen.p3d";
	};
	// jp_f_bangasa (wall)
	class StaticObj_JP_F_Bangasa_Hung: HouseNoDestruct
	{
		scope=1;
		displayName="Oiled-paper umbrella hung on a peg";
		model="\JP\furniture\wall\jp_f_bangasa_hung.p3d";
	};
	class StaticObj_JP_F_Bangasa_Leaning: HouseNoDestruct
	{
		scope=1;
		displayName="Oiled-paper umbrella leaning on the wall";
		model="\JP\furniture\wall\jp_f_bangasa_leaning.p3d";
	};
	class StaticObj_JP_F_Bangasa_Open_Torn: HouseNoDestruct
	{
		scope=1;
		displayName="Umbrella dropped open, paper split";
		model="\JP\furniture\wall\jp_f_bangasa_open_torn.p3d";
	};
	// jp_f_noren_inner (wall)
	class StaticObj_JP_F_Noren_Inner_2: HouseNoDestruct
	{
		scope=1;
		displayName="Inner noren, two panels (0.88)";
		model="\JP\furniture\wall\jp_f_noren_inner_2.p3d";
	};
	class StaticObj_JP_F_Noren_Inner_3: HouseNoDestruct
	{
		scope=1;
		displayName="Inner noren, three panels (1.32)";
		model="\JP\furniture\wall\jp_f_noren_inner_3.p3d";
	};
	class StaticObj_JP_F_Noren_Inner_Torn: HouseNoDestruct
	{
		scope=1;
		displayName="Inner noren, a panel torn off";
		model="\JP\furniture\wall\jp_f_noren_inner_torn.p3d";
	};
	// jp_f_kaya (wall)
	class StaticObj_JP_F_Kaya_Draped: HouseNoDestruct
	{
		scope=1;
		displayName="Mosquito net folded over a pole";
		model="\JP\furniture\wall\jp_f_kaya_draped.p3d";
	};
	class StaticObj_JP_F_Kaya_Bundle: HouseNoDestruct
	{
		scope=1;
		displayName="Mosquito net tied in a bundle on a hook";
		model="\JP\furniture\wall\jp_f_kaya_bundle.p3d";
	};
	class StaticObj_JP_F_Kaya_Loose: HouseNoDestruct
	{
		scope=1;
		displayName="Mosquito net come loose, hanging in a swag";
		model="\JP\furniture\wall\jp_f_kaya_loose.p3d";
	};
	// jp_f_fire_gear (wall)
	class StaticObj_JP_F_Fire_Gear: HouseNoDestruct
	{
		scope=1;
		displayName="Fire buckets on a shelf, fire hook on pegs";
		model="\JP\furniture\wall\jp_f_fire_gear.p3d";
	};
	class StaticObj_JP_F_Fire_Gear_Buckets: HouseNoDestruct
	{
		scope=1;
		displayName="Two fire buckets hung on pegs";
		model="\JP\furniture\wall\jp_f_fire_gear_buckets.p3d";
	};
	class StaticObj_JP_F_Fire_Gear_Fallen: HouseNoDestruct
	{
		scope=1;
		displayName="Fire gear, a bucket on the floor, the hook askew";
		model="\JP\furniture\wall\jp_f_fire_gear_fallen.p3d";
	};
	// jp_f_butsudan (religious)
	class StaticObj_JP_F_Butsudan_Lacquer: HouseNoDestruct
	{
		scope=1;
		displayName="Buddhist cabinet (butsudan), lacquered, doors shut";
		model="\JP\furniture\religious\jp_f_butsudan_lacquer.p3d";
	};
	class StaticObj_JP_F_Butsudan_Plain: HouseNoDestruct
	{
		scope=1;
		displayName="Buddhist cabinet, plain wood";
		model="\JP\furniture\religious\jp_f_butsudan_plain.p3d";
	};
	class StaticObj_JP_F_Butsudan_Shelf: HouseNoDestruct
	{
		scope=1;
		displayName="Buddhist shelf with a small shrine box";
		model="\JP\furniture\religious\jp_f_butsudan_shelf.p3d";
	};
	class StaticObj_JP_F_Butsudan_Lacquer_Dusty: HouseNoDestruct
	{
		scope=1;
		displayName="Buddhist cabinet, undisturbed, dusty";
		model="\JP\furniture\religious\jp_f_butsudan_lacquer_dusty.p3d";
	};
	class StaticObj_JP_F_Butsudan_Plain_Dusty: HouseNoDestruct
	{
		scope=1;
		displayName="Buddhist cabinet, plain, dusty";
		model="\JP\furniture\religious\jp_f_butsudan_plain_dusty.p3d";
	};
	class StaticObj_JP_F_Butsudan_Shelf_Dusty: HouseNoDestruct
	{
		scope=1;
		displayName="Buddhist shelf, undisturbed, dusty";
		model="\JP\furniture\religious\jp_f_butsudan_shelf_dusty.p3d";
	};
	// jp_f_butsu_set (religious)
	class StaticObj_JP_F_Butsu_Set_Full: HouseNoDestruct
	{
		scope=1;
		displayName="Butsudan set: tablets, incense burner, candle, vase, bell";
		model="\JP\furniture\religious\jp_f_butsu_set_full.p3d";
	};
	class StaticObj_JP_F_Butsu_Set_Simple: HouseNoDestruct
	{
		scope=1;
		displayName="Butsudan set: a tablet, burner and vase";
		model="\JP\furniture\religious\jp_f_butsu_set_simple.p3d";
	};
	class StaticObj_JP_F_Butsu_Set_Full_Dusty: HouseNoDestruct
	{
		scope=1;
		displayName="Butsudan set, flowers dried, candle burnt down";
		model="\JP\furniture\religious\jp_f_butsu_set_full_dusty.p3d";
	};
	class StaticObj_JP_F_Butsu_Set_Simple_Dusty: HouseNoDestruct
	{
		scope=1;
		displayName="Butsudan set, simple, dusty";
		model="\JP\furniture\religious\jp_f_butsu_set_simple_dusty.p3d";
	};
	// jp_f_kamidana_set (religious)
	class StaticObj_JP_F_Kamidana_Set_Offerings: HouseNoDestruct
	{
		scope=1;
		displayName="God-shelf offerings: sanbo, flasks, sakaki";
		model="\JP\furniture\religious\jp_f_kamidana_set_offerings.p3d";
	};
	class StaticObj_JP_F_Kamidana_Set_Shimenawa: HouseNoDestruct
	{
		scope=1;
		displayName="Sacred rope with paper streamers for a god shelf";
		model="\JP\furniture\religious\jp_f_kamidana_set_shimenawa.p3d";
	};
	class StaticObj_JP_F_Kamidana_Set_Offerings_Dry: HouseNoDestruct
	{
		scope=1;
		displayName="God-shelf offerings, sakaki dried, dishes empty";
		model="\JP\furniture\religious\jp_f_kamidana_set_offerings_dry.p3d";
	};
	class StaticObj_JP_F_Kamidana_Set_Shimenawa_Old: HouseNoDestruct
	{
		scope=1;
		displayName="Sacred rope, faded, a streamer gone";
		model="\JP\furniture\religious\jp_f_kamidana_set_shimenawa_old.p3d";
	};
	// jp_f_tableware (meal)
	class StaticObj_JP_F_Tableware_Hakozen_Stack: HouseNoDestruct
	{
		scope=1;
		displayName="Box trays (hakozen), three stacked, lacquer";
		model="\JP\furniture\meal\jp_f_tableware_hakozen_stack.p3d";
	};
	class StaticObj_JP_F_Tableware_Hakozen_Plain: HouseNoDestruct
	{
		scope=1;
		displayName="Box trays, plain wood, two stacked";
		model="\JP\furniture\meal\jp_f_tableware_hakozen_plain.p3d";
	};
	class StaticObj_JP_F_Tableware_Zen: HouseNoDestruct
	{
		scope=1;
		displayName="Legged tray (zen) with lidded bowls";
		model="\JP\furniture\meal\jp_f_tableware_zen.p3d";
	};
	class StaticObj_JP_F_Tableware_Bowls: HouseNoDestruct
	{
		scope=1;
		displayName="A stack of bowls and dishes";
		model="\JP\furniture\meal\jp_f_tableware_bowls.p3d";
	};
	class StaticObj_JP_F_Tableware_Scattered: HouseNoDestruct
	{
		scope=1;
		displayName="Tableware knocked over, bowls upturned";
		model="\JP\furniture\meal\jp_f_tableware_scattered.p3d";
	};
	// jp_f_meal_left (meal)
	class StaticObj_JP_F_Meal_Left_Zen: HouseNoDestruct
	{
		scope=1;
		displayName="A meal left on its tray, a cup knocked over";
		model="\JP\furniture\meal\jp_f_meal_left_zen.p3d";
	};
	class StaticObj_JP_F_Meal_Left_Two: HouseNoDestruct
	{
		scope=1;
		displayName="Two meals left, one tray pushed back, the flask down";
		model="\JP\furniture\meal\jp_f_meal_left_two.p3d";
	};
	class StaticObj_JP_F_Meal_Left_Hakozen: HouseNoDestruct
	{
		scope=1;
		displayName="A poor meal on a box-tray lid";
		model="\JP\furniture\meal\jp_f_meal_left_hakozen.p3d";
	};
	// jp_f_tokkuri (meal)
	class StaticObj_JP_F_Tokkuri_Pair: HouseNoDestruct
	{
		scope=1;
		displayName="Two sake flasks and cups on a tray";
		model="\JP\furniture\meal\jp_f_tokkuri_pair.p3d";
	};
	class StaticObj_JP_F_Tokkuri_Large: HouseNoDestruct
	{
		scope=1;
		displayName="A large sake flask and a cup";
		model="\JP\furniture\meal\jp_f_tokkuri_large.p3d";
	};
	class StaticObj_JP_F_Tokkuri_Tipped: HouseNoDestruct
	{
		scope=1;
		displayName="Sake flask on its side, a cup rolled off";
		model="\JP\furniture\meal\jp_f_tokkuri_tipped.p3d";
	};
	// jp_f_suribachi (meal)
	class StaticObj_JP_F_Suribachi_Bowl: HouseNoDestruct
	{
		scope=1;
		displayName="Grinding bowl (suribachi) and pestle";
		model="\JP\furniture\meal\jp_f_suribachi_bowl.p3d";
	};
	class StaticObj_JP_F_Suribachi_Board: HouseNoDestruct
	{
		scope=1;
		displayName="Cutting board with a knife and a radish";
		model="\JP\furniture\meal\jp_f_suribachi_board.p3d";
	};
	class StaticObj_JP_F_Suribachi_Spilled: HouseNoDestruct
	{
		scope=1;
		displayName="Grinding bowl tipped, pestle rolled, board askew";
		model="\JP\furniture\meal\jp_f_suribachi_spilled.p3d";
	};
	// jp_f_seiro (meal)
	class StaticObj_JP_F_Seiro_Kama2: HouseNoDestruct
	{
		scope=1;
		displayName="Steamer, two tiers, on the rice pot";
		model="\JP\furniture\meal\jp_f_seiro_kama2.p3d";
	};
	class StaticObj_JP_F_Seiro_Kama3: HouseNoDestruct
	{
		scope=1;
		displayName="Steamer, three tiers, on the rice pot";
		model="\JP\furniture\meal\jp_f_seiro_kama3.p3d";
	};
	class StaticObj_JP_F_Seiro_Stack: HouseNoDestruct
	{
		scope=1;
		displayName="Steamer tiers stacked";
		model="\JP\furniture\meal\jp_f_seiro_stack.p3d";
	};
	class StaticObj_JP_F_Seiro_Toppled: HouseNoDestruct
	{
		scope=1;
		displayName="Steamer on the pot, lid and a tier fallen";
		model="\JP\furniture\meal\jp_f_seiro_toppled.p3d";
	};
	// jp_f_taru (meal)
	class StaticObj_JP_F_Taru_Cask: HouseNoDestruct
	{
		scope=1;
		displayName="Coopered cask (taru)";
		model="\JP\furniture\meal\jp_f_taru_cask.p3d";
	};
	class StaticObj_JP_F_Taru_Komo: HouseNoDestruct
	{
		scope=1;
		displayName="Straw-wrapped sake cask, marked";
		model="\JP\furniture\meal\jp_f_taru_komo.p3d";
	};
	class StaticObj_JP_F_Taru_Rack3: HouseNoDestruct
	{
		scope=1;
		displayName="Three casks on a low rack";
		model="\JP\furniture\meal\jp_f_taru_rack3.p3d";
	};
	class StaticObj_JP_F_Taru_Staved: HouseNoDestruct
	{
		scope=1;
		displayName="Cask staved in, dry";
		model="\JP\furniture\meal\jp_f_taru_staved.p3d";
	};
	class StaticObj_JP_F_Taru_Rack3_Ab: HouseNoDestruct
	{
		scope=1;
		displayName="Cask rack, one cask gone, one rolled off";
		model="\JP\furniture\meal\jp_f_taru_rack3_ab.p3d";
	};
	// jp_f_basket (meal)
	class StaticObj_JP_F_Basket_Zaru: HouseNoDestruct
	{
		scope=1;
		displayName="Flat sieve basket (zaru)";
		model="\JP\furniture\meal\jp_f_basket_zaru.p3d";
	};
	class StaticObj_JP_F_Basket_Zaru_Stack: HouseNoDestruct
	{
		scope=1;
		displayName="Three sieve baskets stacked";
		model="\JP\furniture\meal\jp_f_basket_zaru_stack.p3d";
	};
	class StaticObj_JP_F_Basket_Zaru_Wall: HouseNoDestruct
	{
		scope=1;
		displayName="Sieve basket hung on a wall peg";
		model="\JP\furniture\meal\jp_f_basket_zaru_wall.p3d";
	};
	class StaticObj_JP_F_Basket_Kago: HouseNoDestruct
	{
		scope=1;
		displayName="Tall basket (kago)";
		model="\JP\furniture\meal\jp_f_basket_kago.p3d";
	};
	class StaticObj_JP_F_Basket_Back: HouseNoDestruct
	{
		scope=1;
		displayName="Back basket (seoi-kago) with straps";
		model="\JP\furniture\meal\jp_f_basket_back.p3d";
	};
	class StaticObj_JP_F_Basket_Kago_Tipped: HouseNoDestruct
	{
		scope=1;
		displayName="Tall basket on its side, leaves spilled";
		model="\JP\furniture\meal\jp_f_basket_kago_tipped.p3d";
	};
	class StaticObj_JP_F_Basket_Back_Crushed: HouseNoDestruct
	{
		scope=1;
		displayName="Back basket on its side";
		model="\JP\furniture\meal\jp_f_basket_back_crushed.p3d";
	};
	// jp_f_charcoal (meal)
	class StaticObj_JP_F_Charcoal_Bale: HouseNoDestruct
	{
		scope=1;
		displayName="Charcoal bale (sumi-dawara), open";
		model="\JP\furniture\meal\jp_f_charcoal_bale.p3d";
	};
	class StaticObj_JP_F_Charcoal_Bales3: HouseNoDestruct
	{
		scope=1;
		displayName="Three charcoal bales";
		model="\JP\furniture\meal\jp_f_charcoal_bales3.p3d";
	};
	class StaticObj_JP_F_Charcoal_Scuttle: HouseNoDestruct
	{
		scope=1;
		displayName="Charcoal scuttle with tongs";
		model="\JP\furniture\meal\jp_f_charcoal_scuttle.p3d";
	};
	class StaticObj_JP_F_Charcoal_Burst: HouseNoDestruct
	{
		scope=1;
		displayName="Charcoal bale burst, charcoal spilled";
		model="\JP\furniture\meal\jp_f_charcoal_burst.p3d";
	};
	// jp_f_hiuchi (meal)
	class StaticObj_JP_F_Hiuchi_Box: HouseNoDestruct
	{
		scope=1;
		displayName="Fire-striker box, the steel on the lid";
		model="\JP\furniture\meal\jp_f_hiuchi_box.p3d";
	};
	class StaticObj_JP_F_Hiuchi_Open: HouseNoDestruct
	{
		scope=1;
		displayName="Fire-striker kit laid out";
		model="\JP\furniture\meal\jp_f_hiuchi_open.p3d";
	};
	class StaticObj_JP_F_Hiuchi_Spilled: HouseNoDestruct
	{
		scope=1;
		displayName="Fire-striker box tipped, tinder spilled";
		model="\JP\furniture\meal\jp_f_hiuchi_spilled.p3d";
	};
	// jp_f_enza (living)
	class StaticObj_JP_F_Enza: HouseNoDestruct
	{
		scope=1;
		displayName="Round straw cushion (enza)";
		model="\JP\furniture\living\jp_f_enza.p3d";
	};
	class StaticObj_JP_F_Enza_Stack3: HouseNoDestruct
	{
		scope=1;
		displayName="Three straw cushions stacked";
		model="\JP\furniture\living\jp_f_enza_stack3.p3d";
	};
	class StaticObj_JP_F_Enza_Zabuton: HouseNoDestruct
	{
		scope=1;
		displayName="Cotton cushion (zabuton), T3";
		model="\JP\furniture\living\jp_f_enza_zabuton.p3d";
	};
	class StaticObj_JP_F_Enza_Zabuton_Stack3: HouseNoDestruct
	{
		scope=1;
		displayName="Three zabuton stacked, T3";
		model="\JP\furniture\living\jp_f_enza_zabuton_stack3.p3d";
	};
	class StaticObj_JP_F_Enza_Kicked: HouseNoDestruct
	{
		scope=1;
		displayName="Straw cushion kicked against the wall";
		model="\JP\furniture\living\jp_f_enza_kicked.p3d";
	};
	class StaticObj_JP_F_Enza_Zabuton_Folded: HouseNoDestruct
	{
		scope=1;
		displayName="Zabuton folded over, askew, T3";
		model="\JP\furniture\living\jp_f_enza_zabuton_folded.p3d";
	};
	// jp_f_byobu (living)
	class StaticObj_JP_F_Byobu_Makura: HouseNoDestruct
	{
		scope=1;
		displayName="Low bedding screen, two leaves";
		model="\JP\furniture\living\jp_f_byobu_makura.p3d";
	};
	class StaticObj_JP_F_Byobu_Tsuitate: HouseNoDestruct
	{
		scope=1;
		displayName="Entrance screen on two feet";
		model="\JP\furniture\living\jp_f_byobu_tsuitate.p3d";
	};
	class StaticObj_JP_F_Byobu_Makura_Fallen: HouseNoDestruct
	{
		scope=1;
		displayName="Bedding screen knocked flat, torn";
		model="\JP\furniture\living\jp_f_byobu_makura_fallen.p3d";
	};
	class StaticObj_JP_F_Byobu_Tsuitate_Fallen: HouseNoDestruct
	{
		scope=1;
		displayName="Entrance screen fallen, torn";
		model="\JP\furniture\living\jp_f_byobu_tsuitate_fallen.p3d";
	};
	// jp_f_iko (living)
	class StaticObj_JP_F_Iko_Robe: HouseNoDestruct
	{
		scope=1;
		displayName="Clothes rack, lacquered, a robe spread over it";
		model="\JP\furniture\living\jp_f_iko_robe.p3d";
	};
	class StaticObj_JP_F_Iko_Plain: HouseNoDestruct
	{
		scope=1;
		displayName="Clothes rack, plain, an under-robe hung";
		model="\JP\furniture\living\jp_f_iko_plain.p3d";
	};
	class StaticObj_JP_F_Iko_Empty: HouseNoDestruct
	{
		scope=1;
		displayName="Clothes rack, plain, a sash end over the rail";
		model="\JP\furniture\living\jp_f_iko_empty.p3d";
	};
	class StaticObj_JP_F_Iko_Fallen: HouseNoDestruct
	{
		scope=1;
		displayName="Clothes rack fallen, the robe on the mat";
		model="\JP\furniture\living\jp_f_iko_fallen.p3d";
	};
	// jp_f_clothes (living)
	class StaticObj_JP_F_Clothes_Kimono: HouseNoDestruct
	{
		scope=1;
		displayName="A kimono dropped on the mat";
		model="\JP\furniture\living\jp_f_clothes_kimono.p3d";
	};
	class StaticObj_JP_F_Clothes_Kimono_Obi: HouseNoDestruct
	{
		scope=1;
		displayName="An under-kimono and a sash on the mat";
		model="\JP\furniture\living\jp_f_clothes_kimono_obi.p3d";
	};
	class StaticObj_JP_F_Clothes_Haori: HouseNoDestruct
	{
		scope=1;
		displayName="A short jacket and a sash on the mat";
		model="\JP\furniture\living\jp_f_clothes_haori.p3d";
	};
	// jp_f_sewing (living)
	class StaticObj_JP_F_Sewing_Box: HouseNoDestruct
	{
		scope=1;
		displayName="Sewing box (haribako) with a pincushion";
		model="\JP\furniture\living\jp_f_sewing_box.p3d";
	};
	class StaticObj_JP_F_Sewing_Work: HouseNoDestruct
	{
		scope=1;
		displayName="Sewing box and a half-sewn garment";
		model="\JP\furniture\living\jp_f_sewing_work.p3d";
	};
	class StaticObj_JP_F_Sewing_Spilled: HouseNoDestruct
	{
		scope=1;
		displayName="Sewing box, drawer out, spools rolled";
		model="\JP\furniture\living\jp_f_sewing_spilled.p3d";
	};
	// jp_f_mirror_stand (living)
	class StaticObj_JP_F_Mirror_Stand: HouseNoDestruct
	{
		scope=1;
		displayName="Mirror stand, the mirror under its cloth";
		model="\JP\furniture\living\jp_f_mirror_stand.p3d";
	};
	class StaticObj_JP_F_Mirror_Stand_Open: HouseNoDestruct
	{
		scope=1;
		displayName="Mirror stand, the bronze mirror uncovered";
		model="\JP\furniture\living\jp_f_mirror_stand_open.p3d";
	};
	class StaticObj_JP_F_Mirror_Stand_Tipped: HouseNoDestruct
	{
		scope=1;
		displayName="Mirror stand knocked over, the mirror on the mat";
		model="\JP\furniture\living\jp_f_mirror_stand_tipped.p3d";
	};
	// jp_f_goban (living)
	class StaticObj_JP_F_Goban_Go: HouseNoDestruct
	{
		scope=1;
		displayName="Go board with stones and bowls";
		model="\JP\furniture\living\jp_f_goban_go.p3d";
	};
	class StaticObj_JP_F_Goban_Shogi: HouseNoDestruct
	{
		scope=1;
		displayName="Shogi board with pieces";
		model="\JP\furniture\living\jp_f_goban_shogi.p3d";
	};
	class StaticObj_JP_F_Goban_Go_Scattered: HouseNoDestruct
	{
		scope=1;
		displayName="Go board, a bowl tipped, stones strewn";
		model="\JP\furniture\living\jp_f_goban_go_scattered.p3d";
	};
	class StaticObj_JP_F_Goban_Shogi_Scattered: HouseNoDestruct
	{
		scope=1;
		displayName="Shogi board, pieces strewn";
		model="\JP\furniture\living\jp_f_goban_shogi_scattered.p3d";
	};
	// jp_f_toys (living)
	class StaticObj_JP_F_Toys_Koma: HouseNoDestruct
	{
		scope=1;
		displayName="A spinning top and its string";
		model="\JP\furniture\living\jp_f_toys_koma.p3d";
	};
	class StaticObj_JP_F_Toys_Hagoita: HouseNoDestruct
	{
		scope=1;
		displayName="A battledore and shuttlecock";
		model="\JP\furniture\living\jp_f_toys_hagoita.p3d";
	};
	class StaticObj_JP_F_Toys_Doll: HouseNoDestruct
	{
		scope=1;
		displayName="A small cloth doll";
		model="\JP\furniture\living\jp_f_toys_doll.p3d";
	};
	class StaticObj_JP_F_Toys_Scattered: HouseNoDestruct
	{
		scope=1;
		displayName="Toys left on the floor together";
		model="\JP\furniture\living\jp_f_toys_scattered.p3d";
	};
	// jp_f_shokudai (living)
	class StaticObj_JP_F_Shokudai_Tall: HouseNoDestruct
	{
		scope=1;
		displayName="Tall lacquered candle stand, unlit";
		model="\JP\furniture\living\jp_f_shokudai_tall.p3d";
	};
	class StaticObj_JP_F_Shokudai_Short: HouseNoDestruct
	{
		scope=1;
		displayName="Short iron candle stand";
		model="\JP\furniture\living\jp_f_shokudai_short.p3d";
	};
	class StaticObj_JP_F_Shokudai_Tipped: HouseNoDestruct
	{
		scope=1;
		displayName="Candle stand knocked over, the candle broken";
		model="\JP\furniture\living\jp_f_shokudai_tipped.p3d";
	};
	// jp_f_straw_bed (living)
	class StaticObj_JP_F_Straw_Bed_Pile: HouseNoDestruct
	{
		scope=1;
		displayName="Straw bedding under a straw mat";
		model="\JP\furniture\living\jp_f_straw_bed_pile.p3d";
	};
	class StaticObj_JP_F_Straw_Bed_Quilt: HouseNoDestruct
	{
		scope=1;
		displayName="Straw bedding, a paper quilt thrown back";
		model="\JP\furniture\living\jp_f_straw_bed_quilt.p3d";
	};
	class StaticObj_JP_F_Straw_Bed_Scattered: HouseNoDestruct
	{
		scope=1;
		displayName="Straw bedding scattered and flattened";
		model="\JP\furniture\living\jp_f_straw_bed_scattered.p3d";
	};
	// jp_f_itoguruma (work)
	class StaticObj_JP_F_Itoguruma: HouseNoDestruct
	{
		scope=1;
		displayName="Spinning wheel (itoguruma)";
		model="\JP\furniture\work\jp_f_itoguruma.p3d";
	};
	class StaticObj_JP_F_Itoguruma_Thread: HouseNoDestruct
	{
		scope=1;
		displayName="Spinning wheel with thread and a basket of cotton";
		model="\JP\furniture\work\jp_f_itoguruma_thread.p3d";
	};
	class StaticObj_JP_F_Itoguruma_Broken: HouseNoDestruct
	{
		scope=1;
		displayName="Spinning wheel, the wheel knocked off and broken";
		model="\JP\furniture\work\jp_f_itoguruma_broken.p3d";
	};
	// jp_f_izaribata (work)
	class StaticObj_JP_F_Izaribata: HouseNoDestruct
	{
		scope=1;
		displayName="Ground loom (izari-bata) with cloth on it";
		model="\JP\furniture\work\jp_f_izaribata.p3d";
	};
	class StaticObj_JP_F_Izaribata_Bare: HouseNoDestruct
	{
		scope=1;
		displayName="Ground loom, warped, no cloth yet";
		model="\JP\furniture\work\jp_f_izaribata_bare.p3d";
	};
	class StaticObj_JP_F_Izaribata_Cut: HouseNoDestruct
	{
		scope=1;
		displayName="Ground loom, the warp cut, cloth across the floor";
		model="\JP\furniture\work\jp_f_izaribata_cut.p3d";
	};
	// jp_f_straw_work (work)
	class StaticObj_JP_F_Straw_Work_Sandal: HouseNoDestruct
	{
		scope=1;
		displayName="Straw work: a half-made sandal on a stool, a bundle";
		model="\JP\furniture\work\jp_f_straw_work_sandal.p3d";
	};
	class StaticObj_JP_F_Straw_Work_Beating: HouseNoDestruct
	{
		scope=1;
		displayName="Straw-beating stone and mallet, a bundle";
		model="\JP\furniture\work\jp_f_straw_work_beating.p3d";
	};
	class StaticObj_JP_F_Straw_Work_Scattered: HouseNoDestruct
	{
		scope=1;
		displayName="Straw work scattered, the stool tipped";
		model="\JP\furniture\work\jp_f_straw_work_scattered.p3d";
	};
	// jp_f_mi (work)
	class StaticObj_JP_F_Mi: HouseNoDestruct
	{
		scope=1;
		displayName="Winnowing basket (mi)";
		model="\JP\furniture\work\jp_f_mi.p3d";
	};
	class StaticObj_JP_F_Mi_Wall: HouseNoDestruct
	{
		scope=1;
		displayName="Winnowing basket hung on a wall peg";
		model="\JP\furniture\work\jp_f_mi_wall.p3d";
	};
	class StaticObj_JP_F_Mi_Furui: HouseNoDestruct
	{
		scope=1;
		displayName="Rice sieve (furui)";
		model="\JP\furniture\work\jp_f_mi_furui.p3d";
	};
	class StaticObj_JP_F_Mi_Spilled: HouseNoDestruct
	{
		scope=1;
		displayName="Winnowing basket tipped, grain spilled";
		model="\JP\furniture\work\jp_f_mi_spilled.p3d";
	};
	// jp_f_usu (work)
	class StaticObj_JP_F_Usu: HouseNoDestruct
	{
		scope=1;
		displayName="Rice mortar (usu) with a pounder";
		model="\JP\furniture\work\jp_f_usu.p3d";
	};
	class StaticObj_JP_F_Usu_Mallet: HouseNoDestruct
	{
		scope=1;
		displayName="Rice mortar with a mallet pounder";
		model="\JP\furniture\work\jp_f_usu_mallet.p3d";
	};
	class StaticObj_JP_F_Usu_Ishiusu: HouseNoDestruct
	{
		scope=1;
		displayName="Stone hand mill on a straw mat";
		model="\JP\furniture\work\jp_f_usu_ishiusu.p3d";
	};
	class StaticObj_JP_F_Usu_Fallen: HouseNoDestruct
	{
		scope=1;
		displayName="Rice mortar, the pounder fallen, dust in the bowl";
		model="\JP\furniture\work\jp_f_usu_fallen.p3d";
	};
	class StaticObj_JP_F_Usu_Ishiusu_Off: HouseNoDestruct
	{
		scope=1;
		displayName="Stone hand mill, the top stone off";
		model="\JP\furniture\work\jp_f_usu_ishiusu_off.p3d";
	};
	// jp_f_writing_box (work)
	class StaticObj_JP_F_Writing_Box: HouseNoDestruct
	{
		scope=1;
		displayName="Writing box and a paper stack";
		model="\JP\furniture\work\jp_f_writing_box.p3d";
	};
	class StaticObj_JP_F_Writing_Box_Open: HouseNoDestruct
	{
		scope=1;
		displayName="Writing box open: inkstone, brushes, paper";
		model="\JP\furniture\work\jp_f_writing_box_open.p3d";
	};
	class StaticObj_JP_F_Writing_Box_Spilled: HouseNoDestruct
	{
		scope=1;
		displayName="Writing box knocked, papers slid, ink spilled";
		model="\JP\furniture\work\jp_f_writing_box_spilled.p3d";
	};
	// jp_f_choba_set (work)
	class StaticObj_JP_F_Choba_Set_Desk: HouseNoDestruct
	{
		scope=1;
		displayName="Ledgers, abacus and writing box for the desk";
		model="\JP\furniture\work\jp_f_choba_set_desk.p3d";
	};
	class StaticObj_JP_F_Choba_Set_Zenibako: HouseNoDestruct
	{
		scope=1;
		displayName="Coin box (zenibako), locked";
		model="\JP\furniture\work\jp_f_choba_set_zenibako.p3d";
	};
	class StaticObj_JP_F_Choba_Set_Tenbin: HouseNoDestruct
	{
		scope=1;
		displayName="Money balance on its box";
		model="\JP\furniture\work\jp_f_choba_set_tenbin.p3d";
	};
	class StaticObj_JP_F_Choba_Set_Scattered: HouseNoDestruct
	{
		scope=1;
		displayName="Ledgers splayed, abacus upturned, papers";
		model="\JP\furniture\work\jp_f_choba_set_scattered.p3d";
	};
	class StaticObj_JP_F_Choba_Set_Zenibako_Open: HouseNoDestruct
	{
		scope=1;
		displayName="Coin box forced open, empty";
		model="\JP\furniture\work\jp_f_choba_set_zenibako_open.p3d";
	};
	// jp_f_masu (work)
	class StaticObj_JP_F_Masu_Set: HouseNoDestruct
	{
		scope=1;
		displayName="Measures (masu), three sizes, and the strickle";
		model="\JP\furniture\work\jp_f_masu_set.p3d";
	};
	class StaticObj_JP_F_Masu_To: HouseNoDestruct
	{
		scope=1;
		displayName="A one-to measure heaped with rice, the strickle across";
		model="\JP\furniture\work\jp_f_masu_to.p3d";
	};
	class StaticObj_JP_F_Masu_Spilled: HouseNoDestruct
	{
		scope=1;
		displayName="Measure tipped, the rice spilled";
		model="\JP\furniture\work\jp_f_masu_spilled.p3d";
	};
};
