// JP_Furniture - interior props (jp_f_*), placed as proxies inside JP buildings like vanilla
// \dz\structures\furniture, plus a StaticObj_JP_F_<name> class each (HouseNoDestruct, scope 1) as vanilla
// StaticObj_Furniture_<name>. No script, no vanilla change, no map dependency.
// GENERATED by japan_dev/spikes/B3a/build.py - edit the generator, not this file.
class CfgPatches
{
	class JP_Furniture
	{
		units[]={};
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"DZ_Data",
			"JP_Common"
		};
	};
};
class CfgVehicles
{
	class HouseNoDestruct;
	// jp_f_kama (kitchen)
	class StaticObj_JP_F_Kama: HouseNoDestruct
	{
		scope=1;
		displayName="Rice pot (kama) with lid";
		model="\JP\furniture\kitchen\jp_f_kama.p3d";
	};
	class StaticObj_JP_F_Kama_Nolid: HouseNoDestruct
	{
		scope=1;
		displayName="Rice pot, lid off, rusted";
		model="\JP\furniture\kitchen\jp_f_kama_nolid.p3d";
	};
	class StaticObj_JP_F_Kama_Nabe: HouseNoDestruct
	{
		scope=1;
		displayName="Small pot (nabe) with bail";
		model="\JP\furniture\kitchen\jp_f_kama_nabe.p3d";
	};
	class StaticObj_JP_F_Kama_Nabe_Rusted: HouseNoDestruct
	{
		scope=1;
		displayName="Small pot, rusted, burnt crust";
		model="\JP\furniture\kitchen\jp_f_kama_nabe_rusted.p3d";
	};
	// jp_f_jizai_kagi (kitchen)
	class StaticObj_JP_F_Jizai_Kagi: HouseNoDestruct
	{
		scope=1;
		displayName="Pot hook (jizai-kagi) with fish lever";
		model="\JP\furniture\kitchen\jp_f_jizai_kagi.p3d";
	};
	class StaticObj_JP_F_Jizai_Kagi_Abandoned: HouseNoDestruct
	{
		scope=1;
		displayName="Pot hook, lever jammed high, rusted pot";
		model="\JP\furniture\kitchen\jp_f_jizai_kagi_abandoned.p3d";
	};
	class StaticObj_JP_F_Jizai_Kagi_Plain: HouseNoDestruct
	{
		scope=1;
		displayName="Pot hook, plain bar lever";
		model="\JP\furniture\kitchen\jp_f_jizai_kagi_plain.p3d";
	};
	class StaticObj_JP_F_Jizai_Kagi_Plain_Abandoned: HouseNoDestruct
	{
		scope=1;
		displayName="Pot hook (plain), jammed, rusted pot";
		model="\JP\furniture\kitchen\jp_f_jizai_kagi_plain_abandoned.p3d";
	};
	// jp_f_mizugame (kitchen)
	class StaticObj_JP_F_Mizugame: HouseNoDestruct
	{
		scope=1;
		displayName="Water jar (mizugame), lid and dipper";
		model="\JP\furniture\kitchen\jp_f_mizugame.p3d";
	};
	class StaticObj_JP_F_Mizugame_Open: HouseNoDestruct
	{
		scope=1;
		displayName="Water jar, lid off leaning, dry";
		model="\JP\furniture\kitchen\jp_f_mizugame_open.p3d";
	};
	class StaticObj_JP_F_Mizugame_Broken: HouseNoDestruct
	{
		scope=1;
		displayName="Water jar, cracked, piece on the floor";
		model="\JP\furniture\kitchen\jp_f_mizugame_broken.p3d";
	};
	// jp_f_oke (kitchen)
	class StaticObj_JP_F_Oke_Bucket: HouseNoDestruct
	{
		scope=1;
		displayName="Handled bucket (oke)";
		model="\JP\furniture\kitchen\jp_f_oke_bucket.p3d";
	};
	class StaticObj_JP_F_Oke_Tipped: HouseNoDestruct
	{
		scope=1;
		displayName="Bucket on its side";
		model="\JP\furniture\kitchen\jp_f_oke_tipped.p3d";
	};
	class StaticObj_JP_F_Oke_Tarai: HouseNoDestruct
	{
		scope=1;
		displayName="Shallow washing tub (tarai)";
		model="\JP\furniture\kitchen\jp_f_oke_tarai.p3d";
	};
	class StaticObj_JP_F_Oke_Tarai_Dry: HouseNoDestruct
	{
		scope=1;
		displayName="Tarai, dried out, stave and hoop off";
		model="\JP\furniture\kitchen\jp_f_oke_tarai_dry.p3d";
	};
	class StaticObj_JP_F_Oke_Pickle: HouseNoDestruct
	{
		scope=1;
		displayName="Pickle tub with lid and stone";
		model="\JP\furniture\kitchen\jp_f_oke_pickle.p3d";
	};
	class StaticObj_JP_F_Oke_Pickle_Open: HouseNoDestruct
	{
		scope=1;
		displayName="Pickle tub, lid off, stone on the floor";
		model="\JP\furniture\kitchen\jp_f_oke_pickle_open.p3d";
	};
	// jp_f_tana (kitchen)
	class StaticObj_JP_F_Tana_091_1: HouseNoDestruct
	{
		scope=1;
		displayName="Wall shelf 0.91 m, 1 board";
		model="\JP\furniture\kitchen\jp_f_tana_091_1.p3d";
	};
	class StaticObj_JP_F_Tana_091_1_Sag: HouseNoDestruct
	{
		scope=1;
		displayName="Wall shelf 0.91 m, 1 board, sagging";
		model="\JP\furniture\kitchen\jp_f_tana_091_1_sag.p3d";
	};
	class StaticObj_JP_F_Tana_091_3: HouseNoDestruct
	{
		scope=1;
		displayName="Wall shelf 0.91 m, 3 boards";
		model="\JP\furniture\kitchen\jp_f_tana_091_3.p3d";
	};
	class StaticObj_JP_F_Tana_091_3_Sag: HouseNoDestruct
	{
		scope=1;
		displayName="Wall shelf 0.91 m, 3 boards, sagging";
		model="\JP\furniture\kitchen\jp_f_tana_091_3_sag.p3d";
	};
	class StaticObj_JP_F_Tana_136_1: HouseNoDestruct
	{
		scope=1;
		displayName="Wall shelf 1.36 m, 1 board";
		model="\JP\furniture\kitchen\jp_f_tana_136_1.p3d";
	};
	class StaticObj_JP_F_Tana_136_1_Sag: HouseNoDestruct
	{
		scope=1;
		displayName="Wall shelf 1.36 m, 1 board, sagging";
		model="\JP\furniture\kitchen\jp_f_tana_136_1_sag.p3d";
	};
	class StaticObj_JP_F_Tana_136_3: HouseNoDestruct
	{
		scope=1;
		displayName="Wall shelf 1.36 m, 3 boards";
		model="\JP\furniture\kitchen\jp_f_tana_136_3.p3d";
	};
	class StaticObj_JP_F_Tana_136_3_Sag: HouseNoDestruct
	{
		scope=1;
		displayName="Wall shelf 1.36 m, 3 boards, sagging";
		model="\JP\furniture\kitchen\jp_f_tana_136_3_sag.p3d";
	};
	class StaticObj_JP_F_Tana_182_1: HouseNoDestruct
	{
		scope=1;
		displayName="Wall shelf 1.82 m, 1 board";
		model="\JP\furniture\kitchen\jp_f_tana_182_1.p3d";
	};
	class StaticObj_JP_F_Tana_182_1_Sag: HouseNoDestruct
	{
		scope=1;
		displayName="Wall shelf 1.82 m, 1 board, sagging";
		model="\JP\furniture\kitchen\jp_f_tana_182_1_sag.p3d";
	};
	class StaticObj_JP_F_Tana_182_3: HouseNoDestruct
	{
		scope=1;
		displayName="Wall shelf 1.82 m, 3 boards";
		model="\JP\furniture\kitchen\jp_f_tana_182_3.p3d";
	};
	class StaticObj_JP_F_Tana_182_3_Sag: HouseNoDestruct
	{
		scope=1;
		displayName="Wall shelf 1.82 m, 3 boards, sagging";
		model="\JP\furniture\kitchen\jp_f_tana_182_3_sag.p3d";
	};
	// jp_f_firewood (kitchen)
	class StaticObj_JP_F_Firewood_Stack: HouseNoDestruct
	{
		scope=1;
		displayName="Firewood stack (maki)";
		model="\JP\furniture\kitchen\jp_f_firewood_stack.p3d";
	};
	class StaticObj_JP_F_Firewood_Low: HouseNoDestruct
	{
		scope=1;
		displayName="Firewood stack, half used, logs rolled";
		model="\JP\furniture\kitchen\jp_f_firewood_low.p3d";
	};
	class StaticObj_JP_F_Firewood_Bundle: HouseNoDestruct
	{
		scope=1;
		displayName="Brushwood bundles (soda)";
		model="\JP\furniture\kitchen\jp_f_firewood_bundle.p3d";
	};
	class StaticObj_JP_F_Firewood_Bundle_Loose: HouseNoDestruct
	{
		scope=1;
		displayName="Brushwood bundle burst, sticks scattered";
		model="\JP\furniture\kitchen\jp_f_firewood_bundle_loose.p3d";
	};
	// jp_f_jar (kitchen)
	class StaticObj_JP_F_Jar_S: HouseNoDestruct
	{
		scope=1;
		displayName="Storage jar S";
		model="\JP\furniture\kitchen\jp_f_jar_s.p3d";
	};
	class StaticObj_JP_F_Jar_M: HouseNoDestruct
	{
		scope=1;
		displayName="Storage jar M";
		model="\JP\furniture\kitchen\jp_f_jar_m.p3d";
	};
	class StaticObj_JP_F_Jar_L: HouseNoDestruct
	{
		scope=1;
		displayName="Storage jar L";
		model="\JP\furniture\kitchen\jp_f_jar_l.p3d";
	};
	class StaticObj_JP_F_Jar_S_Pale: HouseNoDestruct
	{
		scope=1;
		displayName="Storage jar S (pale glaze)";
		model="\JP\furniture\kitchen\jp_f_jar_s_pale.p3d";
	};
	class StaticObj_JP_F_Jar_M_Pale: HouseNoDestruct
	{
		scope=1;
		displayName="Storage jar M (pale glaze)";
		model="\JP\furniture\kitchen\jp_f_jar_m_pale.p3d";
	};
	class StaticObj_JP_F_Jar_S_Open: HouseNoDestruct
	{
		scope=1;
		displayName="Storage jar S, lid off";
		model="\JP\furniture\kitchen\jp_f_jar_s_open.p3d";
	};
	class StaticObj_JP_F_Jar_M_Open: HouseNoDestruct
	{
		scope=1;
		displayName="Storage jar M, lid off";
		model="\JP\furniture\kitchen\jp_f_jar_m_open.p3d";
	};
	class StaticObj_JP_F_Jar_L_Open: HouseNoDestruct
	{
		scope=1;
		displayName="Storage jar L, lid off";
		model="\JP\furniture\kitchen\jp_f_jar_l_open.p3d";
	};
	class StaticObj_JP_F_Jar_M_Broken: HouseNoDestruct
	{
		scope=1;
		displayName="Storage jar M, broken";
		model="\JP\furniture\kitchen\jp_f_jar_m_broken.p3d";
	};
	// jp_f_tansu (storage)
	class StaticObj_JP_F_Tansu: HouseNoDestruct
	{
		scope=1;
		displayName="Tansu (clothing chest)";
		model="\JP\furniture\storage\jp_f_tansu.p3d";
	};
	class StaticObj_JP_F_Tansu_Ransacked: HouseNoDestruct
	{
		scope=1;
		displayName="Tansu (ransacked)";
		model="\JP\furniture\storage\jp_f_tansu_ransacked.p3d";
	};
	class StaticObj_JP_F_Tansu_Single: HouseNoDestruct
	{
		scope=1;
		displayName="Tansu, single box";
		model="\JP\furniture\storage\jp_f_tansu_single.p3d";
	};
	class StaticObj_JP_F_Tansu_Single_Ransacked: HouseNoDestruct
	{
		scope=1;
		displayName="Tansu, single box (ransacked)";
		model="\JP\furniture\storage\jp_f_tansu_single_ransacked.p3d";
	};
};
