// JP_Furniture - interior props (jp_f_*), placed as proxies inside JP buildings like vanilla
// \dz\structures\furniture, plus a StaticObj_JP_F_<name> class each (HouseNoDestruct, scope 1) as vanilla
// StaticObj_Furniture_<name>. No script, no vanilla change, no map dependency.
// GENERATED by japan_dev/spikes/B3a/build.py - edit the generator, not this file.
class CfgPatches
{
	class JP_Furniture
	{
		units[]={};
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"DZ_Data",
			"JP_Common"
		};
	};
};
class CfgVehicles
{
	class HouseNoDestruct;
	// jp_f_kama (kitchen)
	class StaticObj_JP_F_Kama: HouseNoDestruct
	{
		scope=1;
		displayName="Rice pot (kama) with lid";
		model="\JP\furniture\kitchen\jp_f_kama.p3d";
	};
	class StaticObj_JP_F_Kama_Nolid: HouseNoDestruct
	{
		scope=1;
		displayName="Rice pot, lid off, rusted";
		model="\JP\furniture\kitchen\jp_f_kama_nolid.p3d";
	};
	class StaticObj_JP_F_Kama_Nabe: HouseNoDestruct
	{
		scope=1;
		displayName="Small pot (nabe) with bail";
		model="\JP\furniture\kitchen\jp_f_kama_nabe.p3d";
	};
	class StaticObj_JP_F_Kama_Nabe_Rusted: HouseNoDestruct
	{
		scope=1;
		displayName="Small pot, rusted, burnt crust";
		model="\JP\furniture\kitchen\jp_f_kama_nabe_rusted.p3d";
	};
	// jp_f_jizai_kagi (kitchen)
	class StaticObj_JP_F_Jizai_Kagi: HouseNoDestruct
	{
		scope=1;
		displayName="Pot hook (jizai-kagi) with fish lever";
		model="\JP\furniture\kitchen\jp_f_jizai_kagi.p3d";
	};
	class StaticObj_JP_F_Jizai_Kagi_Abandoned: HouseNoDestruct
	{
		scope=1;
		displayName="Pot hook, lever jammed high, rusted pot";
		model="\JP\furniture\kitchen\jp_f_jizai_kagi_abandoned.p3d";
	};
	class StaticObj_JP_F_Jizai_Kagi_Plain: HouseNoDestruct
	{
		scope=1;
		displayName="Pot hook, plain bar lever";
		model="\JP\furniture\kitchen\jp_f_jizai_kagi_plain.p3d";
	};
	class StaticObj_JP_F_Jizai_Kagi_Plain_Abandoned: HouseNoDestruct
	{
		scope=1;
		displayName="Pot hook (plain), jammed, rusted pot";
		model="\JP\furniture\kitchen\jp_f_jizai_kagi_plain_abandoned.p3d";
	};
	// jp_f_mizugame (kitchen)
	class StaticObj_JP_F_Mizugame: HouseNoDestruct
	{
		scope=1;
		displayName="Water jar (mizugame), lid and dipper";
		model="\JP\furniture\kitchen\jp_f_mizugame.p3d";
	};
	class StaticObj_JP_F_Mizugame_Open: HouseNoDestruct
	{
		scope=1;
		displayName="Water jar, lid off leaning, dry";
		model="\JP\furniture\kitchen\jp_f_mizugame_open.p3d";
	};
	class StaticObj_JP_F_Mizugame_Broken: HouseNoDestruct
	{
		scope=1;
		displayName="Water jar, cracked, piece on the floor";
		model="\JP\furniture\kitchen\jp_f_mizugame_broken.p3d";
	};
	// jp_f_oke (kitchen)
	class StaticObj_JP_F_Oke_Bucket: HouseNoDestruct
	{
		scope=1;
		displayName="Handled bucket (oke)";
		model="\JP\furniture\kitchen\jp_f_oke_bucket.p3d";
	};
	class StaticObj_JP_F_Oke_Tipped: HouseNoDestruct
	{
		scope=1;
		displayName="Bucket on its side";
		model="\JP\furniture\kitchen\jp_f_oke_tipped.p3d";
	};
	class StaticObj_JP_F_Oke_Tarai: HouseNoDestruct
	{
		scope=1;
		displayName="Shallow washing tub (tarai)";
		model="\JP\furniture\kitchen\jp_f_oke_tarai.p3d";
	};
	class StaticObj_JP_F_Oke_Tarai_Dry: HouseNoDestruct
	{
		scope=1;
		displayName="Tarai, dried out, stave and hoop off";
		model="\JP\furniture\kitchen\jp_f_oke_tarai_dry.p3d";
	};
	class StaticObj_JP_F_Oke_Pickle: HouseNoDestruct
	{
		scope=1;
		displayName="Pickle tub with lid and stone";
		model="\JP\furniture\kitchen\jp_f_oke_pickle.p3d";
	};
	class StaticObj_JP_F_Oke_Pickle_Open: HouseNoDestruct
	{
		scope=1;
		displayName="Pickle tub, lid off, stone on the floor";
		model="\JP\furniture\kitchen\jp_f_oke_pickle_open.p3d";
	};
	// jp_f_tana (kitchen)
	class StaticObj_JP_F_Tana_091_1: HouseNoDestruct
	{
		scope=1;
		displayName="Wall shelf 0.91 m, 1 board";
		model="\JP\furniture\kitchen\jp_f_tana_091_1.p3d";
	};
	class StaticObj_JP_F_Tana_091_1_Sag: HouseNoDestruct
	{
		scope=1;
		displayName="Wall shelf 0.91 m, 1 board, sagging";
		model="\JP\furniture\kitchen\jp_f_tana_091_1_sag.p3d";
	};
	class StaticObj_JP_F_Tana_091_3: HouseNoDestruct
	{
		scope=1;
		displayName="Wall shelf 0.91 m, 3 boards";
		model="\JP\furniture\kitchen\jp_f_tana_091_3.p3d";
	};
	class StaticObj_JP_F_Tana_091_3_Sag: HouseNoDestruct
	{
		scope=1;
		displayName="Wall shelf 0.91 m, 3 boards, sagging";
		model="\JP\furniture\kitchen\jp_f_tana_091_3_sag.p3d";
	};
	class StaticObj_JP_F_Tana_136_1: HouseNoDestruct
	{
		scope=1;
		displayName="Wall shelf 1.36 m, 1 board";
		model="\JP\furniture\kitchen\jp_f_tana_136_1.p3d";
	};
	class StaticObj_JP_F_Tana_136_1_Sag: HouseNoDestruct
	{
		scope=1;
		displayName="Wall shelf 1.36 m, 1 board, sagging";
		model="\JP\furniture\kitchen\jp_f_tana_136_1_sag.p3d";
	};
	class StaticObj_JP_F_Tana_136_3: HouseNoDestruct
	{
		scope=1;
		displayName="Wall shelf 1.36 m, 3 boards";
		model="\JP\furniture\kitchen\jp_f_tana_136_3.p3d";
	};
	class StaticObj_JP_F_Tana_136_3_Sag: HouseNoDestruct
	{
		scope=1;
		displayName="Wall shelf 1.36 m, 3 boards, sagging";
		model="\JP\furniture\kitchen\jp_f_tana_136_3_sag.p3d";
	};
	class StaticObj_JP_F_Tana_182_1: HouseNoDestruct
	{
		scope=1;
		displayName="Wall shelf 1.82 m, 1 board";
		model="\JP\furniture\kitchen\jp_f_tana_182_1.p3d";
	};
	class StaticObj_JP_F_Tana_182_1_Sag: HouseNoDestruct
	{
		scope=1;
		displayName="Wall shelf 1.82 m, 1 board, sagging";
		model="\JP\furniture\kitchen\jp_f_tana_182_1_sag.p3d";
	};
	class StaticObj_JP_F_Tana_182_3: HouseNoDestruct
	{
		scope=1;
		displayName="Wall shelf 1.82 m, 3 boards";
		model="\JP\furniture\kitchen\jp_f_tana_182_3.p3d";
	};
	class StaticObj_JP_F_Tana_182_3_Sag: HouseNoDestruct
	{
		scope=1;
		displayName="Wall shelf 1.82 m, 3 boards, sagging";
		model="\JP\furniture\kitchen\jp_f_tana_182_3_sag.p3d";
	};
	// jp_f_firewood (kitchen)
	class StaticObj_JP_F_Firewood_Stack: HouseNoDestruct
	{
		scope=1;
		displayName="Firewood stack (maki)";
		model="\JP\furniture\kitchen\jp_f_firewood_stack.p3d";
	};
	class StaticObj_JP_F_Firewood_Low: HouseNoDestruct
	{
		scope=1;
		displayName="Firewood stack, half used, logs rolled";
		model="\JP\furniture\kitchen\jp_f_firewood_low.p3d";
	};
	class StaticObj_JP_F_Firewood_Bundle: HouseNoDestruct
	{
		scope=1;
		displayName="Brushwood bundles (soda)";
		model="\JP\furniture\kitchen\jp_f_firewood_bundle.p3d";
	};
	class StaticObj_JP_F_Firewood_Bundle_Loose: HouseNoDestruct
	{
		scope=1;
		displayName="Brushwood bundle burst, sticks scattered";
		model="\JP\furniture\kitchen\jp_f_firewood_bundle_loose.p3d";
	};
	// jp_f_jar (kitchen)
	class StaticObj_JP_F_Jar_S: HouseNoDestruct
	{
		scope=1;
		displayName="Storage jar S";
		model="\JP\furniture\kitchen\jp_f_jar_s.p3d";
	};
	class StaticObj_JP_F_Jar_M: HouseNoDestruct
	{
		scope=1;
		displayName="Storage jar M";
		model="\JP\furniture\kitchen\jp_f_jar_m.p3d";
	};
	class StaticObj_JP_F_Jar_L: HouseNoDestruct
	{
		scope=1;
		displayName="Storage jar L";
		model="\JP\furniture\kitchen\jp_f_jar_l.p3d";
	};
	class StaticObj_JP_F_Jar_S_Pale: HouseNoDestruct
	{
		scope=1;
		displayName="Storage jar S (pale glaze)";
		model="\JP\furniture\kitchen\jp_f_jar_s_pale.p3d";
	};
	class StaticObj_JP_F_Jar_M_Pale: HouseNoDestruct
	{
		scope=1;
		displayName="Storage jar M (pale glaze)";
		model="\JP\furniture\kitchen\jp_f_jar_m_pale.p3d";
	};
	class StaticObj_JP_F_Jar_S_Open: HouseNoDestruct
	{
		scope=1;
		displayName="Storage jar S, lid off";
		model="\JP\furniture\kitchen\jp_f_jar_s_open.p3d";
	};
	class StaticObj_JP_F_Jar_M_Open: HouseNoDestruct
	{
		scope=1;
		displayName="Storage jar M, lid off";
		model="\JP\furniture\kitchen\jp_f_jar_m_open.p3d";
	};
	class StaticObj_JP_F_Jar_L_Open: HouseNoDestruct
	{
		scope=1;
		displayName="Storage jar L, lid off";
		model="\JP\furniture\kitchen\jp_f_jar_l_open.p3d";
	};
	class StaticObj_JP_F_Jar_M_Broken: HouseNoDestruct
	{
		scope=1;
		displayName="Storage jar M, broken";
		model="\JP\furniture\kitchen\jp_f_jar_m_broken.p3d";
	};
	// jp_f_andon (heat_light)
	class StaticObj_JP_F_Andon_Kaku: HouseNoDestruct
	{
		scope=1;
		displayName="Standing paper lamp (andon)";
		model="\JP\furniture\heat_light\jp_f_andon_kaku.p3d";
	};
	class StaticObj_JP_F_Andon_Kaku_Tipped: HouseNoDestruct
	{
		scope=1;
		displayName="Andon, knocked over, paper torn";
		model="\JP\furniture\heat_light\jp_f_andon_kaku_tipped.p3d";
	};
	class StaticObj_JP_F_Andon_Ariake: HouseNoDestruct
	{
		scope=1;
		displayName="Bedside lamp (ariake andon)";
		model="\JP\furniture\heat_light\jp_f_andon_ariake.p3d";
	};
	class StaticObj_JP_F_Andon_Ariake_Tipped: HouseNoDestruct
	{
		scope=1;
		displayName="Bedside lamp, knocked over";
		model="\JP\furniture\heat_light\jp_f_andon_ariake_tipped.p3d";
	};
	// jp_f_hibachi (heat_light)
	class StaticObj_JP_F_Hibachi_Round: HouseNoDestruct
	{
		scope=1;
		displayName="Round ceramic brazier (hibachi)";
		model="\JP\furniture\heat_light\jp_f_hibachi_round.p3d";
	};
	class StaticObj_JP_F_Hibachi_Round_Tipped: HouseNoDestruct
	{
		scope=1;
		displayName="Round brazier, tipped, ash spilled";
		model="\JP\furniture\heat_light\jp_f_hibachi_round_tipped.p3d";
	};
	class StaticObj_JP_F_Hibachi_Box: HouseNoDestruct
	{
		scope=1;
		displayName="Wooden box brazier";
		model="\JP\furniture\heat_light\jp_f_hibachi_box.p3d";
	};
	class StaticObj_JP_F_Hibachi_Box_Tipped: HouseNoDestruct
	{
		scope=1;
		displayName="Box brazier, tipped, ash spilled";
		model="\JP\furniture\heat_light\jp_f_hibachi_box_tipped.p3d";
	};
	// jp_f_tabakobon (heat_light)
	class StaticObj_JP_F_Tabakobon: HouseNoDestruct
	{
		scope=1;
		displayName="Tobacco tray (tabako-bon)";
		model="\JP\furniture\heat_light\jp_f_tabakobon.p3d";
	};
	class StaticObj_JP_F_Tabakobon_Spilled: HouseNoDestruct
	{
		scope=1;
		displayName="Tobacco tray on its side, ash spilled";
		model="\JP\furniture\heat_light\jp_f_tabakobon_spilled.p3d";
	};
	// jp_f_nagamochi (storage)
	class StaticObj_JP_F_Nagamochi: HouseNoDestruct
	{
		scope=1;
		displayName="Long chest (nagamochi)";
		model="\JP\furniture\storage\jp_f_nagamochi.p3d";
	};
	class StaticObj_JP_F_Nagamochi_Open: HouseNoDestruct
	{
		scope=1;
		displayName="Long chest, lid thrown back, cloth spilling";
		model="\JP\furniture\storage\jp_f_nagamochi_open.p3d";
	};
	// jp_f_tansu (storage)
	class StaticObj_JP_F_Tansu: HouseNoDestruct
	{
		scope=1;
		displayName="Tansu (clothing chest)";
		model="\JP\furniture\storage\jp_f_tansu.p3d";
	};
	class StaticObj_JP_F_Tansu_Ransacked: HouseNoDestruct
	{
		scope=1;
		displayName="Tansu (ransacked)";
		model="\JP\furniture\storage\jp_f_tansu_ransacked.p3d";
	};
	class StaticObj_JP_F_Tansu_Single: HouseNoDestruct
	{
		scope=1;
		displayName="Tansu, single box";
		model="\JP\furniture\storage\jp_f_tansu_single.p3d";
	};
	class StaticObj_JP_F_Tansu_Single_Ransacked: HouseNoDestruct
	{
		scope=1;
		displayName="Tansu, single box (ransacked)";
		model="\JP\furniture\storage\jp_f_tansu_single_ransacked.p3d";
	};
	// jp_f_kori (storage)
	class StaticObj_JP_F_Kori: HouseNoDestruct
	{
		scope=1;
		displayName="Wicker trunk (kori)";
		model="\JP\furniture\storage\jp_f_kori.p3d";
	};
	class StaticObj_JP_F_Kori_2: HouseNoDestruct
	{
		scope=1;
		displayName="Wicker trunks, stack of two";
		model="\JP\furniture\storage\jp_f_kori_2.p3d";
	};
	class StaticObj_JP_F_Kori_Open: HouseNoDestruct
	{
		scope=1;
		displayName="Wicker trunk, lid off, garment out";
		model="\JP\furniture\storage\jp_f_kori_open.p3d";
	};
	// jp_f_box (storage)
	class StaticObj_JP_F_Box_S: HouseNoDestruct
	{
		scope=1;
		displayName="Wooden box, small";
		model="\JP\furniture\storage\jp_f_box_s.p3d";
	};
	class StaticObj_JP_F_Box_M: HouseNoDestruct
	{
		scope=1;
		displayName="Wooden box, medium";
		model="\JP\furniture\storage\jp_f_box_m.p3d";
	};
	class StaticObj_JP_F_Box_L: HouseNoDestruct
	{
		scope=1;
		displayName="Wooden box, large";
		model="\JP\furniture\storage\jp_f_box_l.p3d";
	};
	class StaticObj_JP_F_Box_Stack3: HouseNoDestruct
	{
		scope=1;
		displayName="Wooden boxes, stack of three";
		model="\JP\furniture\storage\jp_f_box_stack3.p3d";
	};
	class StaticObj_JP_F_Box_S_Lacquer: HouseNoDestruct
	{
		scope=1;
		displayName="Lacquered box, small (T3)";
		model="\JP\furniture\storage\jp_f_box_s_lacquer.p3d";
	};
	class StaticObj_JP_F_Box_M_Lacquer: HouseNoDestruct
	{
		scope=1;
		displayName="Lacquered box, medium (T3)";
		model="\JP\furniture\storage\jp_f_box_m_lacquer.p3d";
	};
	class StaticObj_JP_F_Box_Open: HouseNoDestruct
	{
		scope=1;
		displayName="Wooden box, lid off, spilled";
		model="\JP\furniture\storage\jp_f_box_open.p3d";
	};
	class StaticObj_JP_F_Box_Stack3_Toppled: HouseNoDestruct
	{
		scope=1;
		displayName="Box stack, small box knocked off";
		model="\JP\furniture\storage\jp_f_box_stack3_toppled.p3d";
	};
	// jp_f_tawara (storage)
	class StaticObj_JP_F_Tawara: HouseNoDestruct
	{
		scope=1;
		displayName="Straw rice bale (tawara)";
		model="\JP\furniture\storage\jp_f_tawara.p3d";
	};
	class StaticObj_JP_F_Tawara_Burst: HouseNoDestruct
	{
		scope=1;
		displayName="Rice bale, burst, rice spilled";
		model="\JP\furniture\storage\jp_f_tawara_burst.p3d";
	};
	class StaticObj_JP_F_Tawara_Stack6: HouseNoDestruct
	{
		scope=1;
		displayName="Rice bales, pyramid of six";
		model="\JP\furniture\storage\jp_f_tawara_stack6.p3d";
	};
	class StaticObj_JP_F_Tawara_Stack6_Burst: HouseNoDestruct
	{
		scope=1;
		displayName="Rice bales, top one burst";
		model="\JP\furniture\storage\jp_f_tawara_stack6_burst.p3d";
	};
	class StaticObj_JP_F_Tawara_Kamasu: HouseNoDestruct
	{
		scope=1;
		displayName="Straw bag (kamasu)";
		model="\JP\furniture\storage\jp_f_tawara_kamasu.p3d";
	};
	class StaticObj_JP_F_Tawara_Kamasu_Stack3: HouseNoDestruct
	{
		scope=1;
		displayName="Straw bags, stack of three";
		model="\JP\furniture\storage\jp_f_tawara_kamasu_stack3.p3d";
	};
	class StaticObj_JP_F_Tawara_Kamasu_Burst: HouseNoDestruct
	{
		scope=1;
		displayName="Straw bag, split and slumped";
		model="\JP\furniture\storage\jp_f_tawara_kamasu_burst.p3d";
	};
	// jp_f_rack (storage)
	class StaticObj_JP_F_Rack_1ken: HouseNoDestruct
	{
		scope=1;
		displayName="Board shelving 1.82 m (kura shelves)";
		model="\JP\furniture\storage\jp_f_rack_1ken.p3d";
	};
	class StaticObj_JP_F_Rack_1ken_Collapsed: HouseNoDestruct
	{
		scope=1;
		displayName="Board shelving 1.82 m, board down, goods on the floor";
		model="\JP\furniture\storage\jp_f_rack_1ken_collapsed.p3d";
	};
	class StaticObj_JP_F_Rack_Half: HouseNoDestruct
	{
		scope=1;
		displayName="Board shelving 0.91 m";
		model="\JP\furniture\storage\jp_f_rack_half.p3d";
	};
	class StaticObj_JP_F_Rack_Half_Collapsed: HouseNoDestruct
	{
		scope=1;
		displayName="Board shelving 0.91 m, board down";
		model="\JP\furniture\storage\jp_f_rack_half_collapsed.p3d";
	};
	// jp_f_futon_stack (bedding)
	class StaticObj_JP_F_Futon_Stack: HouseNoDestruct
	{
		scope=1;
		displayName="Folded bedding stack (futon, yogi)";
		model="\JP\furniture\bedding\jp_f_futon_stack.p3d";
	};
	class StaticObj_JP_F_Futon_Stack_Slumped: HouseNoDestruct
	{
		scope=1;
		displayName="Bedding stack slumped, quilt dragged off";
		model="\JP\furniture\bedding\jp_f_futon_stack_slumped.p3d";
	};
	// jp_f_futon_laid (bedding)
	class StaticObj_JP_F_Futon_Laid: HouseNoDestruct
	{
		scope=1;
		displayName="Laid-out bedding, quilt thrown back";
		model="\JP\furniture\bedding\jp_f_futon_laid.p3d";
	};
	class StaticObj_JP_F_Futon_Laid_Dragged: HouseNoDestruct
	{
		scope=1;
		displayName="Laid-out bedding, quilt dragged aside, stained";
		model="\JP\furniture\bedding\jp_f_futon_laid_dragged.p3d";
	};
	// jp_f_mushiro (bedding)
	class StaticObj_JP_F_Mushiro: HouseNoDestruct
	{
		scope=1;
		displayName="Straw floor mat (mushiro)";
		model="\JP\furniture\bedding\jp_f_mushiro.p3d";
	};
	class StaticObj_JP_F_Mushiro_Torn: HouseNoDestruct
	{
		scope=1;
		displayName="Straw mat, torn, corner curled";
		model="\JP\furniture\bedding\jp_f_mushiro_torn.p3d";
	};
	class StaticObj_JP_F_Mushiro_Rolled: HouseNoDestruct
	{
		scope=1;
		displayName="Straw mat, rolled";
		model="\JP\furniture\bedding\jp_f_mushiro_rolled.p3d";
	};
	class StaticObj_JP_F_Mushiro_Rolled_Loose: HouseNoDestruct
	{
		scope=1;
		displayName="Straw mat, half unrolled";
		model="\JP\furniture\bedding\jp_f_mushiro_rolled_loose.p3d";
	};
	class StaticObj_JP_F_Mushiro_Pile: HouseNoDestruct
	{
		scope=1;
		displayName="Straw mats, small pile";
		model="\JP\furniture\bedding\jp_f_mushiro_pile.p3d";
	};
	class StaticObj_JP_F_Mushiro_Pile_Spread: HouseNoDestruct
	{
		scope=1;
		displayName="Straw mats, pile slid apart";
		model="\JP\furniture\bedding\jp_f_mushiro_pile_spread.p3d";
	};
};
