// japantest_offline.japantestisland - GENERATED by japan_dev/tools/editor_bridge/offline_mission.py from the MP
// mission japantest.japantestisland (T's build_mission.py). Do not edit: rerun the script (start-japan-offline.bat
// does it on every launch). Single-player DayZDiag version: no client connects offline, so this file creates the
// player itself and returns a MissionGameplay.

void JPOffline_Item(string cls, float x, float z)
{
	vector pos = Vector(x, 25.0, z);
	Object obj = GetGame().CreateObjectEx(cls, pos, ECE_PLACE_ON_SURFACE | ECE_NOPERSISTENCY_WORLD);
	if ( !obj )
		Print("[JPOffline] item class not found: " + cls);
}

void JPOffline_Creature(string cls, float x, float z, float yaw)
{
	float y = GetGame().SurfaceY(x, z);
	vector pos = Vector(x, y, z);
	Object obj = GetGame().CreateObjectEx(cls, pos, ECE_PLACE_ON_SURFACE | ECE_INITAI | ECE_EQUIP_ATTACHMENTS | ECE_NOPERSISTENCY_WORLD);
	if ( !obj )
	{
		Print("[JPOffline] creature class not found: " + cls);
		return;
	}
	obj.SetOrientation(Vector(yaw, 0, 0));
}

void JPOffline_CheckSpawner()
{
	// the cfggameplay object spawner normally runs by itself (DayZGame.GlobalsInit); make sure it did
	string probeType = "StaticObj_Misc_HayBale";
	if ( probeType == "" )
		return;
	array<Object> found = new array<Object>;
	GetGame().GetObjectsAtPosition3D(Vector(1004.000, 25.770, 944.000), 1.0, found, null);
	bool ok = false;
	for ( int i = 0; i < found.Count(); i++ )
	{
		if ( found[i] && found[i].GetType() == probeType )
			ok = true;
	}
	if ( ok )
	{
		Print("[JPOffline] object spawner ran (found " + probeType + ")");
		return;
	}
	Print("[JPOffline] object spawner did not run offline - spawning spawns/*.json now");
	ObjectSpawnerHandler.SpawnObjects();
}

void main()
{
	//INIT ECONOMY--------------------------------------
	Hive ce = CreateHive();
	if ( ce )
		ce.InitOffline();

	GetGame().GetWorld().SetDate(2026, 4, 5, 10, 0);

	float sx = 1024.0;
	float sz = 985.0;
	float sy = GetGame().SurfaceY(sx, sz);
	PlayerBase player = PlayerBase.Cast(GetGame().CreatePlayer(null, "SurvivorM_Mirek", Vector(sx, sy, sz), 0, "NONE"));
	if ( player )
	{
		player.SetOrientation(Vector(0, 0, 0));
		player.GetInventory().CreateInInventory("TShirt_Beige");
		player.GetInventory().CreateInInventory("Jeans_Blue");
		player.GetInventory().CreateInInventory("AthleticShoes_Black");
		player.GetInventory().CreateInInventory("Hatchet");
		GetGame().SelectPlayer(null, player);
	}
	else
	{
		Print("[JPOffline] CreatePlayer failed");
	}

	JPOffline_Item("JP_Katana", 1000.00, 975.00);
	JPOffline_Item("JP_Yari", 1001.50, 975.00);
	JPOffline_Item("JP_Yumi", 1003.00, 975.00);
	JPOffline_Item("JP_Yumi_XB", 1004.50, 975.00);
	JPOffline_Item("JP_Ammo_Ya", 1006.00, 975.00);
	JPOffline_Item("JP_Ammo_Ya", 1007.50, 975.00);
	JPOffline_Item("JP_Ammo_Ya", 1009.00, 975.00);
	JPOffline_Item("Sword", 1010.50, 975.00);
	JPOffline_Item("SpearStone", 1012.00, 975.00);
	JPOffline_Item("RecurveBow", 1013.50, 975.00);
	JPOffline_Item("Crossbow", 1015.00, 975.00);
	JPOffline_Item("Ammo_HuntingBolt", 1016.50, 975.00);
	JPOffline_Item("Ammo_HuntingBolt", 1018.00, 975.00);
	JPOffline_Item("Hatchet", 1019.50, 975.00);
	JPOffline_Item("WoodAxe", 1021.00, 975.00);
	JPOffline_Item("Machete", 1022.50, 975.00);
	JPOffline_Item("JP_BambooPole", 1024.00, 975.00);
	JPOffline_Item("JP_BambooPole", 1025.50, 975.00);
	JPOffline_Item("Canteen", 1027.00, 975.00);
	JPOffline_Item("Hatchet", 1028.50, 975.00);
	JPOffline_Item("ChernarusMap", 1030.00, 975.00);
	JPOffline_Item("OrienteeringCompass", 1031.50, 975.00);
	JPOffline_Item("Binoculars", 1033.00, 975.00);
	JPOffline_Item("JP_Kasa", 1034.50, 975.00);
	JPOffline_Item("JP_Kasa", 1036.00, 975.00);
	JPOffline_Item("JP_Kimono_Short", 1037.50, 975.00);
	JPOffline_Item("JP_Kimono_Short", 1039.00, 975.00);
	JPOffline_Item("JP_Kimono_Long", 1040.50, 975.00);
	JPOffline_Item("JP_Kimono_Long", 1042.00, 975.00);
	JPOffline_Item("JP_Tabi_Waraji", 1043.50, 975.00);
	JPOffline_Item("JP_Tabi_Waraji", 1045.00, 975.00);
	JPOffline_Item("CowboyHat_Brown", 1046.50, 975.00);
	JPOffline_Item("Raincoat_Orange", 1000.00, 973.50);
	JPOffline_Item("NurseDress_Blue", 1001.50, 973.50);
	JPOffline_Item("Sneakers_Black", 1003.00, 973.50);
	JPOffline_Creature("ZmbM_CitizenASkinny_Blue", 1010.00, 950.00, 0.0);
	JPOffline_Creature("ZmbF_CitizenANormal_Beige", 1022.00, 938.00, 0.0);
	JPOffline_Creature("Animal_CervusElaphus", 1037.00, 942.00, 90.0);
	Print("[JPOffline] test layout spawned: 35 items, 3 creatures");
	GetGame().GetCallQueue(CALL_CATEGORY_GAMEPLAY).CallLater(JPOffline_CheckSpawner, 5000, false);
}

Mission CreateCustomMission(string path)
{
	return new MissionGameplay();
}
