"""config.cpp for jp_characters.pbo (CfgPatches JP_Characters). Generated; edit here, not in src.

Each item subclasses a vanilla clothing base so slot, insulation (heatIsolation), wetness, cargo, sounds and
repair are inherited unchanged. What is redefined:
  - model / ClothingTypes / hiddenSelections(+Textures) - our meshes and textures
  - DamageSystem: a child's `class DamageSystem` would not inherit the parent's nested classes, so the parent's
    values (hitpoints, GlobalArmor) are copied verbatim from the vanilla config and only healthLevels point at
    our rvmats (pristine / damage / destruct), which is what makes the damage states show on our textures.
"""
import os

from wlib import SRC

MODELS = {
    "jp_kasa_m": "worn", "jp_kasa_f": "worn", "jp_kasa_g": "ground",
    "jp_kimono_short_m": "worn", "jp_kimono_short_f": "worn", "jp_kimono_short_g": "ground",
    "jp_kimono_long_m": "worn", "jp_kimono_long_f": "worn", "jp_kimono_long_g": "ground",
    "jp_tabi_waraji_m": "worn", "jp_tabi_waraji_f": "worn", "jp_tabi_waraji_g": "ground",
}


def all_models():
    return dict(MODELS)


def health_levels(rv):
    lv = [(1.0, ""), (0.7, ""), (0.5, "_damage"), (0.3, "_damage"), (0.0, "_destruct")]
    rows = []
    for h, suf in lv:
        rows.append('\t\t\t\t\t\t{%s, {"%s%s.rvmat"}}' % (("%g" % h), rv, suf))
    return "{\n" + ",\n".join(rows) + "\n\t\t\t\t\t}"


ARMOR_SHIRT = """
			class GlobalArmor
			{
				class Melee
				{
					class Health { damage=0.95; };
					class Blood { damage=1; };
					class Shock { damage=1; };
				};
				class Infected
				{
					class Health { damage=0.95; };
					class Blood { damage=1; };
					class Shock { damage=1; };
				};
			};"""


def item(cls, parent, disp, desc, folder, stem, tex, slot, info, hp, armor="", personality=False, extra=""):
    base = "JP\\characters\\%s" % folder
    rv = "%s\\data\\%s" % (base, tex)
    hs = '"camoGround", "camoMale", "camoFemale"' + (', "personality"' if personality else "")
    return """	class %(cls)s: %(parent)s
	{
		scope = 2;
		displayName = "%(disp)s";
		descriptionShort = "%(desc)s";
		model = "\\%(base)s\\%(stem)s_g.p3d";
		inventorySlot[] = {"%(slot)s"};
		itemInfo[] = {"Clothing", "%(info)s"};
		hiddenSelections[] = {%(hs)s};
		hiddenSelectionsTextures[] =
		{
			"%(base)s\\data\\%(tex)s_co.paa",
			"%(base)s\\data\\%(tex)s_co.paa",
			"%(base)s\\data\\%(tex)s_co.paa"
		};%(extra)s
		class ClothingTypes
		{
			male = "\\%(base)s\\%(stem)s_m.p3d";
			female = "\\%(base)s\\%(stem)s_f.p3d";
		};
		class DamageSystem
		{
			class GlobalHealth
			{
				class Health
				{
					hitpoints = %(hp)d;
					healthLevels[] = %(hl)s;
				};
			};%(armor)s
		};
	};
""" % dict(cls=cls, parent=parent, disp=disp, desc=desc, base=base, stem=stem, tex=tex, slot=slot, info=info, hs=hs,
           hp=hp, hl=health_levels(rv), armor=armor, extra=extra)


def write_config():
    body = []
    body.append(item("JP_Kasa", "CowboyHat_ColorBase", "Kasa (straw hat)",
                     "A conical traveller's hat of woven sedge. Keeps the sun and the rain off.",
                     "kasa", "jp_kasa", "jp_kasa", "Headgear", "Headgear", 100))
    body.append(item("JP_Kimono_Short", "Shirt_ColorBase", "Kimono (short, indigo)",
                     "A thigh-length cotton kimono dyed with indigo, tied with an obi.",
                     "kimono", "jp_kimono_short", "jp_kimono_short", "Body", "Body", 70, ARMOR_SHIRT, True))
    body.append(item("JP_Kimono_Long", "Shirt_ColorBase", "Kimono (long, indigo)",
                     "A floor-length cotton kimono dyed with indigo, tied with an obi.",
                     "kimono", "jp_kimono_long", "jp_kimono_long", "Body", "Body", 70, ARMOR_SHIRT, True))
    body.append(item("JP_Tabi_Waraji", "Sneakers_ColorBase", "Tabi and waraji",
                     "Split-toe cotton socks worn with straw sandals.",
                     "tabi", "jp_tabi_waraji", "jp_tabi_waraji", "Feet", "Feet", 80))
    txt = """// Generated by spikes/W_wearables/tools/configgen.py - do not edit by hand.
class CfgPatches
{
	class JP_Characters
	{
		units[] = {"JP_Kasa", "JP_Kimono_Short", "JP_Kimono_Long", "JP_Tabi_Waraji"};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Data", "DZ_Characters", "DZ_Characters_Headgear", "DZ_Characters_Tops", "DZ_Characters_Shoes"};
	};
};
class CfgVehicles
{
	class CowboyHat_ColorBase;
	class Shirt_ColorBase;
	class Sneakers_ColorBase;
%s};
""" % "".join(body)
    with open(os.path.join(SRC, "config.cpp"), "wb") as f:
        f.write(txt.encode())
    return txt


if __name__ == "__main__":
    print(write_config())
