"""model.cfg writer for W: the vanilla DayzTemporarySkeleton, bone for bone.

The 159 (bone, parent) pairs are read from the vanilla binarized clothing (every worn _m/_f p3d we checked -
raincoat_m/f, cowboyhat, athleticshoes_m, torso3_m, baseballcap_m - carries the identical list; see
odol_mesh.read_skeleton). Spelling is the binarized one (lower case; names are case-insensitive).
"""
import json
import os

from wlib import DATA

SKELETON_JSON = os.path.join(DATA, "dayz_temporary_skeleton.json")


def skeleton_pairs():
    from odol_mesh import read_skeleton
    d = open(r"P:\DZ\characters\tops\raincoat_m.p3d", "rb").read()
    _, bones = read_skeleton(d)
    return bones


def model_cfg(worn_models, ground_models):
    pairs = skeleton_pairs()
    lines = []
    for i in range(0, len(pairs), 4):
        chunk = pairs[i:i + 4]
        lines.append("\t\t\t" + ", ".join('"%s","%s"' % (n, p) for n, p in chunk) + ("," if i + 4 < len(pairs) else ""))
    bones = "\n".join(lines)
    out = []
    out.append("// Generated by spikes/W_wearables/tools/modelcfg.py - do not edit by hand.\n")
    out.append("// DayzTemporarySkeleton: the vanilla worn-clothing skeleton, copied bone for bone from the\n")
    out.append("// binarized vanilla clothing (159 bones, identical in every _m/_f model checked).\n")
    out.append("class CfgSkeletons\n{\n\tclass Default\n\t{\n\t\tisDiscrete = 1;\n\t\tskeletonInherit = \"\";\n"
               "\t\tskeletonBones[] = {};\n\t};\n")
    out.append("\tclass DayzTemporarySkeleton: Default\n\t{\n\t\tisDiscrete = 0;\n\t\tskeletonInherit = \"\";\n"
               "\t\tskeletonBones[] =\n\t\t{\n%s\n\t\t};\n\t};\n};\n\n" % bones)
    out.append("class CfgModels\n{\n\tclass Default\n\t{\n\t\tsectionsInherit = \"\";\n\t\tsections[] = {};\n"
               "\t\tskeletonName = \"\";\n\t};\n")
    out.append("\tclass JP_WornClothing: Default\n\t{\n\t\tskeletonName = \"DayzTemporarySkeleton\";\n"
               "\t\tsections[] = {\"camoMale\", \"camoFemale\", \"camoGround\", \"personality\"};\n\t};\n")
    out.append("\tclass JP_GroundClothing: Default\n\t{\n\t\tsections[] = {\"camoGround\"};\n\t};\n")
    for m in worn_models:
        out.append("\tclass %s: JP_WornClothing {};\n" % m)
    for m in ground_models:
        out.append("\tclass %s: JP_GroundClothing {};\n" % m)
    out.append("};\n")
    return "".join(out)
