// JP_Site - outdoor site objects (jp_s_*), stage S, B3b wave 1. Map objects: StaticObj_JP_S_<name>
// (HouseNoDestruct, scope 1, like vanilla StaticObj_Misc_*); the wells Land_JP_S_Well_* with a one-line
// script class 'extends Well' each (drink + wash hands + fill, exactly as vanilla Land_Misc_Well_Pump_*).
// Shop-front dressing is meant as proxies on shop buildings; it also has classes for loose placement.
// No vanilla change, no map dependency. GENERATED by japan_dev/spikes/B3b/build.py - edit the generator.
class CfgPatches
{
	class JP_Site
	{
		units[]={};
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"DZ_Data",
			"DZ_Scripts",
			"JP_Common"
		};
	};
};
class CfgMods
{
	class JP_Site
	{
		dir="Japan";
		picture="";
		action="";
		hideName=1;
		hidePicture=1;
		name="JP Site";
		credits="";
		author="japan_dev";
		authorID="0";
		version="0.1";
		extra=0;
		type="mod";
		dependencies[]={"World"};
		class defs
		{
			class worldScriptModule
			{
				value="";
				files[]={"JP/site/scripts/4_World"};
			};
		};
	};
};
class CfgVehicles
{
	class HouseNoDestruct;
	// jp_s_oke (yard)
	class StaticObj_JP_S_Oke_Tarai: HouseNoDestruct
	{
		scope=1;
		displayName="Wash tub (tarai), leaves inside";
		model="\JP\site\yard\jp_s_oke_tarai.p3d";
	};
	class StaticObj_JP_S_Oke_Teoke: HouseNoDestruct
	{
		scope=1;
		displayName="Hand bucket (teoke)";
		model="\JP\site\yard\jp_s_oke_teoke.p3d";
	};
	class StaticObj_JP_S_Oke_Ninai: HouseNoDestruct
	{
		scope=1;
		displayName="Carrying bucket (ninai-oke)";
		model="\JP\site\yard\jp_s_oke_ninai.p3d";
	};
	class StaticObj_JP_S_Oke_Taru_Lid: HouseNoDestruct
	{
		scope=1;
		displayName="Pickle barrel with lid and stone";
		model="\JP\site\yard\jp_s_oke_taru_lid.p3d";
	};
	class StaticObj_JP_S_Oke_Stake: HouseNoDestruct
	{
		scope=1;
		displayName="Bucket upside down on a stake (oke-hoshi)";
		model="\JP\site\yard\jp_s_oke_stake.p3d";
	};
	class StaticObj_JP_S_Oke_Ab_Tipped: HouseNoDestruct
	{
		scope=1;
		displayName="Barrel tipped over, hoop sprung";
		model="\JP\site\yard\jp_s_oke_ab_tipped.p3d";
	};
	class StaticObj_JP_S_Oke_Ab_Staves: HouseNoDestruct
	{
		scope=1;
		displayName="Tub collapsed into staves";
		model="\JP\site\yard\jp_s_oke_ab_staves.p3d";
	};
	// jp_s_fire_tub (water)
	class StaticObj_JP_S_Fire_Tub_Full: HouseNoDestruct
	{
		scope=1;
		displayName="Corner fire tub with a bucket pyramid";
		model="\JP\site\water\jp_s_fire_tub_full.p3d";
	};
	class StaticObj_JP_S_Fire_Tub_Open: HouseNoDestruct
	{
		scope=1;
		displayName="Fire tub, lid gone, three buckets down";
		model="\JP\site\water\jp_s_fire_tub_open.p3d";
	};
	class StaticObj_JP_S_Fire_Tub_Eave: HouseNoDestruct
	{
		scope=1;
		displayName="Fire bucket on an eave peg (building proxy)";
		model="\JP\site\water\jp_s_fire_tub_eave.p3d";
	};
	class StaticObj_JP_S_Fire_Tub_Rural: HouseNoDestruct
	{
		scope=1;
		displayName="Rain barrel under an eave (rural)";
		model="\JP\site\water\jp_s_fire_tub_rural.p3d";
	};
	class StaticObj_JP_S_Fire_Tub_Ab_Scattered: HouseNoDestruct
	{
		scope=1;
		displayName="Fire tub, pyramid collapsed, buckets scattered";
		model="\JP\site\water\jp_s_fire_tub_ab_scattered.p3d";
	};
	// jp_s_firewood_stack (yard)
	class StaticObj_JP_S_Firewood_Stack_Wall_1ken_H120: HouseNoDestruct
	{
		scope=1;
		displayName="Firewood stack on a wall, 1 ken x 1.2 m";
		model="\JP\site\yard\jp_s_firewood_stack_wall_1ken_h120.p3d";
	};
	class StaticObj_JP_S_Firewood_Stack_Wall_1ken_H180: HouseNoDestruct
	{
		scope=1;
		displayName="Firewood stack on a wall, 1 ken x 1.8 m";
		model="\JP\site\yard\jp_s_firewood_stack_wall_1ken_h180.p3d";
	};
	class StaticObj_JP_S_Firewood_Stack_Half: HouseNoDestruct
	{
		scope=1;
		displayName="Firewood stack end piece, half ken, stepped";
		model="\JP\site\yard\jp_s_firewood_stack_half.p3d";
	};
	class StaticObj_JP_S_Firewood_Stack_Free_Posts: HouseNoDestruct
	{
		scope=1;
		displayName="Firewood stack between two stakes, board cap";
		model="\JP\site\yard\jp_s_firewood_stack_free_posts.p3d";
	};
	class StaticObj_JP_S_Firewood_Stack_Bundle: HouseNoDestruct
	{
		scope=1;
		displayName="Brushwood bundle (soda) leaning on a wall";
		model="\JP\site\yard\jp_s_firewood_stack_bundle.p3d";
	};
	class StaticObj_JP_S_Firewood_Stack_Ab_Collapsed: HouseNoDestruct
	{
		scope=1;
		displayName="Firewood stack, one end slumped, spilled";
		model="\JP\site\yard\jp_s_firewood_stack_ab_collapsed.p3d";
	};
	// jp_s_bench (street)
	class StaticObj_JP_S_Bench_1ken: HouseNoDestruct
	{
		scope=1;
		displayName="Bench (endai), 1 ken";
		model="\JP\site\street\jp_s_bench_1ken.p3d";
	};
	class StaticObj_JP_S_Bench_Long: HouseNoDestruct
	{
		scope=1;
		displayName="Tea-stand bench, 1.5 ken";
		model="\JP\site\street\jp_s_bench_long.p3d";
	};
	class StaticObj_JP_S_Bench_Mat: HouseNoDestruct
	{
		scope=1;
		displayName="Bench with a rotted straw mat";
		model="\JP\site\street\jp_s_bench_mat.p3d";
	};
	class StaticObj_JP_S_Bench_Ab_Tipped: HouseNoDestruct
	{
		scope=1;
		displayName="Bench tipped on its side";
		model="\JP\site\street\jp_s_bench_ab_tipped.p3d";
	};
	class StaticObj_JP_S_Bench_Ab_Broken: HouseNoDestruct
	{
		scope=1;
		displayName="Bench, one leg frame collapsed";
		model="\JP\site\street\jp_s_bench_ab_broken.p3d";
	};
	// jp_s_laundry_pole (yard)
	class StaticObj_JP_S_Laundry_Pole_Forked: HouseNoDestruct
	{
		scope=1;
		displayName="Drying pole on forked posts";
		model="\JP\site\yard\jp_s_laundry_pole_forked.p3d";
	};
	class StaticObj_JP_S_Laundry_Pole_Crossed: HouseNoDestruct
	{
		scope=1;
		displayName="Drying pole on crossed stakes";
		model="\JP\site\yard\jp_s_laundry_pole_crossed.p3d";
	};
	class StaticObj_JP_S_Laundry_Pole_Load_Cloth: HouseNoDestruct
	{
		scope=1;
		displayName="Drying pole, faded kimono, one cloth fallen";
		model="\JP\site\yard\jp_s_laundry_pole_load_cloth.p3d";
	};
	class StaticObj_JP_S_Laundry_Pole_Load_Kaki: HouseNoDestruct
	{
		scope=1;
		displayName="Persimmons dried black on strings (autumn)";
		model="\JP\site\yard\jp_s_laundry_pole_load_kaki.p3d";
	};
	class StaticObj_JP_S_Laundry_Pole_Load_Daikon: HouseNoDestruct
	{
		scope=1;
		displayName="Daikon hung in pairs, shrivelled (autumn)";
		model="\JP\site\yard\jp_s_laundry_pole_load_daikon.p3d";
	};
	class StaticObj_JP_S_Laundry_Pole_Load_Net: HouseNoDestruct
	{
		scope=1;
		displayName="A small net draped on the pole (fishing village)";
		model="\JP\site\yard\jp_s_laundry_pole_load_net.p3d";
	};
	class StaticObj_JP_S_Laundry_Pole_Ab_Down: HouseNoDestruct
	{
		scope=1;
		displayName="Drying pole down, one post leaning";
		model="\JP\site\yard\jp_s_laundry_pole_ab_down.p3d";
	};
	// jp_s_tenbin (yard)
	class StaticObj_JP_S_Tenbin_Baskets: HouseNoDestruct
	{
		scope=1;
		displayName="Shoulder pole with two baskets";
		model="\JP\site\yard\jp_s_tenbin_baskets.p3d";
	};
	class StaticObj_JP_S_Tenbin_Buckets: HouseNoDestruct
	{
		scope=1;
		displayName="Shoulder pole with two buckets";
		model="\JP\site\yard\jp_s_tenbin_buckets.p3d";
	};
	class StaticObj_JP_S_Tenbin_Boxes: HouseNoDestruct
	{
		scope=1;
		displayName="Shoulder pole with peddler's boxes";
		model="\JP\site\yard\jp_s_tenbin_boxes.p3d";
	};
	class StaticObj_JP_S_Tenbin_Leaning: HouseNoDestruct
	{
		scope=1;
		displayName="Shoulder pole leaning on a wall";
		model="\JP\site\yard\jp_s_tenbin_leaning.p3d";
	};
	class StaticObj_JP_S_Tenbin_Ab_Dropped: HouseNoDestruct
	{
		scope=1;
		displayName="Shoulder pole dropped, basket overturned";
		model="\JP\site\yard\jp_s_tenbin_ab_dropped.p3d";
	};
	// jp_s_handcart (yard)
	class StaticObj_JP_S_Handcart_Empty: HouseNoDestruct
	{
		scope=1;
		displayName="Handcart (daihachi-guruma), handles down";
		model="\JP\site\yard\jp_s_handcart_empty.p3d";
	};
	class StaticObj_JP_S_Handcart_Load_Bales: HouseNoDestruct
	{
		scope=1;
		displayName="Handcart with rice bales roped on";
		model="\JP\site\yard\jp_s_handcart_load_bales.p3d";
	};
	class StaticObj_JP_S_Handcart_Load_Barrels: HouseNoDestruct
	{
		scope=1;
		displayName="Handcart with barrels";
		model="\JP\site\yard\jp_s_handcart_load_barrels.p3d";
	};
	class StaticObj_JP_S_Handcart_Small: HouseNoDestruct
	{
		scope=1;
		displayName="Small cart (niguruma)";
		model="\JP\site\yard\jp_s_handcart_small.p3d";
	};
	class StaticObj_JP_S_Handcart_Ab_Tipped: HouseNoDestruct
	{
		scope=1;
		displayName="Handcart tipped on its side, load spilled";
		model="\JP\site\yard\jp_s_handcart_ab_tipped.p3d";
	};
	class StaticObj_JP_S_Handcart_Ab_Broken: HouseNoDestruct
	{
		scope=1;
		displayName="Handcart with a broken wheel, bed down";
		model="\JP\site\yard\jp_s_handcart_ab_broken.p3d";
	};
	class StaticObj_JP_S_Handcart_Ab_Wreck: HouseNoDestruct
	{
		scope=1;
		displayName="Handcart wreck, wheels off, slats gone";
		model="\JP\site\yard\jp_s_handcart_ab_wreck.p3d";
	};
	// jp_s_well_tsurube (water)
	class Land_JP_S_Well_Tsurube_Curb_Tub: HouseNoDestruct
	{
		scope=1;
		displayName="Pulley well, round tub curb";
		model="\JP\site\water\jp_s_well_tsurube_curb_tub.p3d";
	};
	class Land_JP_S_Well_Tsurube_Curb_Igeta: HouseNoDestruct
	{
		scope=1;
		displayName="Pulley well, square igeta curb";
		model="\JP\site\water\jp_s_well_tsurube_curb_igeta.p3d";
	};
	class Land_JP_S_Well_Tsurube_Curb_Stone: HouseNoDestruct
	{
		scope=1;
		displayName="Pulley well, stone curb";
		model="\JP\site\water\jp_s_well_tsurube_curb_stone.p3d";
	};
	class Land_JP_S_Well_Tsurube_Roofed: HouseNoDestruct
	{
		scope=1;
		displayName="Roofed pulley well (dwelling 28)";
		model="\JP\site\water\jp_s_well_tsurube_roofed.p3d";
	};
	class Land_JP_S_Well_Tsurube_Lid: HouseNoDestruct
	{
		scope=1;
		displayName="Well curb with a board lid";
		model="\JP\site\water\jp_s_well_tsurube_lid.p3d";
	};
	class Land_JP_S_Well_Tsurube_Ab_Open: HouseNoDestruct
	{
		scope=1;
		displayName="Pulley well, rope rotted, lid askew";
		model="\JP\site\water\jp_s_well_tsurube_ab_open.p3d";
	};
	// jp_s_well_hanetsurube (water)
	class Land_JP_S_Well_Hanetsurube_Well: HouseNoDestruct
	{
		scope=1;
		displayName="Lever well (hanetsurube)";
		model="\JP\site\water\jp_s_well_hanetsurube_well.p3d";
	};
	class StaticObj_JP_S_Well_Hanetsurube_Field: HouseNoDestruct
	{
		scope=1;
		displayName="Field sweep over a ditch";
		model="\JP\site\water\jp_s_well_hanetsurube_field.p3d";
	};
	class Land_JP_S_Well_Hanetsurube_Ab_Down: HouseNoDestruct
	{
		scope=1;
		displayName="Lever well, lashing rotted, pole down";
		model="\JP\site\water\jp_s_well_hanetsurube_ab_down.p3d";
	};
	// jp_s_stone_jizo (roadside)
	class StaticObj_JP_S_Stone_Jizo_S: HouseNoDestruct
	{
		scope=1;
		displayName="Stone Jizo, small (0.45)";
		model="\JP\site\roadside\jp_s_stone_jizo_s.p3d";
	};
	class StaticObj_JP_S_Stone_Jizo_M: HouseNoDestruct
	{
		scope=1;
		displayName="Stone Jizo, standard (0.90)";
		model="\JP\site\roadside\jp_s_stone_jizo_m.p3d";
	};
	class StaticObj_JP_S_Stone_Jizo_L: HouseNoDestruct
	{
		scope=1;
		displayName="Stone Jizo, large on a lotus (1.36)";
		model="\JP\site\roadside\jp_s_stone_jizo_l.p3d";
	};
	class StaticObj_JP_S_Stone_Jizo_Halo: HouseNoDestruct
	{
		scope=1;
		displayName="Boat-halo Jizo stone (funagata)";
		model="\JP\site\roadside\jp_s_stone_jizo_halo.p3d";
	};
	class StaticObj_JP_S_Stone_Jizo_Bib: HouseNoDestruct
	{
		scope=1;
		displayName="Stone Jizo with a faded rag bib and cap";
		model="\JP\site\roadside\jp_s_stone_jizo_bib.p3d";
	};
	class StaticObj_JP_S_Stone_Jizo_Offer: HouseNoDestruct
	{
		scope=1;
		displayName="Stone Jizo with offerings (cup, stones, dead flowers)";
		model="\JP\site\roadside\jp_s_stone_jizo_offer.p3d";
	};
	class StaticObj_JP_S_Stone_Jizo_Ab_Tipped: HouseNoDestruct
	{
		scope=1;
		displayName="Stone Jizo toppled, head broken off";
		model="\JP\site\roadside\jp_s_stone_jizo_ab_tipped.p3d";
	};
	// jp_s_jizo_hut (roadside)
	class StaticObj_JP_S_Jizo_Hut_Box: HouseNoDestruct
	{
		scope=1;
		displayName="Jizo box (street corner), small Jizo inside";
		model="\JP\site\roadside\jp_s_jizo_hut_box.p3d";
	};
	class StaticObj_JP_S_Jizo_Hut_Hall: HouseNoDestruct
	{
		scope=1;
		displayName="Jizo hall, one ken, open front";
		model="\JP\site\roadside\jp_s_jizo_hut_hall.p3d";
	};
	class StaticObj_JP_S_Jizo_Hut_Stone_Roof: HouseNoDestruct
	{
		scope=1;
		displayName="Stone-roofed Jizo niche (mountain)";
		model="\JP\site\roadside\jp_s_jizo_hut_stone_roof.p3d";
	};
	class StaticObj_JP_S_Jizo_Hut_Ab_Open: HouseNoDestruct
	{
		scope=1;
		displayName="Jizo box, lattice door fallen, roof lifted";
		model="\JP\site\roadside\jp_s_jizo_hut_ab_open.p3d";
	};
	// jp_s_stele (roadside)
	class StaticObj_JP_S_Stele_Koshin: HouseNoDestruct
	{
		scope=1;
		displayName="Koshin pillar with Shomen Kongo relief";
		model="\JP\site\roadside\jp_s_stele_koshin.p3d";
	};
	class StaticObj_JP_S_Stele_Relief_Panel: HouseNoDestruct
	{
		scope=1;
		displayName="Bato Kannon relief panel";
		model="\JP\site\roadside\jp_s_stele_relief_panel.p3d";
	};
	class StaticObj_JP_S_Stele_Natural_Slab: HouseNoDestruct
	{
		scope=1;
		displayName="Natural slab with deep-cut characters";
		model="\JP\site\roadside\jp_s_stele_natural_slab.p3d";
	};
	class StaticObj_JP_S_Stele_Arched: HouseNoDestruct
	{
		scope=1;
		displayName="Arched-top nenbutsu stone";
		model="\JP\site\roadside\jp_s_stele_arched.p3d";
	};
	class StaticObj_JP_S_Stele_Pillar: HouseNoDestruct
	{
		scope=1;
		displayName="Direction / boundary post";
		model="\JP\site\roadside\jp_s_stele_pillar.p3d";
	};
	class StaticObj_JP_S_Stele_Round: HouseNoDestruct
	{
		scope=1;
		displayName="Round road-god stone (dosojin)";
		model="\JP\site\roadside\jp_s_stele_round.p3d";
	};
	class StaticObj_JP_S_Stele_Group3: HouseNoDestruct
	{
		scope=1;
		displayName="Three roadside stones on one base";
		model="\JP\site\roadside\jp_s_stele_group3.p3d";
	};
	class StaticObj_JP_S_Stele_Ab_Tipped: HouseNoDestruct
	{
		scope=1;
		displayName="Koshin pillar leaning and half sunk, lichen";
		model="\JP\site\roadside\jp_s_stele_ab_tipped.p3d";
	};
};
