// JP_Site - outdoor site objects (jp_s_*), stage S, B3b wave 1. Map objects: StaticObj_JP_S_<name>
// (HouseNoDestruct, scope 1, like vanilla StaticObj_Misc_*); the wells Land_JP_S_Well_* with a one-line
// script class 'extends Well' each (drink + wash hands + fill, exactly as vanilla Land_Misc_Well_Pump_*).
// Shop-front dressing is meant as proxies on shop buildings; it also has classes for loose placement.
// No vanilla change, no map dependency. GENERATED by japan_dev/spikes/B3b/build.py - edit the generator.
class CfgPatches
{
	class JP_Site
	{
		units[]={};
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"DZ_Data",
			"DZ_Scripts",
			"JP_Common"
		};
	};
};
class CfgMods
{
	class JP_Site
	{
		dir="Japan";
		picture="";
		action="";
		hideName=1;
		hidePicture=1;
		name="JP Site";
		credits="";
		author="japan_dev";
		authorID="0";
		version="0.1";
		extra=0;
		type="mod";
		dependencies[]={"World"};
		class defs
		{
			class worldScriptModule
			{
				value="";
				files[]={"JP/site/scripts/4_World"};
			};
		};
	};
};
class CfgVehicles
{
	class HouseNoDestruct;
	// jp_s_oke (yard)
	class StaticObj_JP_S_Oke_Tarai: HouseNoDestruct
	{
		scope=1;
		displayName="Wash tub (tarai), leaves inside";
		model="\JP\site\yard\jp_s_oke_tarai.p3d";
	};
	class StaticObj_JP_S_Oke_Teoke: HouseNoDestruct
	{
		scope=1;
		displayName="Hand bucket (teoke)";
		model="\JP\site\yard\jp_s_oke_teoke.p3d";
	};
	class StaticObj_JP_S_Oke_Ninai: HouseNoDestruct
	{
		scope=1;
		displayName="Carrying bucket (ninai-oke)";
		model="\JP\site\yard\jp_s_oke_ninai.p3d";
	};
	class StaticObj_JP_S_Oke_Taru_Lid: HouseNoDestruct
	{
		scope=1;
		displayName="Pickle barrel with lid and stone";
		model="\JP\site\yard\jp_s_oke_taru_lid.p3d";
	};
	class StaticObj_JP_S_Oke_Stake: HouseNoDestruct
	{
		scope=1;
		displayName="Bucket upside down on a stake (oke-hoshi)";
		model="\JP\site\yard\jp_s_oke_stake.p3d";
	};
	class StaticObj_JP_S_Oke_Ab_Tipped: HouseNoDestruct
	{
		scope=1;
		displayName="Barrel tipped over, hoop sprung";
		model="\JP\site\yard\jp_s_oke_ab_tipped.p3d";
	};
	class StaticObj_JP_S_Oke_Ab_Staves: HouseNoDestruct
	{
		scope=1;
		displayName="Tub collapsed into staves";
		model="\JP\site\yard\jp_s_oke_ab_staves.p3d";
	};
	// jp_s_fire_tub (water)
	class StaticObj_JP_S_Fire_Tub_Full: HouseNoDestruct
	{
		scope=1;
		displayName="Corner fire tub with a bucket pyramid";
		model="\JP\site\water\jp_s_fire_tub_full.p3d";
	};
	class StaticObj_JP_S_Fire_Tub_Open: HouseNoDestruct
	{
		scope=1;
		displayName="Fire tub, lid gone, three buckets down";
		model="\JP\site\water\jp_s_fire_tub_open.p3d";
	};
	class StaticObj_JP_S_Fire_Tub_Eave: HouseNoDestruct
	{
		scope=1;
		displayName="Fire bucket on an eave peg (building proxy)";
		model="\JP\site\water\jp_s_fire_tub_eave.p3d";
	};
	class StaticObj_JP_S_Fire_Tub_Rural: HouseNoDestruct
	{
		scope=1;
		displayName="Rain barrel under an eave (rural)";
		model="\JP\site\water\jp_s_fire_tub_rural.p3d";
	};
	class StaticObj_JP_S_Fire_Tub_Ab_Scattered: HouseNoDestruct
	{
		scope=1;
		displayName="Fire tub, pyramid collapsed, buckets scattered";
		model="\JP\site\water\jp_s_fire_tub_ab_scattered.p3d";
	};
	// jp_s_firewood_stack (yard)
	class StaticObj_JP_S_Firewood_Stack_Wall_1ken_H120: HouseNoDestruct
	{
		scope=1;
		displayName="Firewood stack on a wall, 1 ken x 1.2 m";
		model="\JP\site\yard\jp_s_firewood_stack_wall_1ken_h120.p3d";
	};
	class StaticObj_JP_S_Firewood_Stack_Wall_1ken_H180: HouseNoDestruct
	{
		scope=1;
		displayName="Firewood stack on a wall, 1 ken x 1.8 m";
		model="\JP\site\yard\jp_s_firewood_stack_wall_1ken_h180.p3d";
	};
	class StaticObj_JP_S_Firewood_Stack_Half: HouseNoDestruct
	{
		scope=1;
		displayName="Firewood stack end piece, half ken, stepped";
		model="\JP\site\yard\jp_s_firewood_stack_half.p3d";
	};
	class StaticObj_JP_S_Firewood_Stack_Free_Posts: HouseNoDestruct
	{
		scope=1;
		displayName="Firewood stack between two stakes, board cap";
		model="\JP\site\yard\jp_s_firewood_stack_free_posts.p3d";
	};
	class StaticObj_JP_S_Firewood_Stack_Bundle: HouseNoDestruct
	{
		scope=1;
		displayName="Brushwood bundle (soda) leaning on a wall";
		model="\JP\site\yard\jp_s_firewood_stack_bundle.p3d";
	};
	class StaticObj_JP_S_Firewood_Stack_Ab_Collapsed: HouseNoDestruct
	{
		scope=1;
		displayName="Firewood stack, one end slumped, spilled";
		model="\JP\site\yard\jp_s_firewood_stack_ab_collapsed.p3d";
	};
	// jp_s_bench (street)
	class StaticObj_JP_S_Bench_1ken: HouseNoDestruct
	{
		scope=1;
		displayName="Bench (endai), 1 ken";
		model="\JP\site\street\jp_s_bench_1ken.p3d";
	};
	class StaticObj_JP_S_Bench_Long: HouseNoDestruct
	{
		scope=1;
		displayName="Tea-stand bench, 1.5 ken";
		model="\JP\site\street\jp_s_bench_long.p3d";
	};
	class StaticObj_JP_S_Bench_Mat: HouseNoDestruct
	{
		scope=1;
		displayName="Bench with a rotted straw mat";
		model="\JP\site\street\jp_s_bench_mat.p3d";
	};
	class StaticObj_JP_S_Bench_Ab_Tipped: HouseNoDestruct
	{
		scope=1;
		displayName="Bench tipped on its side";
		model="\JP\site\street\jp_s_bench_ab_tipped.p3d";
	};
	class StaticObj_JP_S_Bench_Ab_Broken: HouseNoDestruct
	{
		scope=1;
		displayName="Bench, one leg frame collapsed";
		model="\JP\site\street\jp_s_bench_ab_broken.p3d";
	};
	// jp_s_laundry_pole (yard)
	class StaticObj_JP_S_Laundry_Pole_Forked: HouseNoDestruct
	{
		scope=1;
		displayName="Drying pole on forked posts";
		model="\JP\site\yard\jp_s_laundry_pole_forked.p3d";
	};
	class StaticObj_JP_S_Laundry_Pole_Crossed: HouseNoDestruct
	{
		scope=1;
		displayName="Drying pole on crossed stakes";
		model="\JP\site\yard\jp_s_laundry_pole_crossed.p3d";
	};
	class StaticObj_JP_S_Laundry_Pole_Load_Cloth: HouseNoDestruct
	{
		scope=1;
		displayName="Drying pole, faded kimono, one cloth fallen";
		model="\JP\site\yard\jp_s_laundry_pole_load_cloth.p3d";
	};
	class StaticObj_JP_S_Laundry_Pole_Load_Kaki: HouseNoDestruct
	{
		scope=1;
		displayName="Persimmons dried black on strings (autumn)";
		model="\JP\site\yard\jp_s_laundry_pole_load_kaki.p3d";
	};
	class StaticObj_JP_S_Laundry_Pole_Load_Daikon: HouseNoDestruct
	{
		scope=1;
		displayName="Daikon hung in pairs, shrivelled (autumn)";
		model="\JP\site\yard\jp_s_laundry_pole_load_daikon.p3d";
	};
	class StaticObj_JP_S_Laundry_Pole_Load_Net: HouseNoDestruct
	{
		scope=1;
		displayName="A small net draped on the pole (fishing village)";
		model="\JP\site\yard\jp_s_laundry_pole_load_net.p3d";
	};
	class StaticObj_JP_S_Laundry_Pole_Ab_Down: HouseNoDestruct
	{
		scope=1;
		displayName="Drying pole down, one post leaning";
		model="\JP\site\yard\jp_s_laundry_pole_ab_down.p3d";
	};
	// jp_s_tenbin (yard)
	class StaticObj_JP_S_Tenbin_Baskets: HouseNoDestruct
	{
		scope=1;
		displayName="Shoulder pole with two baskets";
		model="\JP\site\yard\jp_s_tenbin_baskets.p3d";
	};
	class StaticObj_JP_S_Tenbin_Buckets: HouseNoDestruct
	{
		scope=1;
		displayName="Shoulder pole with two buckets";
		model="\JP\site\yard\jp_s_tenbin_buckets.p3d";
	};
	class StaticObj_JP_S_Tenbin_Boxes: HouseNoDestruct
	{
		scope=1;
		displayName="Shoulder pole with peddler's boxes";
		model="\JP\site\yard\jp_s_tenbin_boxes.p3d";
	};
	class StaticObj_JP_S_Tenbin_Leaning: HouseNoDestruct
	{
		scope=1;
		displayName="Shoulder pole leaning on a wall";
		model="\JP\site\yard\jp_s_tenbin_leaning.p3d";
	};
	class StaticObj_JP_S_Tenbin_Ab_Dropped: HouseNoDestruct
	{
		scope=1;
		displayName="Shoulder pole dropped, basket overturned";
		model="\JP\site\yard\jp_s_tenbin_ab_dropped.p3d";
	};
	// jp_s_handcart (yard)
	class StaticObj_JP_S_Handcart_Empty: HouseNoDestruct
	{
		scope=1;
		displayName="Handcart (daihachi-guruma), handles down";
		model="\JP\site\yard\jp_s_handcart_empty.p3d";
	};
	class StaticObj_JP_S_Handcart_Load_Bales: HouseNoDestruct
	{
		scope=1;
		displayName="Handcart with rice bales roped on";
		model="\JP\site\yard\jp_s_handcart_load_bales.p3d";
	};
	class StaticObj_JP_S_Handcart_Load_Barrels: HouseNoDestruct
	{
		scope=1;
		displayName="Handcart with barrels";
		model="\JP\site\yard\jp_s_handcart_load_barrels.p3d";
	};
	class StaticObj_JP_S_Handcart_Small: HouseNoDestruct
	{
		scope=1;
		displayName="Small cart (niguruma)";
		model="\JP\site\yard\jp_s_handcart_small.p3d";
	};
	class StaticObj_JP_S_Handcart_Ab_Tipped: HouseNoDestruct
	{
		scope=1;
		displayName="Handcart tipped on its side, load spilled";
		model="\JP\site\yard\jp_s_handcart_ab_tipped.p3d";
	};
	class StaticObj_JP_S_Handcart_Ab_Broken: HouseNoDestruct
	{
		scope=1;
		displayName="Handcart with a broken wheel, bed down";
		model="\JP\site\yard\jp_s_handcart_ab_broken.p3d";
	};
	class StaticObj_JP_S_Handcart_Ab_Wreck: HouseNoDestruct
	{
		scope=1;
		displayName="Handcart wreck, wheels off, slats gone";
		model="\JP\site\yard\jp_s_handcart_ab_wreck.p3d";
	};
	// jp_s_well_tsurube (water)
	class Land_JP_S_Well_Tsurube_Curb_Tub: HouseNoDestruct
	{
		scope=1;
		displayName="Pulley well, round tub curb";
		model="\JP\site\water\jp_s_well_tsurube_curb_tub.p3d";
	};
	class Land_JP_S_Well_Tsurube_Curb_Igeta: HouseNoDestruct
	{
		scope=1;
		displayName="Pulley well, square igeta curb";
		model="\JP\site\water\jp_s_well_tsurube_curb_igeta.p3d";
	};
	class Land_JP_S_Well_Tsurube_Curb_Stone: HouseNoDestruct
	{
		scope=1;
		displayName="Pulley well, stone curb";
		model="\JP\site\water\jp_s_well_tsurube_curb_stone.p3d";
	};
	class Land_JP_S_Well_Tsurube_Roofed: HouseNoDestruct
	{
		scope=1;
		displayName="Roofed pulley well (dwelling 28)";
		model="\JP\site\water\jp_s_well_tsurube_roofed.p3d";
	};
	class Land_JP_S_Well_Tsurube_Lid: HouseNoDestruct
	{
		scope=1;
		displayName="Well curb with a board lid";
		model="\JP\site\water\jp_s_well_tsurube_lid.p3d";
	};
	class Land_JP_S_Well_Tsurube_Ab_Open: HouseNoDestruct
	{
		scope=1;
		displayName="Pulley well, rope rotted, lid askew";
		model="\JP\site\water\jp_s_well_tsurube_ab_open.p3d";
	};
	// jp_s_well_hanetsurube (water)
	class Land_JP_S_Well_Hanetsurube_Well: HouseNoDestruct
	{
		scope=1;
		displayName="Lever well (hanetsurube)";
		model="\JP\site\water\jp_s_well_hanetsurube_well.p3d";
	};
	class StaticObj_JP_S_Well_Hanetsurube_Field: HouseNoDestruct
	{
		scope=1;
		displayName="Field sweep over a ditch";
		model="\JP\site\water\jp_s_well_hanetsurube_field.p3d";
	};
	class Land_JP_S_Well_Hanetsurube_Ab_Down: HouseNoDestruct
	{
		scope=1;
		displayName="Lever well, lashing rotted, pole down";
		model="\JP\site\water\jp_s_well_hanetsurube_ab_down.p3d";
	};
	// jp_s_stone_jizo (roadside)
	class StaticObj_JP_S_Stone_Jizo_S: HouseNoDestruct
	{
		scope=1;
		displayName="Stone Jizo, small (0.45)";
		model="\JP\site\roadside\jp_s_stone_jizo_s.p3d";
	};
	class StaticObj_JP_S_Stone_Jizo_M: HouseNoDestruct
	{
		scope=1;
		displayName="Stone Jizo, standard (0.90)";
		model="\JP\site\roadside\jp_s_stone_jizo_m.p3d";
	};
	class StaticObj_JP_S_Stone_Jizo_L: HouseNoDestruct
	{
		scope=1;
		displayName="Stone Jizo, large on a lotus (1.36)";
		model="\JP\site\roadside\jp_s_stone_jizo_l.p3d";
	};
	class StaticObj_JP_S_Stone_Jizo_Halo: HouseNoDestruct
	{
		scope=1;
		displayName="Boat-halo Jizo stone (funagata)";
		model="\JP\site\roadside\jp_s_stone_jizo_halo.p3d";
	};
	class StaticObj_JP_S_Stone_Jizo_Bib: HouseNoDestruct
	{
		scope=1;
		displayName="Stone Jizo with a faded rag bib and cap";
		model="\JP\site\roadside\jp_s_stone_jizo_bib.p3d";
	};
	class StaticObj_JP_S_Stone_Jizo_Offer: HouseNoDestruct
	{
		scope=1;
		displayName="Stone Jizo with offerings (cup, stones, dead flowers)";
		model="\JP\site\roadside\jp_s_stone_jizo_offer.p3d";
	};
	class StaticObj_JP_S_Stone_Jizo_Ab_Tipped: HouseNoDestruct
	{
		scope=1;
		displayName="Stone Jizo toppled, head broken off";
		model="\JP\site\roadside\jp_s_stone_jizo_ab_tipped.p3d";
	};
	// jp_s_jizo_hut (roadside)
	class StaticObj_JP_S_Jizo_Hut_Box: HouseNoDestruct
	{
		scope=1;
		displayName="Jizo box (street corner), small Jizo inside";
		model="\JP\site\roadside\jp_s_jizo_hut_box.p3d";
	};
	class StaticObj_JP_S_Jizo_Hut_Hall: HouseNoDestruct
	{
		scope=1;
		displayName="Jizo hall, one ken, open front";
		model="\JP\site\roadside\jp_s_jizo_hut_hall.p3d";
	};
	class StaticObj_JP_S_Jizo_Hut_Stone_Roof: HouseNoDestruct
	{
		scope=1;
		displayName="Stone-roofed Jizo niche (mountain)";
		model="\JP\site\roadside\jp_s_jizo_hut_stone_roof.p3d";
	};
	class StaticObj_JP_S_Jizo_Hut_Ab_Open: HouseNoDestruct
	{
		scope=1;
		displayName="Jizo box, lattice door fallen, roof lifted";
		model="\JP\site\roadside\jp_s_jizo_hut_ab_open.p3d";
	};
	// jp_s_stele (roadside)
	class StaticObj_JP_S_Stele_Koshin: HouseNoDestruct
	{
		scope=1;
		displayName="Koshin pillar with Shomen Kongo relief";
		model="\JP\site\roadside\jp_s_stele_koshin.p3d";
	};
	class StaticObj_JP_S_Stele_Relief_Panel: HouseNoDestruct
	{
		scope=1;
		displayName="Bato Kannon relief panel";
		model="\JP\site\roadside\jp_s_stele_relief_panel.p3d";
	};
	class StaticObj_JP_S_Stele_Natural_Slab: HouseNoDestruct
	{
		scope=1;
		displayName="Natural slab with deep-cut characters";
		model="\JP\site\roadside\jp_s_stele_natural_slab.p3d";
	};
	class StaticObj_JP_S_Stele_Arched: HouseNoDestruct
	{
		scope=1;
		displayName="Arched-top nenbutsu stone";
		model="\JP\site\roadside\jp_s_stele_arched.p3d";
	};
	class StaticObj_JP_S_Stele_Pillar: HouseNoDestruct
	{
		scope=1;
		displayName="Direction / boundary post";
		model="\JP\site\roadside\jp_s_stele_pillar.p3d";
	};
	class StaticObj_JP_S_Stele_Round: HouseNoDestruct
	{
		scope=1;
		displayName="Round road-god stone (dosojin)";
		model="\JP\site\roadside\jp_s_stele_round.p3d";
	};
	class StaticObj_JP_S_Stele_Group3: HouseNoDestruct
	{
		scope=1;
		displayName="Three roadside stones on one base";
		model="\JP\site\roadside\jp_s_stele_group3.p3d";
	};
	class StaticObj_JP_S_Stele_Ab_Tipped: HouseNoDestruct
	{
		scope=1;
		displayName="Koshin pillar leaning and half sunk, lichen";
		model="\JP\site\roadside\jp_s_stele_ab_tipped.p3d";
	};
	// jp_s_gutter (street)
	class StaticObj_JP_S_Gutter_Stone_1ken: HouseNoDestruct
	{
		scope=1;
		displayName="Street gutter, stone-lined, 1 ken";
		model="\JP\site\street\jp_s_gutter_stone_1ken.p3d";
	};
	class StaticObj_JP_S_Gutter_Stone_Half: HouseNoDestruct
	{
		scope=1;
		displayName="Street gutter, stone-lined, half ken";
		model="\JP\site\street\jp_s_gutter_stone_half.p3d";
	};
	class StaticObj_JP_S_Gutter_Corner: HouseNoDestruct
	{
		scope=1;
		displayName="Street gutter, 90-degree corner";
		model="\JP\site\street\jp_s_gutter_corner.p3d";
	};
	class StaticObj_JP_S_Gutter_Slab: HouseNoDestruct
	{
		scope=1;
		displayName="Street gutter with a slab crossing (door)";
		model="\JP\site\street\jp_s_gutter_slab.p3d";
	};
	class StaticObj_JP_S_Gutter_Board_1ken: HouseNoDestruct
	{
		scope=1;
		displayName="Alley drain with dobu-ita covers, 1 ken";
		model="\JP\site\street\jp_s_gutter_board_1ken.p3d";
	};
	class StaticObj_JP_S_Gutter_Outfall: HouseNoDestruct
	{
		scope=1;
		displayName="Gutter outfall into a canal or ditch";
		model="\JP\site\street\jp_s_gutter_outfall.p3d";
	};
	class StaticObj_JP_S_Gutter_Earth_1ken: HouseNoDestruct
	{
		scope=1;
		displayName="Rural earth-banked gutter, field-stone edge";
		model="\JP\site\street\jp_s_gutter_earth_1ken.p3d";
	};
	class StaticObj_JP_S_Gutter_Ab_Silted: HouseNoDestruct
	{
		scope=1;
		displayName="Street gutter silted with leaves, a stone tipped in";
		model="\JP\site\street\jp_s_gutter_ab_silted.p3d";
	};
	// jp_s_shopfront (street)
	class StaticObj_JP_S_Shopfront_Noren_Long: HouseNoDestruct
	{
		scope=1;
		displayName="Long noren, 3 panels, shop mark";
		model="\JP\site\street\jp_s_shopfront_noren_long.p3d";
	};
	class StaticObj_JP_S_Shopfront_Noren_Half: HouseNoDestruct
	{
		scope=1;
		displayName="Half noren (eating house)";
		model="\JP\site\street\jp_s_shopfront_noren_half.p3d";
	};
	class StaticObj_JP_S_Shopfront_Mizuhiki: HouseNoDestruct
	{
		scope=1;
		displayName="Eave curtain (mizuhiki-noren), 1 ken";
		model="\JP\site\street\jp_s_shopfront_mizuhiki.p3d";
	};
	class StaticObj_JP_S_Shopfront_Sudare_Up: HouseNoDestruct
	{
		scope=1;
		displayName="Reed blind rolled up";
		model="\JP\site\street\jp_s_shopfront_sudare_up.p3d";
	};
	class StaticObj_JP_S_Shopfront_Sudare_Down: HouseNoDestruct
	{
		scope=1;
		displayName="Reed blind down, slumped and holed";
		model="\JP\site\street\jp_s_shopfront_sudare_down.p3d";
	};
	class StaticObj_JP_S_Shopfront_Kanban_Hang: HouseNoDestruct
	{
		scope=1;
		displayName="Hanging signboard (confectioner)";
		model="\JP\site\street\jp_s_shopfront_kanban_hang.p3d";
	};
	class StaticObj_JP_S_Shopfront_Kanban_Stand: HouseNoDestruct
	{
		scope=1;
		displayName="Standing signboard (soba)";
		model="\JP\site\street\jp_s_shopfront_kanban_stand.p3d";
	};
	class StaticObj_JP_S_Shopfront_Shape_Brush: HouseNoDestruct
	{
		scope=1;
		displayName="Shape sign: giant brush";
		model="\JP\site\street\jp_s_shopfront_shape_brush.p3d";
	};
	class StaticObj_JP_S_Shopfront_Shape_Geta: HouseNoDestruct
	{
		scope=1;
		displayName="Shape sign: geta";
		model="\JP\site\street\jp_s_shopfront_shape_geta.p3d";
	};
	class StaticObj_JP_S_Shopfront_Shape_Tabi: HouseNoDestruct
	{
		scope=1;
		displayName="Shape sign: tabi";
		model="\JP\site\street\jp_s_shopfront_shape_tabi.p3d";
	};
	class StaticObj_JP_S_Shopfront_Shape_Gourd: HouseNoDestruct
	{
		scope=1;
		displayName="Shape sign: medicine gourd";
		model="\JP\site\street\jp_s_shopfront_shape_gourd.p3d";
	};
	class StaticObj_JP_S_Shopfront_Shape_Umbrella: HouseNoDestruct
	{
		scope=1;
		displayName="Shape sign: umbrella";
		model="\JP\site\street\jp_s_shopfront_shape_umbrella.p3d";
	};
	class StaticObj_JP_S_Shopfront_Shape_Fan: HouseNoDestruct
	{
		scope=1;
		displayName="Shape sign: fan";
		model="\JP\site\street\jp_s_shopfront_shape_fan.p3d";
	};
	class StaticObj_JP_S_Shopfront_Ab_Noren_Torn: HouseNoDestruct
	{
		scope=1;
		displayName="Noren faded to grey-blue, a panel torn off";
		model="\JP\site\street\jp_s_shopfront_ab_noren_torn.p3d";
	};
	class StaticObj_JP_S_Shopfront_Ab_Fallen: HouseNoDestruct
	{
		scope=1;
		displayName="Noren pole dropped, noren heaped on the threshold";
		model="\JP\site\street\jp_s_shopfront_ab_fallen.p3d";
	};
	class StaticObj_JP_S_Shopfront_Ab_Kanban_Askew: HouseNoDestruct
	{
		scope=1;
		displayName="Hanging signboard hanging from one cord";
		model="\JP\site\street\jp_s_shopfront_ab_kanban_askew.p3d";
	};
	// jp_s_lantern_sign (street)
	class StaticObj_JP_S_Lantern_Sign_Chochin_Shop: HouseNoDestruct
	{
		scope=1;
		displayName="Shop lantern (sake)";
		model="\JP\site\street\jp_s_lantern_sign_chochin_shop.p3d";
	};
	class StaticObj_JP_S_Lantern_Sign_Chochin_Inn: HouseNoDestruct
	{
		scope=1;
		displayName="Inn lantern";
		model="\JP\site\street\jp_s_lantern_sign_chochin_inn.p3d";
	};
	class StaticObj_JP_S_Lantern_Sign_Chochin_Gate: HouseNoDestruct
	{
		scope=1;
		displayName="Ward-gate lantern (Honcho)";
		model="\JP\site\street\jp_s_lantern_sign_chochin_gate.p3d";
	};
	class StaticObj_JP_S_Lantern_Sign_Kake: HouseNoDestruct
	{
		scope=1;
		displayName="Hanging box sign lamp (kake-andon)";
		model="\JP\site\street\jp_s_lantern_sign_kake.p3d";
	};
	class StaticObj_JP_S_Lantern_Sign_Oki: HouseNoDestruct
	{
		scope=1;
		displayName="Standing sign lamp (oki-andon)";
		model="\JP\site\street\jp_s_lantern_sign_oki.p3d";
	};
	class StaticObj_JP_S_Lantern_Sign_Tsuji: HouseNoDestruct
	{
		scope=1;
		displayName="Crossroads lamp on a post (tsuji-andon)";
		model="\JP\site\street\jp_s_lantern_sign_tsuji.p3d";
	};
	class StaticObj_JP_S_Lantern_Sign_Ab_Torn: HouseNoDestruct
	{
		scope=1;
		displayName="Shop lantern, paper split and holed";
		model="\JP\site\street\jp_s_lantern_sign_ab_torn.p3d";
	};
	class StaticObj_JP_S_Lantern_Sign_Ab_Fallen: HouseNoDestruct
	{
		scope=1;
		displayName="Standing lamp tipped, a lantern crushed on the ground";
		model="\JP\site\street\jp_s_lantern_sign_ab_fallen.p3d";
	};
	// jp_s_nobori (street)
	class StaticObj_JP_S_Nobori_Shop: HouseNoDestruct
	{
		scope=1;
		displayName="Shop banner (soba) on a bamboo pole";
		model="\JP\site\street\jp_s_nobori_shop.p3d";
	};
	class StaticObj_JP_S_Nobori_Shrine: HouseNoDestruct
	{
		scope=1;
		displayName="Shrine dedication banners, a pair";
		model="\JP\site\street\jp_s_nobori_shrine.p3d";
	};
	class StaticObj_JP_S_Nobori_Socket_Stones: HouseNoDestruct
	{
		scope=1;
		displayName="Banner socket stones, banner taken down";
		model="\JP\site\street\jp_s_nobori_socket_stones.p3d";
	};
	class StaticObj_JP_S_Nobori_Ab_Tattered: HouseNoDestruct
	{
		scope=1;
		displayName="Banner shredded to a strip, pole leaning";
		model="\JP\site\street\jp_s_nobori_ab_tattered.p3d";
	};
	class StaticObj_JP_S_Nobori_Ab_Down: HouseNoDestruct
	{
		scope=1;
		displayName="Banner pole fallen across the approach";
		model="\JP\site\street\jp_s_nobori_ab_down.p3d";
	};
	// jp_s_stall (street)
	class StaticObj_JP_S_Stall_Reed: HouseNoDestruct
	{
		scope=1;
		displayName="Reed-screen stall with counter";
		model="\JP\site\street\jp_s_stall_reed.p3d";
	};
	class StaticObj_JP_S_Stall_Booth: HouseNoDestruct
	{
		scope=1;
		displayName="Plank booth (kake-mise)";
		model="\JP\site\street\jp_s_stall_booth.p3d";
	};
	class StaticObj_JP_S_Stall_Yatai: HouseNoDestruct
	{
		scope=1;
		displayName="Roofed street stall (yatai), no wheels";
		model="\JP\site\street\jp_s_stall_yatai.p3d";
	};
	class StaticObj_JP_S_Stall_Row3: HouseNoDestruct
	{
		scope=1;
		displayName="Three reed stalls (market row)";
		model="\JP\site\street\jp_s_stall_row3.p3d";
	};
	class StaticObj_JP_S_Stall_Ab_Collapsed: HouseNoDestruct
	{
		scope=1;
		displayName="Reed stall collapsed, mat fallen in";
		model="\JP\site\street\jp_s_stall_ab_collapsed.p3d";
	};
	class StaticObj_JP_S_Stall_Ab_Frame: HouseNoDestruct
	{
		scope=1;
		displayName="Bare stall frame, screens gone";
		model="\JP\site\street\jp_s_stall_ab_frame.p3d";
	};
	// jp_s_kosatsu (roadside)
	class StaticObj_JP_S_Kosatsu_Std: HouseNoDestruct
	{
		scope=1;
		displayName="Notice board (kosatsuba), post-town size";
		model="\JP\site\roadside\jp_s_kosatsu_std.p3d";
	};
	class StaticObj_JP_S_Kosatsu_Large: HouseNoDestruct
	{
		scope=1;
		displayName="Notice board, bridge-end size (Fuchu type)";
		model="\JP\site\roadside\jp_s_kosatsu_large.p3d";
	};
	class StaticObj_JP_S_Kosatsu_Forest: HouseNoDestruct
	{
		scope=1;
		displayName="Single roofed notice board (forest)";
		model="\JP\site\roadside\jp_s_kosatsu_forest.p3d";
	};
	class StaticObj_JP_S_Kosatsu_Ab_Boards_Down: HouseNoDestruct
	{
		scope=1;
		displayName="Notice board, two boards fallen, fence gaps";
		model="\JP\site\roadside\jp_s_kosatsu_ab_boards_down.p3d";
	};
	// jp_s_straw_stack (yard)
	class StaticObj_JP_S_Straw_Stack_Nio_Cyl: HouseNoDestruct
	{
		scope=1;
		displayName="Straw stack, cylinder with conical cap (Kinai)";
		model="\JP\site\yard\jp_s_straw_stack_nio_cyl.p3d";
	};
	class StaticObj_JP_S_Straw_Stack_Nio_Cone: HouseNoDestruct
	{
		scope=1;
		displayName="Straw stack, conical (Kanto)";
		model="\JP\site\yard\jp_s_straw_stack_nio_cone.p3d";
	};
	class StaticObj_JP_S_Straw_Stack_Stook: HouseNoDestruct
	{
		scope=1;
		displayName="Rice sheaves leaning in a stook";
		model="\JP\site\yard\jp_s_straw_stack_stook.p3d";
	};
	class StaticObj_JP_S_Straw_Stack_Bundle: HouseNoDestruct
	{
		scope=1;
		displayName="Tied straw bundle";
		model="\JP\site\yard\jp_s_straw_stack_bundle.p3d";
	};
	class StaticObj_JP_S_Straw_Stack_Tawara_Stack: HouseNoDestruct
	{
		scope=1;
		displayName="Rice bales stacked (5)";
		model="\JP\site\yard\jp_s_straw_stack_tawara_stack.p3d";
	};
	class StaticObj_JP_S_Straw_Stack_Ab_Slumped: HouseNoDestruct
	{
		scope=1;
		displayName="Straw stack slumped, cap blown off";
		model="\JP\site\yard\jp_s_straw_stack_ab_slumped.p3d";
	};
	// jp_s_shimenawa (roadside)
	class StaticObj_JP_S_Shimenawa_Len_1ken: HouseNoDestruct
	{
		scope=1;
		displayName="Straw rope with streamers, 1 ken";
		model="\JP\site\roadside\jp_s_shimenawa_len_1ken.p3d";
	};
	class StaticObj_JP_S_Shimenawa_Len_2ken: HouseNoDestruct
	{
		scope=1;
		displayName="Straw rope with streamers, 2 ken";
		model="\JP\site\roadside\jp_s_shimenawa_len_2ken.p3d";
	};
	class StaticObj_JP_S_Shimenawa_Wrap_D06: HouseNoDestruct
	{
		scope=1;
		displayName="Straw rope round a 0.6 m trunk";
		model="\JP\site\roadside\jp_s_shimenawa_wrap_d06.p3d";
	};
	class StaticObj_JP_S_Shimenawa_Wrap_D10: HouseNoDestruct
	{
		scope=1;
		displayName="Straw rope round a 1.0 m trunk";
		model="\JP\site\roadside\jp_s_shimenawa_wrap_d10.p3d";
	};
	class StaticObj_JP_S_Shimenawa_Wrap_D16: HouseNoDestruct
	{
		scope=1;
		displayName="Straw rope round a 1.6 m trunk (landmark tree)";
		model="\JP\site\roadside\jp_s_shimenawa_wrap_d16.p3d";
	};
	class StaticObj_JP_S_Shimenawa_Ab_Tattered: HouseNoDestruct
	{
		scope=1;
		displayName="Straw rope grey and frayed, one end dropped";
		model="\JP\site\roadside\jp_s_shimenawa_ab_tattered.p3d";
	};
	// jp_s_torii_wood (shrine)
	class StaticObj_JP_S_Torii_Wood_Shinmei: HouseNoDestruct
	{
		scope=1;
		displayName="Wooden torii, shinmei (straight), 1 ken";
		model="\JP\site\shrine\jp_s_torii_wood_shinmei.p3d";
	};
	class StaticObj_JP_S_Torii_Wood_Shinmei_Rope: HouseNoDestruct
	{
		scope=1;
		displayName="Wooden shinmei torii with a straw rope";
		model="\JP\site\shrine\jp_s_torii_wood_shinmei_rope.p3d";
	};
	class StaticObj_JP_S_Torii_Wood_Shinmei_Rope_Shide: HouseNoDestruct
	{
		scope=1;
		displayName="Wooden shinmei torii, straw rope and paper shide";
		model="\JP\site\shrine\jp_s_torii_wood_shinmei_rope_shide.p3d";
	};
	class StaticObj_JP_S_Torii_Wood_Shinmei_Moss: HouseNoDestruct
	{
		scope=1;
		displayName="Wooden shinmei torii, mossy (rural)";
		model="\JP\site\shrine\jp_s_torii_wood_shinmei_moss.p3d";
	};
	class StaticObj_JP_S_Torii_Wood_Shinmei_Moss_Rope: HouseNoDestruct
	{
		scope=1;
		displayName="Wooden shinmei torii, mossy, straw rope";
		model="\JP\site\shrine\jp_s_torii_wood_shinmei_moss_rope.p3d";
	};
	class StaticObj_JP_S_Torii_Wood_Shinmei_Moss_Rope_Shide: HouseNoDestruct
	{
		scope=1;
		displayName="Wooden shinmei torii, mossy, rope and shide";
		model="\JP\site\shrine\jp_s_torii_wood_shinmei_moss_rope_shide.p3d";
	};
	class StaticObj_JP_S_Torii_Wood_Myojin: HouseNoDestruct
	{
		scope=1;
		displayName="Wooden torii, myojin (upswept), 1.5 ken, plaque";
		model="\JP\site\shrine\jp_s_torii_wood_myojin.p3d";
	};
	class StaticObj_JP_S_Torii_Wood_Myojin_Rope: HouseNoDestruct
	{
		scope=1;
		displayName="Wooden myojin torii with a straw rope";
		model="\JP\site\shrine\jp_s_torii_wood_myojin_rope.p3d";
	};
	class StaticObj_JP_S_Torii_Wood_Myojin_Rope_Shide: HouseNoDestruct
	{
		scope=1;
		displayName="Wooden myojin torii, straw rope and paper shide";
		model="\JP\site\shrine\jp_s_torii_wood_myojin_rope_shide.p3d";
	};
	class StaticObj_JP_S_Torii_Wood_Myojin_Moss: HouseNoDestruct
	{
		scope=1;
		displayName="Wooden myojin torii, mossy (rural)";
		model="\JP\site\shrine\jp_s_torii_wood_myojin_moss.p3d";
	};
	class StaticObj_JP_S_Torii_Wood_Myojin_Moss_Rope: HouseNoDestruct
	{
		scope=1;
		displayName="Wooden myojin torii, mossy, rope";
		model="\JP\site\shrine\jp_s_torii_wood_myojin_moss_rope.p3d";
	};
	class StaticObj_JP_S_Torii_Wood_Myojin_Moss_Rope_Shide: HouseNoDestruct
	{
		scope=1;
		displayName="Wooden myojin torii, mossy, rope and shide";
		model="\JP\site\shrine\jp_s_torii_wood_myojin_moss_rope_shide.p3d";
	};
	class StaticObj_JP_S_Torii_Wood_Myojin_Shu: HouseNoDestruct
	{
		scope=1;
		displayName="Vermilion myojin torii, black kasagi (Inari / Hachiman only)";
		model="\JP\site\shrine\jp_s_torii_wood_myojin_shu.p3d";
	};
	class StaticObj_JP_S_Torii_Wood_Myojin_Shu_Rope_Shide: HouseNoDestruct
	{
		scope=1;
		displayName="Vermilion myojin torii with rope and shide (Inari / Hachiman only)";
		model="\JP\site\shrine\jp_s_torii_wood_myojin_shu_rope_shide.p3d";
	};
	class StaticObj_JP_S_Torii_Wood_Mini: HouseNoDestruct
	{
		scope=1;
		displayName="Miniature wooden torii (yard shrine)";
		model="\JP\site\shrine\jp_s_torii_wood_mini.p3d";
	};
	class StaticObj_JP_S_Torii_Wood_Mini_Shu: HouseNoDestruct
	{
		scope=1;
		displayName="Miniature vermilion torii (Inari yard shrine)";
		model="\JP\site\shrine\jp_s_torii_wood_mini_shu.p3d";
	};
	class StaticObj_JP_S_Torii_Wood_Mini_Rope: HouseNoDestruct
	{
		scope=1;
		displayName="Miniature torii with a straw rope and shide (yard shrine)";
		model="\JP\site\shrine\jp_s_torii_wood_mini_rope.p3d";
	};
	class StaticObj_JP_S_Torii_Wood_Ab_Leaning: HouseNoDestruct
	{
		scope=1;
		displayName="Wooden myojin torii leaning on a rotted post, rope dropped";
		model="\JP\site\shrine\jp_s_torii_wood_ab_leaning.p3d";
	};
	class StaticObj_JP_S_Torii_Wood_Ab_Leaning_Shu: HouseNoDestruct
	{
		scope=1;
		displayName="Vermilion torii peeled to grey, leaning, rope dropped";
		model="\JP\site\shrine\jp_s_torii_wood_ab_leaning_shu.p3d";
	};
	class StaticObj_JP_S_Torii_Wood_Ab_Rotted: HouseNoDestruct
	{
		scope=1;
		displayName="Wooden shinmei torii, kasagi slipped off one post, rope dropped";
		model="\JP\site\shrine\jp_s_torii_wood_ab_rotted.p3d";
	};
	// jp_s_torii_stone (shrine)
	class StaticObj_JP_S_Torii_Stone_S: HouseNoDestruct
	{
		scope=1;
		displayName="Stone torii, span 1.82 (village)";
		model="\JP\site\shrine\jp_s_torii_stone_s.p3d";
	};
	class StaticObj_JP_S_Torii_Stone_S_Rope: HouseNoDestruct
	{
		scope=1;
		displayName="Stone torii 1.82 with a straw rope";
		model="\JP\site\shrine\jp_s_torii_stone_s_rope.p3d";
	};
	class StaticObj_JP_S_Torii_Stone_S_Rope_Shide: HouseNoDestruct
	{
		scope=1;
		displayName="Stone torii 1.82, straw rope and shide";
		model="\JP\site\shrine\jp_s_torii_stone_s_rope_shide.p3d";
	};
	class StaticObj_JP_S_Torii_Stone_S_Moss: HouseNoDestruct
	{
		scope=1;
		displayName="Stone torii 1.82, mossy (rural)";
		model="\JP\site\shrine\jp_s_torii_stone_s_moss.p3d";
	};
	class StaticObj_JP_S_Torii_Stone_S_Moss_Rope_Shide: HouseNoDestruct
	{
		scope=1;
		displayName="Stone torii 1.82, mossy, rope and shide";
		model="\JP\site\shrine\jp_s_torii_stone_s_moss_rope_shide.p3d";
	};
	class StaticObj_JP_S_Torii_Stone_M: HouseNoDestruct
	{
		scope=1;
		displayName="Stone torii, span 2.5";
		model="\JP\site\shrine\jp_s_torii_stone_m.p3d";
	};
	class StaticObj_JP_S_Torii_Stone_M_Rope_Shide: HouseNoDestruct
	{
		scope=1;
		displayName="Stone torii 2.5, straw rope and shide";
		model="\JP\site\shrine\jp_s_torii_stone_m_rope_shide.p3d";
	};
	class StaticObj_JP_S_Torii_Stone_L: HouseNoDestruct
	{
		scope=1;
		displayName="Stone torii, span 3.6 (town)";
		model="\JP\site\shrine\jp_s_torii_stone_l.p3d";
	};
	class StaticObj_JP_S_Torii_Stone_L_Rope_Shide: HouseNoDestruct
	{
		scope=1;
		displayName="Stone torii 3.6, straw rope and shide";
		model="\JP\site\shrine\jp_s_torii_stone_l_rope_shide.p3d";
	};
	class StaticObj_JP_S_Torii_Stone_Ab_Broken: HouseNoDestruct
	{
		scope=1;
		displayName="Stone torii, kasagi fallen in two pieces (quake)";
		model="\JP\site\shrine\jp_s_torii_stone_ab_broken.p3d";
	};
	// jp_s_stone_lantern (shrine)
	class StaticObj_JP_S_Stone_Lantern_Kasuga_18: HouseNoDestruct
	{
		scope=1;
		displayName="Stone lantern, Kasuga 1.8";
		model="\JP\site\shrine\jp_s_stone_lantern_kasuga_18.p3d";
	};
	class StaticObj_JP_S_Stone_Lantern_Kasuga_24: HouseNoDestruct
	{
		scope=1;
		displayName="Stone lantern, Kasuga 2.4";
		model="\JP\site\shrine\jp_s_stone_lantern_kasuga_24.p3d";
	};
	class StaticObj_JP_S_Stone_Lantern_Kasuga_30: HouseNoDestruct
	{
		scope=1;
		displayName="Stone lantern, Kasuga 3.0";
		model="\JP\site\shrine\jp_s_stone_lantern_kasuga_30.p3d";
	};
	class StaticObj_JP_S_Stone_Lantern_Square_24: HouseNoDestruct
	{
		scope=1;
		displayName="Stone lantern, square standing 2.4";
		model="\JP\site\shrine\jp_s_stone_lantern_square_24.p3d";
	};
	class StaticObj_JP_S_Stone_Lantern_Oki: HouseNoDestruct
	{
		scope=1;
		displayName="Small placed stone lantern (oki-doro)";
		model="\JP\site\shrine\jp_s_stone_lantern_oki.p3d";
	};
	class StaticObj_JP_S_Stone_Lantern_Joyato: HouseNoDestruct
	{
		scope=1;
		displayName="Always-lit lantern (joyato) on a two-step base, 4.0";
		model="\JP\site\shrine\jp_s_stone_lantern_joyato.p3d";
	};
	class StaticObj_JP_S_Stone_Lantern_Kasuga_18_Moss: HouseNoDestruct
	{
		scope=1;
		displayName="Stone lantern, Kasuga 1.8, mossy";
		model="\JP\site\shrine\jp_s_stone_lantern_kasuga_18_moss.p3d";
	};
	class StaticObj_JP_S_Stone_Lantern_Kasuga_24_Moss: HouseNoDestruct
	{
		scope=1;
		displayName="Stone lantern, Kasuga 2.4, mossy";
		model="\JP\site\shrine\jp_s_stone_lantern_kasuga_24_moss.p3d";
	};
	class StaticObj_JP_S_Stone_Lantern_Kasuga_30_Moss: HouseNoDestruct
	{
		scope=1;
		displayName="Stone lantern, Kasuga 3.0, mossy";
		model="\JP\site\shrine\jp_s_stone_lantern_kasuga_30_moss.p3d";
	};
	class StaticObj_JP_S_Stone_Lantern_Square_24_Moss: HouseNoDestruct
	{
		scope=1;
		displayName="Stone lantern, square 2.4, mossy";
		model="\JP\site\shrine\jp_s_stone_lantern_square_24_moss.p3d";
	};
	class StaticObj_JP_S_Stone_Lantern_Oki_Moss: HouseNoDestruct
	{
		scope=1;
		displayName="Small placed stone lantern, mossy";
		model="\JP\site\shrine\jp_s_stone_lantern_oki_moss.p3d";
	};
	class StaticObj_JP_S_Stone_Lantern_Ab_Toppled: HouseNoDestruct
	{
		scope=1;
		displayName="Kasuga lantern, roof and jewel fallen (quake)";
		model="\JP\site\shrine\jp_s_stone_lantern_ab_toppled.p3d";
	};
	class StaticObj_JP_S_Stone_Lantern_Ab_Hoju_Moss: HouseNoDestruct
	{
		scope=1;
		displayName="Kasuga lantern 1.8, mossy, jewel fallen";
		model="\JP\site\shrine\jp_s_stone_lantern_ab_hoju_moss.p3d";
	};
	// jp_s_chozubachi (shrine)
	class StaticObj_JP_S_Chozubachi_Small: HouseNoDestruct
	{
		scope=1;
		displayName="Stone basin, Tenna 2 (1682) size, on a plinth stone";
		model="\JP\site\shrine\jp_s_chozubachi_small.p3d";
	};
	class StaticObj_JP_S_Chozubachi_Large: HouseNoDestruct
	{
		scope=1;
		displayName="Stone basin, long (town shrine)";
		model="\JP\site\shrine\jp_s_chozubachi_large.p3d";
	};
	class StaticObj_JP_S_Chozubachi_Natural: HouseNoDestruct
	{
		scope=1;
		displayName="Natural stone basin with a cut hollow (mountain shrine)";
		model="\JP\site\shrine\jp_s_chozubachi_natural.p3d";
	};
	class StaticObj_JP_S_Chozubachi_Ab_Dry: HouseNoDestruct
	{
		scope=1;
		displayName="Stone basin, dry and leaf-filled, ladles fallen";
		model="\JP\site\shrine\jp_s_chozubachi_ab_dry.p3d";
	};
	// jp_s_stone_steps (shrine)
	class StaticObj_JP_S_Stone_Steps_Dressed_3: HouseNoDestruct
	{
		scope=1;
		displayName="Stone steps, dressed, 3 steps, 1 ken wide";
		model="\JP\site\shrine\jp_s_stone_steps_dressed_3.p3d";
	};
	class StaticObj_JP_S_Stone_Steps_Dressed_6: HouseNoDestruct
	{
		scope=1;
		displayName="Stone steps, dressed, 6 steps, 1 ken wide";
		model="\JP\site\shrine\jp_s_stone_steps_dressed_6.p3d";
	};
	class StaticObj_JP_S_Stone_Steps_Dressed_3_Wide: HouseNoDestruct
	{
		scope=1;
		displayName="Stone steps, dressed, 3 steps, 1.5 ken wide";
		model="\JP\site\shrine\jp_s_stone_steps_dressed_3_wide.p3d";
	};
	class StaticObj_JP_S_Stone_Steps_Dressed_6_Wide: HouseNoDestruct
	{
		scope=1;
		displayName="Stone steps, dressed, 6 steps, 1.5 ken wide";
		model="\JP\site\shrine\jp_s_stone_steps_dressed_6_wide.p3d";
	};
	class StaticObj_JP_S_Stone_Steps_Dressed_3_Narrow: HouseNoDestruct
	{
		scope=1;
		displayName="Stone steps, dressed, 3 steps, half ken wide";
		model="\JP\site\shrine\jp_s_stone_steps_dressed_3_narrow.p3d";
	};
	class StaticObj_JP_S_Stone_Steps_Rough_3: HouseNoDestruct
	{
		scope=1;
		displayName="Stone steps, rough field stones, 3 steps, 1 ken wide";
		model="\JP\site\shrine\jp_s_stone_steps_rough_3.p3d";
	};
	class StaticObj_JP_S_Stone_Steps_Rough_3_Narrow: HouseNoDestruct
	{
		scope=1;
		displayName="Stone steps, rough field stones, half ken wide";
		model="\JP\site\shrine\jp_s_stone_steps_rough_3_narrow.p3d";
	};
	class StaticObj_JP_S_Stone_Steps_Landing: HouseNoDestruct
	{
		scope=1;
		displayName="Stone landing slab course, 1 ken square";
		model="\JP\site\shrine\jp_s_stone_steps_landing.p3d";
	};
	class StaticObj_JP_S_Stone_Steps_Landing_Wide: HouseNoDestruct
	{
		scope=1;
		displayName="Stone landing, 1.5 ken wide, 1 ken deep";
		model="\JP\site\shrine\jp_s_stone_steps_landing_wide.p3d";
	};
	class StaticObj_JP_S_Stone_Steps_Cheek_3: HouseNoDestruct
	{
		scope=1;
		displayName="Side cheek stone for a 3-step flight";
		model="\JP\site\shrine\jp_s_stone_steps_cheek_3.p3d";
	};
	class StaticObj_JP_S_Stone_Steps_Cheek_6: HouseNoDestruct
	{
		scope=1;
		displayName="Side cheek stone for a 6-step flight";
		model="\JP\site\shrine\jp_s_stone_steps_cheek_6.p3d";
	};
	class StaticObj_JP_S_Stone_Steps_Ab_Heaved: HouseNoDestruct
	{
		scope=1;
		displayName="Stone steps heaved by roots, one step missing";
		model="\JP\site\shrine\jp_s_stone_steps_ab_heaved.p3d";
	};
	class StaticObj_JP_S_Stone_Steps_Ab_Heaved_Rough: HouseNoDestruct
	{
		scope=1;
		displayName="Rough stone steps, heaved, leaves drifted";
		model="\JP\site\shrine\jp_s_stone_steps_ab_heaved_rough.p3d";
	};
	// jp_s_grave_stones (grave)
	class StaticObj_JP_S_Grave_Stones_Board: HouseNoDestruct
	{
		scope=1;
		displayName="Board-shaped gravestone (itabi) on a base, name and date";
		model="\JP\site\grave\jp_s_grave_stones_board.p3d";
	};
	class StaticObj_JP_S_Grave_Stones_Board_S: HouseNoDestruct
	{
		scope=1;
		displayName="Small board-shaped gravestone set in the ground, name only";
		model="\JP\site\grave\jp_s_grave_stones_board_s.p3d";
	};
	class StaticObj_JP_S_Grave_Stones_Board_Tall_Moss: HouseNoDestruct
	{
		scope=1;
		displayName="Tall board-shaped gravestone on two bases, mossy";
		model="\JP\site\grave\jp_s_grave_stones_board_tall_moss.p3d";
	};
	class StaticObj_JP_S_Grave_Stones_Boat_Halo: HouseNoDestruct
	{
		scope=1;
		displayName="Boat-halo gravestone with a Jizo in relief";
		model="\JP\site\grave\jp_s_grave_stones_boat_halo.p3d";
	};
	class StaticObj_JP_S_Grave_Stones_Boat_Halo_Child: HouseNoDestruct
	{
		scope=1;
		displayName="Small boat-halo stone (a child's grave), no inscription";
		model="\JP\site\grave\jp_s_grave_stones_boat_halo_child.p3d";
	};
	class StaticObj_JP_S_Grave_Stones_Round: HouseNoDestruct
	{
		scope=1;
		displayName="Round-headed gravestone (kushigata) on a base";
		model="\JP\site\grave\jp_s_grave_stones_round.p3d";
	};
	class StaticObj_JP_S_Grave_Stones_Round_S_Plain: HouseNoDestruct
	{
		scope=1;
		displayName="Small round-headed stone, plain";
		model="\JP\site\grave\jp_s_grave_stones_round_s_plain.p3d";
	};
	class StaticObj_JP_S_Grave_Stones_Pillar: HouseNoDestruct
	{
		scope=1;
		displayName="Square-pillar gravestone on three bases (rare in 1730)";
		model="\JP\site\grave\jp_s_grave_stones_pillar.p3d";
	};
	class StaticObj_JP_S_Grave_Stones_Pillar_Pointed: HouseNoDestruct
	{
		scope=1;
		displayName="Square pillar with a pointed top (new Kyoho fashion, rare)";
		model="\JP\site\grave\jp_s_grave_stones_pillar_pointed.p3d";
	};
	class StaticObj_JP_S_Grave_Stones_Gorinto_S: HouseNoDestruct
	{
		scope=1;
		displayName="Five-ring stupa (gorinto), 0.6";
		model="\JP\site\grave\jp_s_grave_stones_gorinto_s.p3d";
	};
	class StaticObj_JP_S_Grave_Stones_Gorinto_L: HouseNoDestruct
	{
		scope=1;
		displayName="Large five-ring stupa on a platform, 2.0 (samurai / priest)";
		model="\JP\site\grave\jp_s_grave_stones_gorinto_l.p3d";
	};
	class StaticObj_JP_S_Grave_Stones_Gorinto_Stack: HouseNoDestruct
	{
		scope=1;
		displayName="Gorinto re-stacked from two stupas, crescent missing";
		model="\JP\site\grave\jp_s_grave_stones_gorinto_stack.p3d";
	};
	class StaticObj_JP_S_Grave_Stones_Gorinto_Heap: HouseNoDestruct
	{
		scope=1;
		displayName="A small heap of old gorinto fragments at a plot corner";
		model="\JP\site\grave\jp_s_grave_stones_gorinto_heap.p3d";
	};
	class StaticObj_JP_S_Grave_Stones_Hokyointo: HouseNoDestruct
	{
		scope=1;
		displayName="Hokyointo (treasure-seal stupa), 1.5";
		model="\JP\site\grave\jp_s_grave_stones_hokyointo.p3d";
	};
	class StaticObj_JP_S_Grave_Stones_Jizo_Child: HouseNoDestruct
	{
		scope=1;
		displayName="Small Jizo on a base (a child's grave), faded bib";
		model="\JP\site\grave\jp_s_grave_stones_jizo_child.p3d";
	};
	class StaticObj_JP_S_Grave_Stones_Field: HouseNoDestruct
	{
		scope=1;
		displayName="Field stone as a grave marker (poor grave)";
		model="\JP\site\grave\jp_s_grave_stones_field.p3d";
	};
	class StaticObj_JP_S_Grave_Stones_Field_Mound: HouseNoDestruct
	{
		scope=1;
		displayName="Earth grave mound with a field stone at its head";
		model="\JP\site\grave\jp_s_grave_stones_field_mound.p3d";
	};
	class StaticObj_JP_S_Grave_Stones_Field_Pair: HouseNoDestruct
	{
		scope=1;
		displayName="Two small field stones (a couple's poor grave)";
		model="\JP\site\grave\jp_s_grave_stones_field_pair.p3d";
	};
	class StaticObj_JP_S_Grave_Stones_Ab_Leaning: HouseNoDestruct
	{
		scope=1;
		displayName="Board-shaped gravestone leaning and sunk";
		model="\JP\site\grave\jp_s_grave_stones_ab_leaning.p3d";
	};
	class StaticObj_JP_S_Grave_Stones_Ab_Board_Broken: HouseNoDestruct
	{
		scope=1;
		displayName="Board-shaped gravestone, gable snapped off and lying in front";
		model="\JP\site\grave\jp_s_grave_stones_ab_board_broken.p3d";
	};
	class StaticObj_JP_S_Grave_Stones_Ab_Boat_Halo_Sunk: HouseNoDestruct
	{
		scope=1;
		displayName="Boat-halo gravestone leaning forward, half sunk, mossy";
		model="\JP\site\grave\jp_s_grave_stones_ab_boat_halo_sunk.p3d";
	};
	class StaticObj_JP_S_Grave_Stones_Ab_Round_Lean: HouseNoDestruct
	{
		scope=1;
		displayName="Round-headed gravestone leaning sideways";
		model="\JP\site\grave\jp_s_grave_stones_ab_round_lean.p3d";
	};
	class StaticObj_JP_S_Grave_Stones_Ab_Gorinto_Fallen: HouseNoDestruct
	{
		scope=1;
		displayName="Gorinto with roof, crescent and jewel fallen (quake)";
		model="\JP\site\grave\jp_s_grave_stones_ab_gorinto_fallen.p3d";
	};
	class StaticObj_JP_S_Grave_Stones_Ab_Hokyointo_Broken: HouseNoDestruct
	{
		scope=1;
		displayName="Hokyointo, finial and one horn fallen";
		model="\JP\site\grave\jp_s_grave_stones_ab_hokyointo_broken.p3d";
	};
	// jp_s_grave_wood (grave)
	class StaticObj_JP_S_Grave_Wood_Sotoba_X3: HouseNoDestruct
	{
		scope=1;
		displayName="Three sotoba slats behind a stone";
		model="\JP\site\grave\jp_s_grave_wood_sotoba_x3.p3d";
	};
	class StaticObj_JP_S_Grave_Wood_Rack: HouseNoDestruct
	{
		scope=1;
		displayName="Sotoba rack with leaning slats";
		model="\JP\site\grave\jp_s_grave_wood_rack.p3d";
	};
	class StaticObj_JP_S_Grave_Wood_Tubes: HouseNoDestruct
	{
		scope=1;
		displayName="Bamboo flower tubes in a stone, dead stems";
		model="\JP\site\grave\jp_s_grave_wood_tubes.p3d";
	};
	class StaticObj_JP_S_Grave_Wood_Incense: HouseNoDestruct
	{
		scope=1;
		displayName="Stone incense stand with ash";
		model="\JP\site\grave\jp_s_grave_wood_incense.p3d";
	};
	class StaticObj_JP_S_Grave_Wood_Bucket_Rack: HouseNoDestruct
	{
		scope=1;
		displayName="Bucket and ladle rack (teoke-kake)";
		model="\JP\site\grave\jp_s_grave_wood_bucket_rack.p3d";
	};
	class StaticObj_JP_S_Grave_Wood_Bohyo: HouseNoDestruct
	{
		scope=1;
		displayName="Wooden grave post on an earth mound";
		model="\JP\site\grave\jp_s_grave_wood_bohyo.p3d";
	};
	class StaticObj_JP_S_Grave_Wood_Bohyo_New: HouseNoDestruct
	{
		scope=1;
		displayName="Fresh wooden grave post, tall, on a new high mound";
		model="\JP\site\grave\jp_s_grave_wood_bohyo_new.p3d";
	};
	class StaticObj_JP_S_Grave_Wood_Bohyo_S: HouseNoDestruct
	{
		scope=1;
		displayName="Small silver-grey grave post (child or very poor grave)";
		model="\JP\site\grave\jp_s_grave_wood_bohyo_s.p3d";
	};
	class StaticObj_JP_S_Grave_Wood_Bohyo_Roof: HouseNoDestruct
	{
		scope=1;
		displayName="Wooden grave post with a small gabled cap (kasa-toba)";
		model="\JP\site\grave\jp_s_grave_wood_bohyo_roof.p3d";
	};
	class StaticObj_JP_S_Grave_Wood_Ab_Fallen: HouseNoDestruct
	{
		scope=1;
		displayName="Sotoba slats fallen and split, flower tube knocked over";
		model="\JP\site\grave\jp_s_grave_wood_ab_fallen.p3d";
	};
	class StaticObj_JP_S_Grave_Wood_Ab_Bohyo_Lean: HouseNoDestruct
	{
		scope=1;
		displayName="Grey grave post leaning hard, mound slumped";
		model="\JP\site\grave\jp_s_grave_wood_ab_bohyo_lean.p3d";
	};
	class StaticObj_JP_S_Grave_Wood_Ab_Bohyo_Split: HouseNoDestruct
	{
		scope=1;
		displayName="Black rotting grave post, top split apart";
		model="\JP\site\grave\jp_s_grave_wood_ab_bohyo_split.p3d";
	};
	class StaticObj_JP_S_Grave_Wood_Ab_Bohyo_Rotted: HouseNoDestruct
	{
		scope=1;
		displayName="Sunken grave mound, post rotted to a stump";
		model="\JP\site\grave\jp_s_grave_wood_ab_bohyo_rotted.p3d";
	};
	// jp_s_hasa (yard_life)
	class StaticObj_JP_S_Hasa_Low: HouseNoDestruct
	{
		scope=1;
		displayName="Rice drying rack on crossed stakes, hung with sheaves";
		model="\JP\site\yard_life\jp_s_hasa_low.p3d";
	};
	class StaticObj_JP_S_Hasa_Tiers: HouseNoDestruct
	{
		scope=1;
		displayName="Tiered rice drying rack, three rails of sheaves";
		model="\JP\site\yard_life\jp_s_hasa_tiers.p3d";
	};
	class StaticObj_JP_S_Hasa_Empty: HouseNoDestruct
	{
		scope=1;
		displayName="Tiered rice drying rack, empty";
		model="\JP\site\yard_life\jp_s_hasa_empty.p3d";
	};
	class StaticObj_JP_S_Hasa_Ab_Sagged: HouseNoDestruct
	{
		scope=1;
		displayName="Rice drying rack, one stake pair leaning, rail sagged, sheaves grey and fallen";
		model="\JP\site\yard_life\jp_s_hasa_ab_sagged.p3d";
	};
	class StaticObj_JP_S_Hasa_Ab_Collapsed: HouseNoDestruct
	{
		scope=1;
		displayName="Rice drying rack blown down, sheaves in heaps";
		model="\JP\site\yard_life\jp_s_hasa_ab_collapsed.p3d";
	};
	// jp_s_kaki_curtain (yard_life)
	class StaticObj_JP_S_Kaki_Curtain_1ken: HouseNoDestruct
	{
		scope=1;
		displayName="Persimmon curtain under the eaves, six strings";
		model="\JP\site\yard_life\jp_s_kaki_curtain_1ken.p3d";
	};
	class StaticObj_JP_S_Kaki_Curtain_Half: HouseNoDestruct
	{
		scope=1;
		displayName="Persimmon curtain, three strings";
		model="\JP\site\yard_life\jp_s_kaki_curtain_half.p3d";
	};
	class StaticObj_JP_S_Kaki_Curtain_Ab_Fallen: HouseNoDestruct
	{
		scope=1;
		displayName="Persimmon curtain fallen, fruit black on the ground";
		model="\JP\site\yard_life\jp_s_kaki_curtain_ab_fallen.p3d";
	};
	// jp_s_tsukimi (yard_life)
	class StaticObj_JP_S_Tsukimi_Stand: HouseNoDestruct
	{
		scope=1;
		displayName="Moon-viewing offering: dango on a stand, pampas grass";
		model="\JP\site\yard_life\jp_s_tsukimi_stand.p3d";
	};
	class StaticObj_JP_S_Tsukimi_Ab_Dried: HouseNoDestruct
	{
		scope=1;
		displayName="Moon-viewing offering, dango mouldy and pecked, grass snapped";
		model="\JP\site\yard_life\jp_s_tsukimi_ab_dried.p3d";
	};
	class StaticObj_JP_S_Tsukimi_Ab_Tipped: HouseNoDestruct
	{
		scope=1;
		displayName="Moon-viewing stand knocked over, dango scattered";
		model="\JP\site\yard_life\jp_s_tsukimi_ab_tipped.p3d";
	};
	// jp_s_scarecrow (yard_life)
	class StaticObj_JP_S_Scarecrow_Kasa: HouseNoDestruct
	{
		scope=1;
		displayName="Scarecrow in a sedge hat and straw cape";
		model="\JP\site\yard_life\jp_s_scarecrow_kasa.p3d";
	};
	class StaticObj_JP_S_Scarecrow_Naruko: HouseNoDestruct
	{
		scope=1;
		displayName="Bird clappers on a rope between stakes";
		model="\JP\site\yard_life\jp_s_scarecrow_naruko.p3d";
	};
	class StaticObj_JP_S_Scarecrow_Ab_Leaning: HouseNoDestruct
	{
		scope=1;
		displayName="Scarecrow leaning, hat blown off";
		model="\JP\site\yard_life\jp_s_scarecrow_ab_leaning.p3d";
	};
	class StaticObj_JP_S_Scarecrow_Ab_Down: HouseNoDestruct
	{
		scope=1;
		displayName="Scarecrow fallen face down in the stubble";
		model="\JP\site\yard_life\jp_s_scarecrow_ab_down.p3d";
	};
	// jp_s_farm_tools (yard_life)
	class StaticObj_JP_S_Farm_Tools_Lean: HouseNoDestruct
	{
		scope=1;
		displayName="Farm tools leaned on a wall: hoe, rake, flail, sickle";
		model="\JP\site\yard_life\jp_s_farm_tools_lean.p3d";
	};
	class StaticObj_JP_S_Farm_Tools_Pair: HouseNoDestruct
	{
		scope=1;
		displayName="Hoe and rake leaned on a wall";
		model="\JP\site\yard_life\jp_s_farm_tools_pair.p3d";
	};
	class StaticObj_JP_S_Farm_Tools_Ab_Fallen: HouseNoDestruct
	{
		scope=1;
		displayName="Farm tools slid down into the leaves, rusted";
		model="\JP\site\yard_life\jp_s_farm_tools_ab_fallen.p3d";
	};
	// jp_s_leaf_pile (yard_life)
	class StaticObj_JP_S_Leaf_Pile_Broom: HouseNoDestruct
	{
		scope=1;
		displayName="Raked leaf pile with a bamboo broom";
		model="\JP\site\yard_life\jp_s_leaf_pile_broom.p3d";
	};
	class StaticObj_JP_S_Leaf_Pile_Small: HouseNoDestruct
	{
		scope=1;
		displayName="Raked leaf pile";
		model="\JP\site\yard_life\jp_s_leaf_pile_small.p3d";
	};
	class StaticObj_JP_S_Leaf_Pile_Ab_Scattered: HouseNoDestruct
	{
		scope=1;
		displayName="Leaf pile spread by the wind, broom fallen";
		model="\JP\site\yard_life\jp_s_leaf_pile_ab_scattered.p3d";
	};
	// jp_s_ladder (yard_life)
	class StaticObj_JP_S_Ladder_Lean: HouseNoDestruct
	{
		scope=1;
		displayName="Wooden ladder leaned against the eaves";
		model="\JP\site\yard_life\jp_s_ladder_lean.p3d";
	};
	class StaticObj_JP_S_Ladder_Bamboo: HouseNoDestruct
	{
		scope=1;
		displayName="Bamboo ladder leaned against the eaves";
		model="\JP\site\yard_life\jp_s_ladder_bamboo.p3d";
	};
	class StaticObj_JP_S_Ladder_Ab_Fallen: HouseNoDestruct
	{
		scope=1;
		displayName="Ladder fallen on the ground, rungs broken";
		model="\JP\site\yard_life\jp_s_ladder_ab_fallen.p3d";
	};
	// jp_s_charcoal_bales (yard_life)
	class StaticObj_JP_S_Charcoal_Bales_Stack: HouseNoDestruct
	{
		scope=1;
		displayName="Charcoal bales stacked by a door";
		model="\JP\site\yard_life\jp_s_charcoal_bales_stack.p3d";
	};
	class StaticObj_JP_S_Charcoal_Bales_Row2: HouseNoDestruct
	{
		scope=1;
		displayName="Two charcoal bales against a wall";
		model="\JP\site\yard_life\jp_s_charcoal_bales_row2.p3d";
	};
	class StaticObj_JP_S_Charcoal_Bales_Ab_Burst: HouseNoDestruct
	{
		scope=1;
		displayName="Charcoal bale fallen and burst, charcoal spilled";
		model="\JP\site\yard_life\jp_s_charcoal_bales_ab_burst.p3d";
	};
	// jp_s_potted (yard_life)
	class StaticObj_JP_S_Potted_Stand: HouseNoDestruct
	{
		scope=1;
		displayName="Potted plants on a stepped stand";
		model="\JP\site\yard_life\jp_s_potted_stand.p3d";
	};
	class StaticObj_JP_S_Potted_Pair: HouseNoDestruct
	{
		scope=1;
		displayName="A potted pine in a tub and an azalea";
		model="\JP\site\yard_life\jp_s_potted_pair.p3d";
	};
	class StaticObj_JP_S_Potted_Ab_Dead: HouseNoDestruct
	{
		scope=1;
		displayName="Potted plants dead on their stand, one pot broken";
		model="\JP\site\yard_life\jp_s_potted_ab_dead.p3d";
	};
	class StaticObj_JP_S_Potted_Ab_Fallen: HouseNoDestruct
	{
		scope=1;
		displayName="Plant stand tipped over, pots spilled";
		model="\JP\site\yard_life\jp_s_potted_ab_fallen.p3d";
	};
	// jp_s_bird_cage (yard_life)
	class StaticObj_JP_S_Bird_Cage_Hung: HouseNoDestruct
	{
		scope=1;
		displayName="Empty bird cage hung under the eaves";
		model="\JP\site\yard_life\jp_s_bird_cage_hung.p3d";
	};
	class StaticObj_JP_S_Bird_Cage_Open: HouseNoDestruct
	{
		scope=1;
		displayName="Empty bird cage, door open, feeder tipped";
		model="\JP\site\yard_life\jp_s_bird_cage_open.p3d";
	};
	class StaticObj_JP_S_Bird_Cage_Ab_Fallen: HouseNoDestruct
	{
		scope=1;
		displayName="Bird cage fallen, paper torn";
		model="\JP\site\yard_life\jp_s_bird_cage_ab_fallen.p3d";
	};
	// jp_s_kakei (yard_life)
	class StaticObj_JP_S_Kakei_Trough: HouseNoDestruct
	{
		scope=1;
		displayName="Bamboo water pipe into a wooden trough";
		model="\JP\site\yard_life\jp_s_kakei_trough.p3d";
	};
	class StaticObj_JP_S_Kakei_Stone: HouseNoDestruct
	{
		scope=1;
		displayName="Bamboo water pipe into a stone basin";
		model="\JP\site\yard_life\jp_s_kakei_stone.p3d";
	};
	class StaticObj_JP_S_Kakei_Ab_Broken: HouseNoDestruct
	{
		scope=1;
		displayName="Bamboo pipe fallen, trough dry and broken";
		model="\JP\site\yard_life\jp_s_kakei_ab_broken.p3d";
	};
	// jp_s_stable_yard (yard_life)
	class StaticObj_JP_S_Stable_Yard_Tie_Post: HouseNoDestruct
	{
		scope=1;
		displayName="Horse tie post and a feed trough";
		model="\JP\site\yard_life\jp_s_stable_yard_tie_post.p3d";
	};
	class StaticObj_JP_S_Stable_Yard_Saddle_Rack: HouseNoDestruct
	{
		scope=1;
		displayName="Pack saddle on a rack";
		model="\JP\site\yard_life\jp_s_stable_yard_saddle_rack.p3d";
	};
	class StaticObj_JP_S_Stable_Yard_Trough_Stone: HouseNoDestruct
	{
		scope=1;
		displayName="Stone water trough, leaves inside";
		model="\JP\site\yard_life\jp_s_stable_yard_trough_stone.p3d";
	};
	class StaticObj_JP_S_Stable_Yard_Ab_Saddle_Fallen: HouseNoDestruct
	{
		scope=1;
		displayName="Pack saddle fallen off its rack";
		model="\JP\site\yard_life\jp_s_stable_yard_ab_saddle_fallen.p3d";
	};
	// jp_s_travel_gear (street_life)
	class StaticObj_JP_S_Travel_Gear_Set: HouseNoDestruct
	{
		scope=1;
		displayName="Dropped travel gear: hat, stick, bundle, sandal";
		model="\JP\site\street_life\jp_s_travel_gear_set.p3d";
	};
	class StaticObj_JP_S_Travel_Gear_Hat_Stick: HouseNoDestruct
	{
		scope=1;
		displayName="A sedge hat and a walking stick in the road";
		model="\JP\site\street_life\jp_s_travel_gear_hat_stick.p3d";
	};
	class StaticObj_JP_S_Travel_Gear_Ab_Burst: HouseNoDestruct
	{
		scope=1;
		displayName="Travel bundle burst open, hat crushed";
		model="\JP\site\street_life\jp_s_travel_gear_ab_burst.p3d";
	};
	// jp_s_kago (street_life)
	class StaticObj_JP_S_Kago_Down: HouseNoDestruct
	{
		scope=1;
		displayName="Palanquin (kago) set down in the road";
		model="\JP\site\street_life\jp_s_kago_down.p3d";
	};
	class StaticObj_JP_S_Kago_Ab_Tipped: HouseNoDestruct
	{
		scope=1;
		displayName="Palanquin tipped on its side";
		model="\JP\site\street_life\jp_s_kago_ab_tipped.p3d";
	};
	class StaticObj_JP_S_Kago_Ab_Broken: HouseNoDestruct
	{
		scope=1;
		displayName="Palanquin broken, pole thrown down, roof mat in the road";
		model="\JP\site\street_life\jp_s_kago_ab_broken.p3d";
	};
	// jp_s_tenbin_spill (street_life)
	class StaticObj_JP_S_Tenbin_Spill_Boxes: HouseNoDestruct
	{
		scope=1;
		displayName="Peddler's boxes overturned, goods spilled";
		model="\JP\site\street_life\jp_s_tenbin_spill_boxes.p3d";
	};
	class StaticObj_JP_S_Tenbin_Spill_Fish: HouseNoDestruct
	{
		scope=1;
		displayName="Fish seller's tubs overturned, fish dried black";
		model="\JP\site\street_life\jp_s_tenbin_spill_fish.p3d";
	};
	class StaticObj_JP_S_Tenbin_Spill_Veg: HouseNoDestruct
	{
		scope=1;
		displayName="Vegetable baskets overturned, daikon rotted";
		model="\JP\site\street_life\jp_s_tenbin_spill_veg.p3d";
	};
	// jp_s_bench_dress (street_life)
	class StaticObj_JP_S_Bench_Dress_Tea: HouseNoDestruct
	{
		scope=1;
		displayName="Tea tray with two cups (bench dressing)";
		model="\JP\site\street_life\jp_s_bench_dress_tea.p3d";
	};
	class StaticObj_JP_S_Bench_Dress_Tobacco: HouseNoDestruct
	{
		scope=1;
		displayName="Tobacco tray, pipe and a cup (bench dressing)";
		model="\JP\site\street_life\jp_s_bench_dress_tobacco.p3d";
	};
	class StaticObj_JP_S_Bench_Dress_Cloth: HouseNoDestruct
	{
		scope=1;
		displayName="Folded cloth and a tipped cup (bench dressing)";
		model="\JP\site\street_life\jp_s_bench_dress_cloth.p3d";
	};
	class StaticObj_JP_S_Bench_Dress_Ab_Spilled: HouseNoDestruct
	{
		scope=1;
		displayName="Cups knocked over, tobacco tray tipped, ash spilled (bench dressing)";
		model="\JP\site\street_life\jp_s_bench_dress_ab_spilled.p3d";
	};
	// jp_s_stool (street_life)
	class StaticObj_JP_S_Stool_Std: HouseNoDestruct
	{
		scope=1;
		displayName="Wooden stool";
		model="\JP\site\street_life\jp_s_stool_std.p3d";
	};
	class StaticObj_JP_S_Stool_Ab_Tipped: HouseNoDestruct
	{
		scope=1;
		displayName="Wooden stool knocked over";
		model="\JP\site\street_life\jp_s_stool_ab_tipped.p3d";
	};
	class StaticObj_JP_S_Stool_Ab_Broken: HouseNoDestruct
	{
		scope=1;
		displayName="Wooden stool, a leg broken off";
		model="\JP\site\street_life\jp_s_stool_ab_broken.p3d";
	};
	// jp_s_footwear (street_life)
	class StaticObj_JP_S_Footwear_Pairs: HouseNoDestruct
	{
		scope=1;
		displayName="Clogs and sandals at an entrance";
		model="\JP\site\street_life\jp_s_footwear_pairs.p3d";
	};
	class StaticObj_JP_S_Footwear_Ab_Scattered: HouseNoDestruct
	{
		scope=1;
		displayName="Clogs scattered, one upside down";
		model="\JP\site\street_life\jp_s_footwear_ab_scattered.p3d";
	};
	class StaticObj_JP_S_Footwear_Ab_Single: HouseNoDestruct
	{
		scope=1;
		displayName="A single clog, thong broken";
		model="\JP\site\street_life\jp_s_footwear_ab_single.p3d";
	};
	// jp_s_fishnet (street_life)
	class StaticObj_JP_S_Fishnet_Poles: HouseNoDestruct
	{
		scope=1;
		displayName="Fishing nets drying on three bamboo poles";
		model="\JP\site\street_life\jp_s_fishnet_poles.p3d";
	};
	class StaticObj_JP_S_Fishnet_Small: HouseNoDestruct
	{
		scope=1;
		displayName="A fishing net drying on two poles";
		model="\JP\site\street_life\jp_s_fishnet_small.p3d";
	};
	class StaticObj_JP_S_Fishnet_Heap: HouseNoDestruct
	{
		scope=1;
		displayName="A fishing net heaped on the sand";
		model="\JP\site\street_life\jp_s_fishnet_heap.p3d";
	};
	class StaticObj_JP_S_Fishnet_Ab_Down: HouseNoDestruct
	{
		scope=1;
		displayName="Net drying poles snapped, the net slumped";
		model="\JP\site\street_life\jp_s_fishnet_ab_down.p3d";
	};
	// jp_s_boat (street_life)
	class StaticObj_JP_S_Boat_Up: HouseNoDestruct
	{
		scope=1;
		displayName="Small plank boat pulled up on a bank";
		model="\JP\site\street_life\jp_s_boat_up.p3d";
	};
	class StaticObj_JP_S_Boat_Tilted: HouseNoDestruct
	{
		scope=1;
		displayName="Small boat on the bank, rolled on its bilge";
		model="\JP\site\street_life\jp_s_boat_tilted.p3d";
	};
	class StaticObj_JP_S_Boat_Upturned: HouseNoDestruct
	{
		scope=1;
		displayName="Small boat upturned on two logs";
		model="\JP\site\street_life\jp_s_boat_upturned.p3d";
	};
	class StaticObj_JP_S_Boat_Ab_Rotten: HouseNoDestruct
	{
		scope=1;
		displayName="Small boat rotting on the bank, side planks gone";
		model="\JP\site\street_life\jp_s_boat_ab_rotten.p3d";
	};
	// jp_s_fire_watch (street_life)
	class StaticObj_JP_S_Fire_Watch_Rack: HouseNoDestruct
	{
		scope=1;
		displayName="Fire gear rack: buckets, fire hook, ladder";
		model="\JP\site\street_life\jp_s_fire_watch_rack.p3d";
	};
	class StaticObj_JP_S_Fire_Watch_Ladder_Tower: HouseNoDestruct
	{
		scope=1;
		displayName="Fire-watch ladder with an alarm bell";
		model="\JP\site\street_life\jp_s_fire_watch_ladder_tower.p3d";
	};
	class StaticObj_JP_S_Fire_Watch_Ab_Fallen: HouseNoDestruct
	{
		scope=1;
		displayName="Fire gear rack, ladder and buckets fallen";
		model="\JP\site\street_life\jp_s_fire_watch_ab_fallen.p3d";
	};
	// jp_s_sandals_sale (street_life)
	class StaticObj_JP_S_Sandals_Sale_Eave: HouseNoDestruct
	{
		scope=1;
		displayName="Straw sandals hung for sale under the eaves";
		model="\JP\site\street_life\jp_s_sandals_sale_eave.p3d";
	};
	class StaticObj_JP_S_Sandals_Sale_Stand: HouseNoDestruct
	{
		scope=1;
		displayName="Straw sandals for sale on a rack";
		model="\JP\site\street_life\jp_s_sandals_sale_stand.p3d";
	};
	class StaticObj_JP_S_Sandals_Sale_Ab_Fallen: HouseNoDestruct
	{
		scope=1;
		displayName="Sandal rack blown over, sandals rotting";
		model="\JP\site\street_life\jp_s_sandals_sale_ab_fallen.p3d";
	};
	// jp_s_amado (street_life)
	class StaticObj_JP_S_Amado_Half_Open: HouseNoDestruct
	{
		scope=1;
		displayName="Shop shutters half open (two slid together)";
		model="\JP\site\street_life\jp_s_amado_half_open.p3d";
	};
	class StaticObj_JP_S_Amado_Leaning: HouseNoDestruct
	{
		scope=1;
		displayName="A shop shutter leaned against the front";
		model="\JP\site\street_life\jp_s_amado_leaning.p3d";
	};
	class StaticObj_JP_S_Amado_Fallen: HouseNoDestruct
	{
		scope=1;
		displayName="A shop shutter fallen flat in the street";
		model="\JP\site\street_life\jp_s_amado_fallen.p3d";
	};
	class StaticObj_JP_S_Amado_Ab_Broken: HouseNoDestruct
	{
		scope=1;
		displayName="A fallen shop shutter snapped in two";
		model="\JP\site\street_life\jp_s_amado_ab_broken.p3d";
	};
	// jp_s_lantern_fallen (street_life)
	class StaticObj_JP_S_Lantern_Fallen_Chochin: HouseNoDestruct
	{
		scope=1;
		displayName="A torn paper lantern fallen in the street";
		model="\JP\site\street_life\jp_s_lantern_fallen_chochin.p3d";
	};
	class StaticObj_JP_S_Lantern_Fallen_Andon: HouseNoDestruct
	{
		scope=1;
		displayName="A box lamp fallen on its back";
		model="\JP\site\street_life\jp_s_lantern_fallen_andon.p3d";
	};
	class StaticObj_JP_S_Lantern_Fallen_Crushed: HouseNoDestruct
	{
		scope=1;
		displayName="A crest lantern trodden flat";
		model="\JP\site\street_life\jp_s_lantern_fallen_crushed.p3d";
	};
};
