#!/usr/bin/env python3
r"""build.py - jp_f_tansu (effort test, level xhigh): model -> MLOD -> config -> binarize -> PBO.

  python build.py [--no-binarize] [--no-pack]

  1. tansu.py -> MLOD out/jp_f_tansu.p3d (state A, intact) and out/jp_f_tansu_ransacked.p3d (state B), copied to
     src/JP/effort_test/xhigh/ with model.cfg, config.cpp and the sidecar jp_f_tansu.json
  2. CfgConvert syntax check of config.cpp and model.cfg
  3. binarize.exe (cwd P:\) -> the ODOLs replace the MLOD copies in src (the MLODs stay in out/); out/binarize.log
  4. pack src/JP/effort_test/xhigh (minus model.cfg and the sidecar) -> ..\@Japan\addons\jp_efftest_xhigh.pbo,
     prefix JP\effort_test\xhigh; if the folder is locked the PBO goes to this spike folder instead
  5. verify.py -> checks.json
Never starts, stops or touches the server, the game or any GUI program. Python writes are binary with LF.
"""
import json
import os
import re
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DEV = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
ROOT = os.path.abspath(os.path.join(DEV, ".."))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(DEV, "tools", "common"))    # pbo.py (read-only, imported)
import tansu  # noqa: E402
from jpparts import mlod  # noqa: E402

LEVEL = "xhigh"
SRC = os.path.join(DEV, "src", "JP", "effort_test", LEVEL)
OUT = os.path.join(HERE, "out")
TEMP = os.path.join(HERE, "_build")
PBO_NAME = "jp_efftest_%s.pbo" % LEVEL
PBO_OUT = os.path.join(ROOT, "@Japan", "addons", PBO_NAME)
PREFIX = "JP\\effort_test\\%s" % LEVEL
PATCH = "JP_EffTest_%s" % LEVEL
MODELS = {"A": ("jp_f_tansu", "%s_Tansu" % PATCH, "Tansu (clothing chest of drawers)"),
          "B": ("jp_f_tansu_ransacked", "%s_Tansu_Ransacked" % PATCH, "Tansu (clothing chest of drawers, ransacked)")}
TOOLS = r"C:\Program Files (x86)\Steam\steamapps\common\DayZ Tools\Bin"
BINARIZE = os.path.join(TOOLS, "Binarize", "binarize.exe")
CFGCONVERT = os.path.join(TOOLS, "CfgConvert", "CfgConvert.exe")


def wb(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "wb") as f:
        f.write(text if isinstance(text, bytes) else text.replace("\r\n", "\n").encode("utf-8"))


def model_path(state):
    return "\\%s\\%s.p3d" % (PREFIX, MODELS[state][0])


# ------------------------------------------------------------------------------------------------ configs
def config_cpp():
    cls = ""
    for st in ("A", "B"):
        p3d, cname, disp = MODELS[st]
        cls += ("\t// %s\n\tclass %s: HouseNoDestruct\n\t{\n\t\tscope=1;\n\t\tdisplayName=\"%s\";\n"
                "\t\tmodel=\"%s\";\n\t};\n"
                % ("state A: intact, every drawer shut, dusty" if st == "A" else
                   "state B: ransacked, the lock drawer on the floor in front, three drawers pulled out",
                   cname, disp, model_path(st)))
    return ("// %s - effort test (level %s): jp_f_tansu, the clothing chest of drawers (BUILD_LIST row 26), two states.\n"
            "// GENERATED by japan_dev/spikes/effort_test/%s/build.py - edit the generator, not this file.\n"
            "// Static furniture like vanilla StaticObj_Furniture_* (HouseNoDestruct, scope 1): placed by the object\n"
            "// spawner, init.c or as a proxy. Asset only: no world, map or mission dependency.\n"
            "class CfgPatches\n{\n\tclass %s\n\t{\n\t\tunits[]={};\n\t\tweapons[]={};\n\t\trequiredVersion=0.1;\n"
            "\t\trequiredAddons[]=\n\t\t{\n\t\t\t\"DZ_Data\",\n\t\t\t\"JP_Common\"\n\t\t};\n\t};\n};\n"
            "class CfgVehicles\n{\n\tclass HouseNoDestruct;\n%s};\n" % (PATCH, LEVEL, LEVEL, PATCH, cls))


def model_cfg():
    body = "".join("\tclass %s: Default\n\t{\n\t};\n" % MODELS[st][0] for st in ("A", "B"))
    return ("// static furniture: no skeleton, no animations\n"
            "class CfgSkeletons\n{\n\tclass Default\n\t{\n\t\tisDiscrete=1;\n\t\tskeletonInherit=\"\";\n"
            "\t\tskeletonBones[]={};\n\t};\n};\nclass CfgModels\n{\n\tclass Default\n\t{\n\t\tsectionsInherit=\"\";\n"
            "\t\tsections[]={};\n\t\tskeletonName=\"\";\n\t};\n%s};\n" % body)


def cfgconvert(path):
    os.makedirs(TEMP, exist_ok=True)
    dst = os.path.join(TEMP, os.path.basename(path) + ".bin")
    if os.path.isfile(dst):
        os.remove(dst)
    r = subprocess.run([CFGCONVERT, "-bin", "-dst", dst, path], capture_output=True, text=True, errors="replace")
    ok = r.returncode == 0 and os.path.isfile(dst)
    # and back to text, to prove the binary round-trips
    txt = dst + ".cpp"
    r2 = subprocess.run([CFGCONVERT, "-txt", "-dst", txt, dst], capture_output=True, text=True, errors="replace")
    ok2 = r2.returncode == 0 and os.path.isfile(txt)
    msg = (r.stdout + r.stderr + r2.stdout + r2.stderr).strip()
    print("  CfgConvert %s: %s %s" % (os.path.basename(path), "OK" if ok and ok2 else "FAILED", msg))
    return ok and ok2, msg


# ------------------------------------------------------------------------------------------------ steps
def write_models():
    os.makedirs(OUT, exist_ok=True)
    os.makedirs(SRC, exist_ok=True)
    infos = {}
    for st in ("A", "B"):
        part, info, L = tansu.lods(st)
        name = MODELS[st][0]
        mp = os.path.join(OUT, name + ".p3d")
        mlod.write_mlod(mp, L)
        shutil.copyfile(mp, os.path.join(SRC, name + ".p3d"))
        info["faces"] = {mlod.lod_name(l.resolution): len(l.faces) for l in L}
        info["tris_res1"] = sum(len(f[0]) - 2 for f in L[0].faces)
        infos[st] = info
        print("MLOD %s: %s, Res 1 = %d triangles" % (mp, info["faces"], info["tris_res1"]))
    wb(os.path.join(SRC, "model.cfg"), model_cfg())
    wb(os.path.join(SRC, "config.cpp"), config_cpp())
    return infos


def sidecar(infos):
    sc = {
        "id": "jp_f_tansu",
        "name": "Clothing chest of drawers (isho-dansu), two stacked parts",
        "made_by": "spikes/effort_test/%s/build.py (effort test, 2026-09-29)" % LEVEL,
        "variants": {"": {"p3d": model_path("A"), "class": MODELS["A"][1], "state": "intact, drawers shut, dusty"},
                     "_ransacked": {"p3d": model_path("B"), "class": MODELS["B"][1],
                                    "state": "the lock drawer on the floor in front, three drawers pulled out, one shut",
                                    "drawers": infos["B"]["drawers"], "dropped": infos["B"].get("dropped")}},
        "datum": "origin = base centre on the floor; +y up; +z = the front (drawers); +x = the chest's own right "
                 "(a viewer facing the drawers sees it on the LEFT); autocenter=0",
        "size_m": {"width": 1.0, "depth": 0.45, "height": 1.0, "parts": [0.5, 0.5],
                   "note": "body; iron fittings add up to 9 mm (side handles) and 10 mm (pulls)"},
        "connectors": [{"type": "proxy_base", "pos": [0.0, 0.0, 0.0],
                        "note": "on the floor against a wall, back 0.02 off the wall (BUILD_LIST row 26)"}],
        "footprint": {"x": [-0.5, 0.5], "z": [-0.225, 0.225]},
        "front_zone": dict(tansu.FRONT_ZONE, rule="kept clear by the decorator: no other prop, not part of a path "
                                               "or a clear band; state B's dropped drawer lies inside it"),
        "loot_surfaces": [
            {"surface": "top", "height": 1.0, "rect": {"x": [-0.47, 0.47], "z": [-0.20, 0.20]},
             "points": [lp for lp in infos["A"]["loot"]], "container": "lootshelves", "tag": "shelves",
             "states": ["", "_ransacked"]},
            {"surface": "dropped drawer bottom", "height": tansu.TBOT,
             "points": [lp for lp in infos["B"]["loot"] if lp["name"] == "loot_drawer"], "container": "lootshelves",
             "tag": "shelves", "states": ["_ransacked"],
             "note": "the drawer's inside is about 0.90 x 0.35 m; range 0.15 keeps the item inside its walls"}],
        "loot_note": "BUILD_LIST row 26: top at 1.00, 2 points (range 0.2); ransacked: 1 point in the dropped drawer "
                     "(floor). No Memory LOD (BUILD_LIST Q5 binding item 2): the points live here. The furnished "
                     "house's generator adds them as lootshelves points and subtracts footprint + front zone from "
                     "lootFloor.",
        "materials": [
            {"surface": "body, drawer fronts", "wanted": "jp_m_wood_interior (timber_interior), not built yet",
             "used": "JP\\common\\materials\\wood\\jp_m_wood_street_dark_w2.rvmat",
             "why": "closest library wood to timber_interior (dE76 8.8 < tolerance 14); _w2 = dusty, pale edge wear"},
            {"surface": "carcass inside (seen through the ransacked openings)",
             "used": "JP\\common\\materials\\wood\\jp_m_wood_sooted_w0.rvmat",
             "why": "near-black: stands in for the occlusion inside a closed cabinet"},
            {"surface": "drawer boxes (sides, back, bottom)",
             "used": "JP\\common\\materials\\wood\\jp_m_wood_weathered_w1.rvmat",
             "why": "paler unfinished secondary wood, reads against the dark show faces"},
            {"surface": "fittings", "wanted": "jp_m_metal_iron (iron_black)",
             "used": "JP\\common\\materials\\metal\\jp_m_metal_iron_w1.rvmat", "why": "the planned material itself"}],
        "faces": {st: infos[st]["faces"] for st in infos},
        "tiers": [2, 3], "room_tags": ["sleeping", "zashiki", "living", "office", "storage"],
    }
    wb(os.path.join(SRC, "jp_f_tansu.json"), json.dumps(sc, indent=1) + "\n")
    # the loot note as mapgroupproto points (model -> CE frame (mx,my,mz) = (-lz,ly,lx), pokemon_dev WORLD_BUILDINGS s0)
    lines = ["<!-- jp_f_tansu loot surfaces (effort test %s). Reference only: a furnished house's generator transforms these"
             " into the house frame. CE frame: lx = model z, ly = model y, lz = -model x. -->" % LEVEL]
    for st in ("A", "B"):
        lines.append('<group name="%s">' % MODELS[st][1])
        lines.append('\t<container name="lootshelves">')
        lines.append('\t\t<category name="tools" />\n\t\t<category name="clothes" />\n\t\t<tag name="shelves" />')
        for lp in infos[st]["loot"]:
            mx, my, mz = lp["model"]
            lines.append('\t\t<point pos="%.6f %.6f %.6f" range="%.6f" height="%.6f" />  <!-- %s -->'
                         % (mz, my, -mx, lp["range"], min(2.0, 2.5 * lp["range"]), lp["name"]))
        lines.append("\t</container>\n</group>")
    wb(os.path.join(HERE, "loot_note_mapgroupproto.xml"), "\n".join(lines) + "\n")


BENIGN = [r"^No entry '\.", r"^Trying to access error value\.", r"CfgVehicles missing in PreloadConfig",
          r"Terrain grid 0\.5 will be too slow", r"is declared, but definition was not found",
          r"^Distance 0\.0 - min grid", r"^FileServer MaxCacheSize", r"^BINARIZE rev", r"^Binarize started",
          r"binarize\.exe\"? -always", r"^Convert model ", r"^<model = ", r"^</model>", r"KB saved in selections",
          r"DIAG-SERIALIZED BoundingCenter", r"^\s*$"]


def binarize():
    if not os.path.isdir(r"P:\DZ") or not os.path.isdir(r"P:\JP\effort_test\%s" % LEVEL):
        print(r"binarize: P:\DZ or P:\JP\effort_test\%s missing (subst P: D:\DayZToolsExtract; P:\JP junction)" % LEVEL)
        return False, {}
    out = os.path.join(TEMP, "binarized")
    shutil.rmtree(out, ignore_errors=True)
    os.makedirs(out)
    cmd = [BINARIZE, "-always", "-addon=P:\\JP\\effort_test\\%s" % LEVEL, "-binpath=P:\\bin",
           "P:\\JP\\effort_test\\%s" % LEVEL, out, "*.p3d"]
    r = subprocess.run(cmd, cwd="P:\\", capture_output=True, text=True, errors="replace")
    log = os.path.join(OUT, "binarize.log")
    text = r.stdout + "\n" + r.stderr
    wb(log, " ".join(cmd) + "\n\n" + text)
    lines = [l for l in text.splitlines()]
    other = [l for l in lines if not any(re.search(b, l) for b in BENIGN)]
    flagged = [l for l in lines if re.search(r"error|warning|cannot|not loaded|missing|failed", l, re.I)
               and not any(re.search(b, l) for b in BENIGN)]
    res = {"returncode": r.returncode, "log": os.path.relpath(log, DEV), "lines": len(lines),
           "unexplained_lines": other, "flagged_lines": flagged, "converted": {}}
    ok = True
    for st in ("A", "B"):
        name = MODELS[st][0] + ".p3d"
        found = None
        for root_, _, files in os.walk(out):
            if name in files:
                found = os.path.join(root_, name)
        good = bool(found) and open(found, "rb").read(4) == b"ODOL"
        res["converted"][name] = {"odol": good, "bytes": os.path.getsize(found) if found else 0,
                                  "mentioned_in_log": any(name in l.lower() for l in lines)}
        if good:
            shutil.copyfile(found, os.path.join(SRC, name))
        ok = ok and good
    print("binarize %s: %s; %d log lines, %d unexplained, %d flagged -> %s" % (
        "OK" if ok else "FAILED", {k: v["bytes"] for k, v in res["converted"].items()}, len(lines), len(other),
        len(flagged), log))
    for l in other:
        print("   unexplained:", l)
    res["ok"] = ok and not flagged
    return ok, res


def pack():
    stage = os.path.join(TEMP, "pbo_stage")
    shutil.rmtree(stage, ignore_errors=True)
    shutil.copytree(SRC, stage, ignore=shutil.ignore_patterns("model.cfg", "*.json", "*.blend", "*.png", "*.log"))
    import pbo
    try:
        pbo.cmd_pack(stage, PBO_OUT, PREFIX)
        where = PBO_OUT
    except PermissionError as e:
        print("PBO write to @Japan\\addons FAILED (a running server or game locks it):", e)
        where = os.path.join(HERE, PBO_NAME)
        pbo.cmd_pack(stage, where, PREFIX)
    print("packed", where, os.path.getsize(where), "bytes")
    return where


def main(argv):
    infos = write_models()
    sidecar(infos)
    cc = [cfgconvert(os.path.join(SRC, "config.cpp")), cfgconvert(os.path.join(SRC, "model.cfg"))]
    bres = {}
    if "--no-binarize" not in argv:
        _, bres = binarize()
    where = None
    if "--no-pack" not in argv:
        where = pack()
    wb(os.path.join(OUT, "build_result.json"), json.dumps({
        "cfgconvert": {"config.cpp": {"ok": cc[0][0], "msg": cc[0][1]}, "model.cfg": {"ok": cc[1][0], "msg": cc[1][1]}},
        "binarize": bres, "pbo": where, "infos": infos}, indent=1, default=str) + "\n")
    import verify
    ok = verify.run()
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
