// JP_Common - the shared material library (jp_m_*) and the material swatch wall.
// GENERATED by japan_dev/research/materials/build_materials.py - edit the generator, not this file.
// One CfgPatches class for this PBO, declared once. Every area lists JP_Common in requiredAddons.
class CfgPatches
{
	class JP_Common
	{
		units[]={};
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"DZ_Data",
			"DZ_Structures_Residential"
		};
	};
};
class CfgVehicles
{
	class HouseNoDestruct;
	class Land_JP_Swatch_Wall: HouseNoDestruct
	{
		scope=1;
		displayName="JP material swatch wall";
		model="\JP\common\swatch\jp_swatch_wall.p3d";
	};
};
