r"""binarize_config.py - build the config.cpp that binarize.exe reads while it converts the 8WVR world to OPRW.

Why (2026-09-27): binarize run with -binpath=P:\ only sees P:\bin\config.cpp plus our addon config. It cannot
resolve `JapanTestIsland: ChernarusPlus`, so 39 world lookups (Clutter, sky, sea...) fell back to defaults and
the OPRW came out with the v29 header byte after "0FNE" at 0. Every world that boots on this server (vanilla
ChernarusPlus/Enoch, DeerIsle, Banov) has it at 1, and ours crashed the server with INT_DIVIDE_BY_ZERO inside
CE InitOffline. This builds a binarize-only config that carries the vanilla definitions binarize needs:

    CfgSurfaceCharacters, CfgSurfaces         from P:\DZ\surfaces\config.cpp
    CfgWorlds.CAWorld (Clutter + the rest)     merged from P:\DZ\surfaces\config.cpp and
                                               P:\DZ\worlds\chernarusplus\world\config.cpp
    CfgWorlds.ChernarusPlus                    from P:\DZ\worlds\chernarusplus\world\config.cpp
    + our own config (CfgPatches, CfgWorldList, CfgWorlds.JapanTestIsland)

It is written only for the binarize step and never shipped; the packed config.cpp stays the lean one.
"""


def _skip_string(t, i):
    q = t[i]
    i += 1
    while i < len(t) and t[i] != q:
        i += 1
    return i + 1


def block_body(t, header_pos):
    """Return (body_start, body_end) of the {...} that follows header_pos (exclusive of the braces)."""
    i = t.index("{", header_pos)
    start = i + 1
    depth = 1
    i += 1
    while depth:
        c = t[i]
        if c in "\"'":
            i = _skip_string(t, i)
            continue
        if c == "/" and t[i + 1] == "/":
            i = t.index("\n", i)
            continue
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
        i += 1
    return start, i - 1


def find_class(t, name, start=0, end=None, top_only=True):
    """Position of `class <name>` (followed by ':' or '{' or whitespace) at brace depth 0 of t[start:end]."""
    end = len(t) if end is None else end
    depth = 0
    i = start
    key = "class " + name
    while i < end:
        c = t[i]
        if c in "\"'":
            i = _skip_string(t, i)
            continue
        if c == "/" and i + 1 < end and t[i + 1] == "/":
            i = t.index("\n", i)
            continue
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
        elif depth == 0 and t.startswith(key, i):
            nxt = t[i + len(key)] if i + len(key) < len(t) else ""
            if nxt in " \t\r\n:{":
                # skip forward declarations "class X;"
                j = i + len(key)
                while j < end and t[j] in " \t\r\n":
                    j += 1
                if t[j] != ";":
                    return i
        i += 1
    raise KeyError(name)


def get_body(t, name, start=0, end=None):
    p = find_class(t, name, start, end)
    return block_body(t, p)


def build(our_config_text, surfaces_path, world_path):
    surf = open(surfaces_path, "rb").read().decode("latin-1")
    world = open(world_path, "rb").read().decode("latin-1")

    s_chars = surf[slice(*get_body(surf, "CfgSurfaceCharacters"))]
    s_surfs = surf[slice(*get_body(surf, "CfgSurfaces"))]
    s_worlds_b, s_worlds_e = get_body(surf, "CfgWorlds")
    s_caworld = surf[slice(*get_body(surf, "CAWorld", s_worlds_b, s_worlds_e))]

    w_worlds_b, w_worlds_e = get_body(world, "CfgWorlds")
    w_caworld = world[slice(*get_body(world, "CAWorld", w_worlds_b, w_worlds_e))]
    w_cp = world[slice(*get_body(world, "ChernarusPlus", w_worlds_b, w_worlds_e))]

    ours = our_config_text
    o_worlds_b, o_worlds_e = get_body(ours, "CfgWorlds")
    o_island_b, o_island_e = get_body(ours, "JapanTestIsland", o_worlds_b, o_worlds_e)
    island = ours[o_island_b:o_island_e]
    head = ours[:find_class(ours, "CfgWorlds")]   # CfgPatches + CfgWorldList (everything before CfgWorlds)
    tail = ours[o_worlds_e + 1:]
    if tail.lstrip().startswith(";"):
        tail = tail.lstrip()[1:]

    out = []
    out.append("// BINARIZE-ONLY config for JapanTestIsland - generated by tools/binarize_config.py, never shipped.\n")
    out.append(head)
    out.append("class CfgSurfaceCharacters\n{" + s_chars + "};\n")
    out.append("class CfgSurfaces\n{" + s_surfs + "};\n")
    out.append("class CfgWorlds\n{\n\tclass DefaultWorld;\n")
    out.append("\tclass CAWorld: DefaultWorld\n\t{" + s_caworld + "\n" + w_caworld + "\t};\n")
    out.append("\tclass ChernarusPlus: CAWorld\n\t{" + w_cp + "\t};\n")
    out.append("\tclass JapanTestIsland: ChernarusPlus\n\t{" + island + "\t};\n};\n")
    out.append(tail)
    return "".join(out)


if __name__ == "__main__":
    import sys
    src = sys.argv[1]
    txt = build(open(src, "rb").read().decode("latin-1"),
                r"P:\DZ\surfaces\config.cpp", r"P:\DZ\worlds\chernarusplus\world\config.cpp")
    open(sys.argv[2], "wb").write(txt.encode("latin-1"))
    print("wrote", sys.argv[2], len(txt), "bytes")
