"""Make (or refresh) the OFFLINE copy of the test mission, for DayZDiag_x64 single-player.

    python tools\\editor_bridge\\offline_mission.py

Reads mission\\japantest.japantestisland\\ (T's multiplayer CE mission, generated by build_mission.py) and writes
mission\\japantest_offline.japantestisland\\: every file copied as-is except init.c, which is rewritten for offline
play. start-japan-offline.bat runs this first, so the offline copy always follows T's latest mission build.

Why the MP init.c cannot run offline as-is (vanilla scripts, D:\\DayZToolsExtract\\scripts):
  * 5_mission\\somemission.c: offline the game wants a MissionGameplay; the MP init.c returns a MissionServer subclass.
  * 5_mission\\mission\\missionserver.c: MissionServer creates the character only on a client-connect event
    (OnClientNewEvent -> CreateCharacter -> InvokeOnConnect). Offline nobody connects, so there would be no player
    and JPTest_SpawnAll (items + creatures) would never run.
The offline init.c therefore: starts the CE offline (loot, same as the server), creates and selects a player at the
yard spawn (1024, 985) facing north, sets 10:00 on 5 April, lays out the same item grid and creatures (parsed from
the MP init.c), and makes sure the cfggameplay object spawner ran (the spawns/*.json objects): if the first spawner
object is not found after 5 s it calls ObjectSpawnerHandler.SpawnObjects() itself. Log lines start with [JPOffline].
The CE writes storage_-1\\ inside the offline mission folder; this script never touches it.
"""
import json
import os
import re
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DEV = os.path.abspath(os.path.join(HERE, "..", ".."))
SRC = os.path.join(DEV, "mission", "japantest.japantestisland")
DST = os.path.join(DEV, "mission", "japantest_offline.japantestisland")

INIT = r"""// japantest_offline.japantestisland - GENERATED by japan_dev/tools/editor_bridge/offline_mission.py from the MP
// mission japantest.japantestisland (T's build_mission.py). Do not edit: rerun the script (start-japan-offline.bat
// does it on every launch). Single-player DayZDiag version: no client connects offline, so this file creates the
// player itself and returns a MissionGameplay.

void JPOffline_Item(string cls, float x, float z)
{
	vector pos = Vector(x, 25.0, z);
	Object obj = GetGame().CreateObjectEx(cls, pos, ECE_PLACE_ON_SURFACE | ECE_NOPERSISTENCY_WORLD);
	if ( !obj )
		Print("[JPOffline] item class not found: " + cls);
}

void JPOffline_Creature(string cls, float x, float z, float yaw)
{
	float y = GetGame().SurfaceY(x, z);
	vector pos = Vector(x, y, z);
	Object obj = GetGame().CreateObjectEx(cls, pos, ECE_PLACE_ON_SURFACE | ECE_INITAI | ECE_EQUIP_ATTACHMENTS | ECE_NOPERSISTENCY_WORLD);
	if ( !obj )
	{
		Print("[JPOffline] creature class not found: " + cls);
		return;
	}
	obj.SetOrientation(Vector(yaw, 0, 0));
}

void JPOffline_CheckSpawner()
{
	// the cfggameplay object spawner normally runs by itself (DayZGame.GlobalsInit); make sure it did
	string probeType = "%PROBE_TYPE%";
	if ( probeType == "" )
		return;
	array<Object> found = new array<Object>;
	GetGame().GetObjectsAtPosition3D(Vector(%PROBE_POS%), 1.0, found, null);
	bool ok = false;
	for ( int i = 0; i < found.Count(); i++ )
	{
		if ( found[i] && found[i].GetType() == probeType )
			ok = true;
	}
	if ( ok )
	{
		Print("[JPOffline] object spawner ran (found " + probeType + ")");
		return;
	}
	Print("[JPOffline] object spawner did not run offline - spawning spawns/*.json now");
	ObjectSpawnerHandler.SpawnObjects();
}

void main()
{
	//INIT ECONOMY--------------------------------------
	Hive ce = CreateHive();
	if ( ce )
		ce.InitOffline();

	GetGame().GetWorld().SetDate(2026, 4, 5, 10, 0);

	float sx = 1024.0;
	float sz = 985.0;
	float sy = GetGame().SurfaceY(sx, sz);
	PlayerBase player = PlayerBase.Cast(GetGame().CreatePlayer(null, "SurvivorM_Mirek", Vector(sx, sy, sz), 0, "NONE"));
	if ( player )
	{
		player.SetOrientation(Vector(0, 0, 0));
		player.GetInventory().CreateInInventory("TShirt_Beige");
		player.GetInventory().CreateInInventory("Jeans_Blue");
		player.GetInventory().CreateInInventory("AthleticShoes_Black");
		player.GetInventory().CreateInInventory("Hatchet");
		GetGame().SelectPlayer(null, player);
	}
	else
	{
		Print("[JPOffline] CreatePlayer failed");
	}

%ITEMS%
	Print("[JPOffline] test layout spawned: %NITEMS% items, %NCREATURES% creatures");
	GetGame().GetCallQueue(CALL_CATEGORY_GAMEPLAY).CallLater(JPOffline_CheckSpawner, 5000, false);
}

Mission CreateCustomMission(string path)
{
	return new MissionGameplay();
}
"""


def wb(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "wb") as f:
        f.write(text.encode("utf-8"))


def main():
    if not os.path.isdir(SRC):
        print("missing %s - run spikes\\T_terrain\\build_mission.py first" % SRC)
        return 1
    n = 0
    for dp, dns, fns in os.walk(SRC):
        dns[:] = [d for d in dns if not d.lower().startswith("storage_")]
        for fn in fns:
            rel = os.path.relpath(os.path.join(dp, fn), SRC)
            if rel.lower() == "init.c":
                continue
            dst = os.path.join(DST, rel)
            os.makedirs(os.path.dirname(dst), exist_ok=True)
            shutil.copyfile(os.path.join(dp, fn), dst)
            n += 1
    src_init = open(os.path.join(SRC, "init.c"), "rb").read().decode("utf-8")
    items = re.findall(r'JPTest_Item\("([^"]+)",\s*([-0-9.]+),\s*([-0-9.]+)\);', src_init)
    crs = re.findall(r'JPTest_Creature\("([^"]+)",\s*([-0-9.]+),\s*([-0-9.]+),\s*([-0-9.]+)\);', src_init)
    lines = ['\tJPOffline_Item("%s", %s, %s);' % it for it in items]
    lines += ['\tJPOffline_Creature("%s", %s, %s, %s);' % c for c in crs]
    # probe for the object spawner: the first object of the first spawner file cfggameplay.json lists
    probe_type, probe_pos = "", "0, 0, 0"
    try:
        gp = json.load(open(os.path.join(SRC, "cfggameplay.json"), "rb"))
        for rel in gp.get("WorldsData", {}).get("objectSpawnersArr", []):
            objs = json.load(open(os.path.join(SRC, rel), "rb")).get("Objects", [])
            if objs:
                probe_type = objs[0]["name"]
                probe_pos = "%.3f, %.3f, %.3f" % tuple(objs[0]["pos"])
                break
    except (OSError, ValueError, KeyError) as ex:
        print("note: no spawner probe (%s)" % ex)
    text = (INIT.replace("%ITEMS%", "\n".join(lines)).replace("%NITEMS%", str(len(items)))
            .replace("%NCREATURES%", str(len(crs))).replace("%PROBE_TYPE%", probe_type).replace("%PROBE_POS%", probe_pos))
    wb(os.path.join(DST, "init.c"), text)
    print("offline mission: %s (%d files copied, init.c with %d items, %d creatures, spawner probe %s)"
          % (DST, n, len(items), len(crs), probe_type or "none"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
