"""FX1 render jobs (spikes/FX1/render_fx1.py): (out, caption, spec). Cameras in the MODEL frame of the key (x, y up,
z = front); prop shots place catalogue props at [name, x, y, z, yaw]. Rendered twice: FX1_TAG=before from a HEAD
copy of the tree, FX1_TAG=after from the working tree; spikes/FX1/sheet_fx1.py pairs them."""

JOBS = [
    ("doors_p1", "1 P1 town haiden doors (lattice tobira, opening in), half open: each leaf's ring pull + pull board",
     {"key": "f_shrine_haiden_town", "cam": [0.9, 1.95, 4.7], "look": [0.0, 1.55, 2.3], "lens": 24, "open": 0.55,
      "site": False}),
    ("doors_t1", "1 T1 village hondo, left door pair (lattice, opening in), half open",
     {"key": "f_temple_hondo_village", "cam": [-0.2, 1.85, 5.6], "look": [-0.9, 1.45, 3.6], "lens": 24,
      "open": 0.55, "site": False}),
    ("box_p1", "2 P1 offering box: was centred across the 1.1 m stair foot, with leaf litter draped on it; now on the "
     "ground beside the stair foot, clear of the kohai post, no litter",
     {"key": "f_shrine_haiden_town", "cam": [1.2, 2.1, 9.6], "look": [0.6, 0.7, 4.6], "lens": 26}),
    ("box_u1", "2 U1 town hondo donation box beside the stair foot",
     {"key": "f_temple_hondo_town", "cam": [1.4, 2.0, 10.6], "look": [0.8, 0.8, 5.6], "lens": 26}),
    ("bell_t3", "3 T3 village bell tower: the striker log on two ropes from the bell beam (was: ropes ending in the "
     "air), the bell on its hook", {"key": "f_temple_shoro_village", "cam": [2.3, 1.9, 2.9], "look": [-0.2, 2.6, 0.0],
                                    "lens": 20}),
    ("gong_u1", "3 U1 town hondo gong: hangs from a bar between the kohai tie beams (was: 1.56 m of air above it)",
     {"key": "f_temple_hondo_town", "cam": [-0.45, 2.3, 7.6], "look": [0.0, 3.9, 4.0], "lens": 24, "site": False}),
    ("suzu_p1", "3 P1 haiden bell rope (suzu): from a bar between the kohai tie beams (was: 1.08 m of air above it)",
     {"key": "f_shrine_haiden_town", "cam": [-0.45, 2.0, 6.6], "look": [0.0, 3.3, 2.9], "lens": 24, "site": False}),
    ("en_u1", "4 U1 town hondo: the en (veranda) ends - koran returns back to the wall (was: deck and rail cut off)",
     {"key": "f_temple_hondo_town", "cam": [6.4, 2.0, 6.6], "look": [2.9, 1.1, 3.6], "lens": 24, "site": False}),
    ("torii_shinmei", "5 Wooden shinmei torii, rope + shide, a 1.80 m figure: shide tip 1.67 -> 2.46 m over the base",
     {"props": [["jp_s_torii_wood_shinmei_rope_shide", 0.0, 0.0, 0.0, 0.0]], "humans": [[0.3, 0.0]],
      "cam": [1.6, 1.5, 6.2], "look": [0.0, 1.9, 0.0], "lens": 28}),
    ("torii_myojin", "5 Wooden myojin torii, rope + shide: 2.03 -> 2.60 m",
     {"props": [["jp_s_torii_wood_myojin_rope_shide", 0.0, 0.0, 0.0, 0.0]], "humans": [[0.3, 0.0]],
      "cam": [1.8, 1.6, 7.6], "look": [0.0, 2.1, 0.0], "lens": 28}),
    ("torii_stone_s", "5 Stone torii s, rope + shide: 1.50 -> 2.52 m",
     {"props": [["jp_s_torii_stone_s_rope_shide", 0.0, 0.0, 0.0, 0.0]], "humans": [[0.3, 0.0]],
      "cam": [1.6, 1.5, 6.6], "look": [0.0, 2.0, 0.0], "lens": 28}),
    ("wood_wall", "6 Wall woodpile 1 ken x 1.2 m: tied end stakes (front + back) at both free ends",
     {"props": [["jp_s_firewood_stack_wall_1ken_h120", 0.0, 0.0, 0.0, 0.0]], "cam": [1.9, 1.2, 2.3],
      "look": [0.35, 0.6, 0.2], "lens": 28}),
    ("wood_free", "6 Free-standing woodpile: two tied stakes per end (was one post per end)",
     {"props": [["jp_s_firewood_stack_free_posts", 0.0, 0.0, 0.0, 0.0]], "cam": [2.0, 1.4, 2.4],
      "look": [0.3, 0.6, 0.0], "lens": 28}),
    ("wood_f", "6 Kitchen woodpile (jp_f_firewood_stack): stakes inside its 0.91 m footprint",
     {"props": [["jp_f_firewood_stack", 0.0, 0.0, 0.0, 0.0]], "cam": [1.2, 0.9, 1.5], "look": [0.1, 0.32, 0.0],
      "lens": 30}),
]
