# Waterway TYPES and the PARTS list (data only). Rendered by gen_waterways.py.
# Research agent WW, 2026-09-29. Source keys are defined in SOURCES (gen_waterways.py).

TYPES = [
 {
  "code": "a", "water_short": "sea (coastal towns) / pond (inland a3)", "name": "City canal (horikawa)",
  "what": "Straight dug canal between stone or timber walls; the streets of Osaka and eastern Edo, Nagoya's Horikawa, "
          "Sakai's moat ring. Kura and open quays (kashi / hama) line it; many plank bridges.",
  "variants": [
   "a1 main canal: 20-36 m water, dressed-stone walls, trestle or long plank bridges, kura-yashiki boat basins (funairi)",
   "a2 back canal: 8-15 m water, rough stone or pile-and-board banks, short plank bridges, house backs with steps",
   "a3 river kashi: a natural river used as a canal (Ise Kawasaki on the Seta, Fushimi port): kura straight onto the water"],
  "cross_section": [
   ["water width, main", "20-55 m", "Sanjukkenbori was 30 ken (~55 m) from 1612, narrowed to 19 ken in 1828 [S-30K]; Nagoya Horikawa 12-48 ken (22-87 m) [S-NGY]; Nagahori ~40 m, Dotonbori 30-50 m (today's widths) [S-OSK]. Game: 20 m and 36 m"],
   ["water width, back canal", "8-15 m (assumed)", "between the Takase (7-8 m, a hauled canal) and the named main canals; Hacchobori / Kaede-gawa scale. Game: 10 m"],
   ["water depth", "1.8-2.5 m (assumed)", "carried loaded flat lighters (hirata) at low tide; must be deep enough to swim in DayZ"],
   ["wall top above water", "2.0-3.0 m", "Hiroshima domain kura-yashiki revetment, Osaka: stone walls 3 m high [S-KURA]; the castle-side wall of Edo's outer moat along the Nihonbashi River is ~6 m [S-EDOM] (castle scale, not a canal)"],
   ["quay strip (kashi / hama)", "4-10 m (assumed)", "open unloading strip between the wall and the kura or house row, with sheds (naya), stacked goods and landing steps [l02, l07]"],
   ["wall batter", "dressed 1:0.1-0.2, rough 1:0.3 (assumed)", "near-vertical dressed walls read as 'city'"],
   ["hidden foundation", "timber sill logs (dogi) on piles ~1 m apart", "found under Edo's moat walls on soft ground [S-EDOM]; shows only in the collapsed-wall abandoned state"]],
  "edges": "Dressed stone (uchikomi-hagi / kirikomi-hagi) for main canals, kura-yashiki frontages and quays; rough stone (nozura) on back canals; "
           "pile-and-board revetment (kui-dome: posts ~0.9 m apart with boards behind) for cheap banks, clearly shown along the Onagi-gawa [l08].",
  "steps_landings": "Gangi quay steps at every quay and at each kura-yashiki (the Hiroshima domain yard had stone walls + gangi + a 51 x 47 m boat basin cut into the plot [S-KURA]); "
                    "plank landing stages on piles; short private step flights at house backs.",
  "mooring": "Timber mooring posts standing in the water at the wall foot; holed mooring stones set in the wall top.",
  "outfalls": "Street-drain mouths in the wall every block (gesui-guchi); Osaka's back-to-back sewers end here [OL U streets].",
  "bridges": "KEEP_CIVIC plank bridge (most; Osaka had ~200 townsmen's bridges), trestle bridge (the big public bridges: Nihonbashi, Tenma-bashi, Naniwa-bashi), occasional arched bridge. No stone slab bridges (spans too long).",
  "planting": "Weeping willow at bridge ends and canal corners [l07]; a single old pine at a quay corner (Onagi-gawa's 'five pines' [l08]); no cherry rows (Kiyamachi-style cherry rows are Meiji or later).",
  "buildings": "Kura backs straight onto the wall with water doors (Nagoya Horikawa, Ise Kawasaki [S-NGY, S-ISE]); Osaka hama frontage: kura-yashiki and merchant houses each with their own steps; "
               "Edo kashi: an open public strip with sheds and kura set back. Laundry is not done in city canals (tidal, dirty).",
  "boats": "chokibune, yanebune, hiratabune (flat cargo lighter), tenmasen; yakatabune as a rare hero (OUTDOOR_LIST U boats, section 7.14).",
  "abandoned": "Water brown-green; a mud-and-silt shelf exposed along the wall foot; a hirata sunk with only its gunwale showing; a chokibune swamped against the gangi; "
               "a flotsam raft of planks, straw bales and leaves jammed against a bridge pier; one landing stage with half its planks gone; weeds in every wall joint and a green algae band at the waterline; "
               "one pile-and-board section slumped into the water.",
  "terrain": "Channel cut (bed below sea level where the town is coastal), the quay strip as flat hard ground, bridge-end plazas (hashi-zume).",
  "placeable": "Wall modules, gangi, landing stages, mooring posts and stones, outfalls, bridges, boats, debris.",
  "water": "SEA: coastal canal towns sit at 1-3 m above sea level and their canals are cut below 0 m, so the ocean fills them for free (FEASIBILITY 2.3). Inland a3 (Ise Kawasaki, Fushimi) needs pond models.",
  "refs": ["l01", "l02", "l07", "l08", "l14", "l10"],
 },
 {
  "code": "b", "water_short": "pond (or a dry bed with puddles)", "name": "Shallow town canal (Takase type)",
  "what": "A narrow, very shallow cargo canal with flat boats hauled back upstream by men walking the bank, and side basins (funairi) cut into one bank "
          "where boats turned and unloaded. Kyoto's Takase (1611, Nijo to Fushimi, ~10 km) is the model.",
  "variants": ["b1 Takase: stone-walled, 7-8 m, funairi basins", "b2 moat-canal: a castle-town canal of the same scale doubling as a moat (Ogaki's Suimon-gawa to the Funamachi port)"],
  "cross_section": [
   ["channel width", "7-8 m", "Takase channel ~8 m, water ~7 m wide [S-TAK]"],
   ["water depth", "~0.3 m normal", "'a few tens of cm'; normal depth about 30 cm [S-TAK]"],
   ["bank height", "1.0-1.5 m (assumed)", "house backs and a towpath just above water; boats are flat and low"],
   ["towpath", "1.5-2.0 m (assumed)", "haulers (hikiko, ~700 at the peak) walked the bank pulling on a rope [S-TAK]"],
   ["funairi basin", "~100 x 11 m (55 x 6 ken), stone-walled", "Ichi-no-funairi; another record gives 134 x 16 m; 9 basins between Nijo and Shijo, about every 100 m, on the west bank [S-TAK]"],
   ["boat", "~13 x 2 m, flat-bottomed, max 15 koku (~2.25 t)", "takasebune; ~200 boats at the peak [S-TAK]"]],
  "edges": "Stone-walled both sides (the funairi are recorded as stone-walled [S-TAK]); rough stone where it runs out of town.",
  "steps_landings": "Short gangi and plank landings inside each funairi; a few steps at the house backs.",
  "mooring": "Posts inside the funairi; boats tied bow to stern along the towpath side.",
  "outfalls": "Small drain mouths from the houses.",
  "bridges": "Many short, low plank bridges (one per street crossing); stone slab bridges where it is narrow.",
  "planting": "Willows along the towpath (assumed); NO cherry rows (the Kiyamachi and Ogaki cherry rows are modern Somei-yoshino).",
  "buildings": "House backs and inns straight onto the water on the east bank; timber, charcoal and rice merchants' yards at each funairi.",
  "boats": "takasebune (flat, 13 x 2 m); the local boat type OUTDOOR_LIST 7.14 lost, back in as a length variant of the flat cargo boat.",
  "abandoned": "With no one keeping the intake weir, the 0.3 m of water drops to a trickle between gravel and silt bars; takasebune lie grounded and tilted; the funairi basins are silted, reed-choked and hold standing water; "
               "a hauling rope still tied to a post; leaves pile against every low bridge.",
  "terrain": "Shallow channel cut, the funairi cuts, the towpath strip.",
  "placeable": "Wall modules (low heights), funairi corner pieces (= wall modules), gangi, landing, plank and slab bridges, boats.",
  "water": "POND: Kyoto is inland and uphill. The trickle state is cheap: a thin stepped pond strip, or even a dry gravel bed with puddles.",
  "refs": [],
 },
 {
  "code": "c", "water_short": "pond; sea at river mouths", "name": "Big river through or beside a town",
  "what": "The river a town grew beside: gravel flats (kawara), earth levees (tsutsumi) with planting, a long bridge or a ferry, and river works.",
  "variants": [
   "c1 levee-banked lowland river: Kamo, Sumida, Yodo, Yahagi, Tama, Sagami, Kiso: long bridge or ferry, levees with roads on top",
   "c2 braided gravel river, unbridged: Oi, Abe, Sakawa, Fuji, Tenryu, Kamanashi: a wide stony bed with shifting channels, crossed by porters or ferry",
   "c3 town river: a 20-60 m river through a post or castle town, one trestle or plank bridge, gravel bars (Totsuka's Kashio, Fujieda's Seto)"],
  "cross_section": [
   ["c1 channel between levees", "~100 m (Kamo) to 150-200 m (Sumida, assumed)", "the 1670 Kanbun new levee narrowed the Kamo to about 100 m, straightened it and faced it in stone [S-KAMO]"],
   ["c1 low-water channel", "30-60 m (assumed)", "autumn low water leaves wide gravel and sand flats (kawara) [OL U water]"],
   ["c1 levee", "3-5 m high, crest 4-8 m (assumed)", "grass and planted crest; a road on top where the levee is the road (Bunroku levee, Yodo; mem)"],
   ["c1 bridges", "Sanjo Ohashi 61 x 3 ken (~109 x 5.5 m, 1780 record), stone piers; Yahagi-bashi 208 ken (~378 m), the Tokaido's longest", "[S-KAMO] [S-YAH]"],
   ["c2 bed", "0.5-1.5 km wide, 2-5 channels of 10-60 m (assumed)", "Oi, Abe, Sakawa forded on porters' shoulders; bridges forbidden [OL N 'Braided gravel river', W 4]"],
   ["c2 channel depth", "knee to chest at low water (assumed)", "the reason porters (and river stops, kawa-dome) existed"],
   ["c3 bed / channel", "20-60 m bed, 5-20 m low-water channel, banks 2-4 m (assumed)", "Hokusai 1804 and Hiroshige Tokaido views [l04, l05]"]],
  "edges": "Earth levees with turf; stone-faced reaches in cities (Kamo, 1670); stone-filled bamboo gabions (jakago) along banks and round weirs; timber crib spurs (seigyu) and groynes pushing the current off the bank; "
           "open staggered levees (kasumi-tei) on c2 rivers; Shingen-zutsumi at Nirasaki is an old survivor [OL W 12].",
  "steps_landings": "Earth steps with log risers down the levee [l09]; ferry landings (earth or stone ramp, bell post, waiting bench); porter platforms (rendai) and the river-crossing office on c2; a boat landing at river ports (Kuragano, Fushimi, Hirakata).",
  "mooring": "Stakes in the gravel; boats hauled up on the flats.",
  "outfalls": "Town drains and irrigation outlets through the levee (small sluices).",
  "bridges": "KEEP_CIVIC trestle bridge at hero length (Sanjo, Yahagi, Ryogoku, Seta, Uji); plank bridges on c3; boat bridge as a rare hero; NONE on c2 (ferry or porters). Stone abutments left standing where a flood took the deck [OL U bridges parts].",
  "planting": "Levee crests: black or red pine rows, bamboo groves as flood protection, and on the Sumida levee the cherries planted in 1717 under Yoshimune [S-SUMI] (wild types: yamazakura / edohigan, never Somei-yoshino); "
              "willows and medake thickets at the water; reeds (yoshi) on the flats; bank willow.",
  "buildings": "Towns stand back behind the levee; tea stalls on the bridge-end plaza; riverbed shows and stalls on the kawara; houses on stilts over the water at Ryogoku [l14]; outcast hamlets on the flats (neutral).",
  "boats": "watashi-bune ferry; sanjikkoku-bune (17 x 2.5 m) on the Yodo [S-FSM]; kurawanka food boats at Hirakata; river cargo boats (takasebune) at Kuragano and Kajikazawa; timber rafts (ikada) on the Tenryu, Oi and Tama.",
  "abandoned": "Autumn low water; a ferry boat stranded high on the gravel, its rope still across the river; one or two bays of a long trestle bridge washed out, leaving pile stumps (a real chokepoint); "
               "flotsam piled against the piers; levee grass long and seeded; summer riverbed platforms (Kamo) left as stacked frames on the flats, never set out [S-YUKA]; a porter's platform tipped over on c2.",
  "terrain": "Levees, kawara gravel flats, braided channels, the bridge-end plaza. This is mostly [terrain].",
  "placeable": "Bridges, ferry landing, river-works kit (gabions, cribs, groynes), levee steps, boats, water-level post, debris, riverbed platform remains.",
  "water": "POND for every inland river (stepped pond segments; FEASIBILITY 2.3 says unproven). Rivers at their mouths (Sumida, Yodo at Osaka, Tama at Kawasaki) can be sea-level.",
  "refs": ["l04", "l05", "l06", "l09", "l14", "l01"],
 },
 {
  "code": "d", "water_short": "none (gutters, troughs); thin pond strips for d3", "name": "Street-side channel",
  "what": "Water that runs WITH the street: the stone gutter along house fronts in every town, a wider stone-lined street channel in some post towns, "
          "spring-fed streams through a town, hot-water gutters in spa towns.",
  "variants": [
   "d1 house-front gutter (omote-dobu): the default in every town; = the jp_s_gutter kit",
   "d2 street channel (yosui): a wider stone channel down the middle or one side of the street, with a slab bridge to each door (Nakatsugawa, Narai troughs, Tsumago, Magome)",
   "d3 spring stream: clear, cold, weedy spring water through town (Mishima, Samegai, Tarui)",
   "d4 hot-water gutter: steaming gutters and troughs in spa towns",
   "d5 plot stream: a small stream crossing each long plot behind the street frontage (Kamiyoshida's Yana-gawa, where pilgrims purified before entering the oshi house)"],
  "cross_section": [
   ["d1 gutter", "0.30 wide x 0.25-0.30 deep, stone-lined, 0.3 m outside the house line", "jp_s_gutter build list (outdoor kit, W1); Morse figs 33-34 show the stone edge and a slab or board at each door [m033, m034]"],
   ["d2 street channel", "0.6-1.2 m wide x 0.4-0.6 m deep (assumed)", "Nakatsugawa's channel ran down the centre of the street, fed from the Kurosawa River for fire water; washing in it was forbidden; filled in 1880 [S-NKT]"],
   ["d2 spring troughs", "stone or hollow-log troughs, roofed at Narai", "Narai's spring water stations along the street, for drinking and fire [S-NRI]"],
   ["d3 spring stream", "2-6 m wide x 0.3-0.8 m deep (assumed)", "Mishima's Genbei-gawa, a late-16th-c. channel from Kohama pond, 1.5 km [S-MSM]; Samegai's Jizo-gawa runs ~500 m along the street, ~14 C all year, with baikamo waterweed [S-SMG]"],
   ["d4 hot-water gutter", "0.3-0.6 m troughs (assumed)", "spa-town form; Kusatsu's big trough field (yubatake) needs a date check"],
   ["d5 plot stream", "0.5-1.0 m (assumed)", "Kamiyoshida: Yana-gawa fed from the Sengen shrine; 86 oshi houses on ~750 m of road at the peak [S-KYD]"]],
  "edges": "Dressed or rough stone lining; field-stone edges in villages; timber boards on alley drains (dobu-ita).",
  "steps_landings": "d2/d3: two or three stone steps down to the water at intervals (dipping and washing where allowed); stepping stones across d3.",
  "mooring": "None.",
  "outfalls": "d1 ends in an outfall into a canal, river or ditch (jp_s_gutter _outfall).",
  "bridges": "Stone slab footbridge (1-3 slabs; Morse 268-270) at every door; a plank bridge where a cart crosses d2/d3; gutter slabs on d1.",
  "planting": "Mostly none; a willow at a corner; baikamo and watercress in d3.",
  "buildings": "House fronts face the channel; troughs at the inn doors; on d5 the channel crosses each plot in front of the house.",
  "boats": "None.",
  "abandoned": "Silted to half depth with leaves and mud; grass in the joints; a slab tipped into the channel; d2 channels dry or trickling because no one clears the intake (puddles where the silt dams it); "
               "a trough overflowing into the street and a wet patch; d3 keeps flowing (springs don't stop) and grows a thick green weed; d4 still steams, with sulphur crust.",
  "terrain": "The ditch the pieces sit in (a terrain cut or a baked groove); d3 needs a shallow terrain channel.",
  "placeable": "Gutter pieces (existing kit), wider channel pieces, slab bridges, steps, troughs, spring basins.",
  "water": "Mostly NO water surface needed: d1/d2 are dry or a decal film. d3 needs thin pond strips (clear-water material). d4: steam particles over a wet decal.",
  "refs": ["m033", "m034", "m268", "m269", "m270", "m066"],
 },
 {
  "code": "e", "water_short": "thin pond strips, or dry beds with pools", "name": "Village stream / irrigation channel",
  "what": "The water every farm village lives on: the main irrigation channel (yosui) threading past the houses from a weir, field ditches, "
          "and in the hills a boulder stream with bamboo pipes and log bridges.",
  "variants": [
   "e1 lowland: earth-banked irrigation channel, river-stone lined where it passes the houses, sluices, a weir upstream, wash steps",
   "e2 mountain: boulder stream in a narrow valley, dry-stone terraces, bamboo pipes (kakehi) to each house, log and slab bridges"],
  "cross_section": [
   ["e1 main channel", "1-3 m wide x 0.4-1.0 m deep (assumed)", "earth or stone-lined channel from a weir through the village; also used for washing [OL R 2]"],
   ["e1 field ditch", "0.3-0.6 m (assumed)", "[OL R 2]"],
   ["e1 bank at the houses", "0.5-1.0 m, river stones (assumed)", "'a channel walled with river stones where it passes the houses, with a step down to the water at each house' [OL R 2]"],
   ["wash step (arai-ba)", "2-4 steps down to a slab at water level, 0.9-1.8 m wide (assumed)", "half-ken or one ken wide; one per house or shared"],
   ["e2 stream", "3-15 m boulder bed, pools and riffles (assumed)", "[OL N U 'Mountain torrent']"]],
  "edges": "Earth banks with grass; river-stone or field-stone walls near houses; stake-and-wattle (shigarami) on bends; gabions (jakago) at the weir.",
  "steps_landings": "Wash steps (arai-ba) at each house or group; a wooden board-on-posts platform variant; stepping stones.",
  "mooring": "None (a paddy punt, ta-bune, in delta villages).",
  "outfalls": "Paddy water notches (mizu-kuchi) and field sluices.",
  "bridges": "Stone slab footbridge (Morse 268: two slabs set side by side but offset, on stone posts), log bridge, earth-covered bridge (dobashi) for carts, plank bridge.",
  "planting": "Alders and willows along the paddy bunds (the alder lines carry the autumn hasa racks); bamboo groves behind the farms; persimmon by the house; reeds and water celery in the ditch; red spider lilies on the bunds in autumn (flora list, verify).",
  "buildings": "Farmhouses sit a few metres back with a wash step, wash tubs and buckets on stakes; the Omi kabata (spring house-basin, Harie) is a lake-shore flavour whose start date is unknown [S-HARIE]: flavour only, flag.",
  "boats": "Paddy punt (ta-bune) in delta and wajuu villages only.",
  "abandoned": "Channel choked with weeds and fallen leaves; sluice boards jammed half-open and the field below flooded into a reed marsh (or the paddies dry, harvested stubble); "
               "a broken bucket and a rotting wash tub on the wash step; one slab bridge tipped; a treadwheel collapsed on the bank; the weir breached at one end.",
  "terrain": "Channel cut, paddy terraces, bunds, the weir pool. Mostly [terrain].",
  "placeable": "Sluice (3 sizes), weir, wash steps, slab and log bridges, stepping stones, bamboo pipe, water lifting (lever sweep, treadwheel), wattle revetment.",
  "water": "POND strips for the main channel only; field ditches are wet-mud texture. Mountain streams: stepped pond segments or dry boulder beds with pools.",
  "refs": ["m268", "m269", "m052"],
 },
 {
  "code": "f", "water_short": "pond; sea for coastal castles", "name": "Castle moat",
  "what": "The wet or dry moat round a castle, the one waterway every castle town shares.",
  "variants": [
   "f1 wet moat: stone wall on the castle side, earth bank or low stone on the town side",
   "f2 dry moat: hill castles and spurs (Komoro, Iida, Takato, Inuyama; Nagoya's honmaru)",
   "f3 concentric round moats: Tanaka only (four rings, ~600 m across) [S-TNK]"],
  "cross_section": [
   ["f1 width", "20 m typical; 35-50 m big; 70-100 m+ Osaka outer", "Himeji: average 20 m, max 34.5 m [S-HMJ]; Matsumoto up to ~50 m [S-MTM]; Osaka's outer moat passed 100 m at its widest [S-HMJ page]"],
   ["f1 water depth", "~2-3 m", "Himeji ~2.7 m [S-HMJ]"],
   ["f1 castle-side wall", "stone 5-15 m (assumed range)", "Edo outer moat wall ~6 m [S-EDOM]; Iga Ueno's is famously ~30 m (mem, verify)"],
   ["f1 town side", "turfed earth bank 2-4 m with a low stone or wattle toe (assumed)", "Hiroshige's Soto-sakurada Benkeibori [l11]"],
   ["f2 dry moat", "10-20 m wide x 5-10 m deep (assumed)", "hill castles"]],
  "edges": "Ishigaki (KEEP_CIVIC stone rampart; nozura / uchikomi-hagi / kirikomi-hagi as 3 materials, OL 7.17); 'belt' walls (koshimaki / hachimaki: an earth rampart with a stone band at the foot or the top, Edo and Hikone, mem); earth ramparts with turf and pines.",
  "steps_landings": "Few: a moat-side horse-washing slope (uma-arai-ba) and a boat landing for moat patrol boats (assumed).",
  "mooring": "One or two posts (assumed).",
  "outfalls": "Water gates (sluices) between moat levels; moat dams (dote-bashi) with a path on top [OL U castle].",
  "bridges": "Earth bridge (dobashi) or plank bridge to each gate (KEEP_CIVIC), sometimes a covered corridor bridge.",
  "planting": "Pines on the rampart crest and leaning over the water [l11]; lotus in the moat (brown and broken in autumn); reeds in the corners; willow on the town-side bank.",
  "buildings": "Castle walls, turrets and tamon on top; samurai houses behind board walls on the town side; a guard hut at each gate.",
  "boats": "A small patrol or maintenance punt (assumed; one per moat).",
  "abandoned": "Algae-green still water; dead lotus stalks and brown leaves; reeds spreading from the corners; the plank gate bridge rotten with gaps; a punt sunk at the landing; one ishigaki face bulging with a slump of fallen stones.",
  "terrain": "The moat basin, earth ramparts, the berm (inu-bashiri). Mostly [terrain].",
  "placeable": "Ishigaki faces (castle kit), earth-bridge ends, plank bridge, water gate, lotus / reed clutter, punt.",
  "water": "SEA for coastal castles (Kuwana, Osaka, Edo's lower moats); a lake pond where the moat joins a lake (Zeze, Hikone); POND for every other wet moat (flat, one level per moat: the easy case).",
  "refs": ["l11", "l16"],
 },
 {
  "code": "g", "water_short": "sea; lake ponds", "name": "Shore landing (harbour, beach, lake shore)  [NEW TYPE]",
  "what": "Added because 30+ settlements are ports, fishing villages, salt beaches and lake towns: their water is the sea or a lake, not a canal or river. "
          "Kept small: it reuses the canal-edge kit and the shore kit.",
  "variants": [
   "g1 harbour quay: stone quay wall, gangi, stone jetty, mooring stones, lighthouse lantern (ports, Miya, Kuwana, Uraga)",
   "g2 beach landing: sand or shingle with boats on skids, capstan, net racks (fishing and salt villages)",
   "g3 lake shore: landing ramp, ferry, jetty on a lake (Lake Biwa, Ashi, Hamana, Suwa)"],
  "cross_section": [
   ["g1 quay wall", "1.5-3.0 m above high water (assumed)", "same wall modules as a1"],
   ["g1 jetty (hatoba)", "5-10 m wide, 20-60 m long (assumed)", "stone-faced earth pier"],
   ["lighthouse lantern", "~8 m wooden tower lantern at Ogaki's river port (1688-1704)", "[S-OGK]; = KEEP_CIVIC lighthouse lantern"],
   ["g2 beach", "boats drawn up 10-30 m above the waterline (assumed)", "setting kit 'fishing village' [OL 4]"]],
  "edges": "Dressed stone quays; rough stone breakwaters; natural beach.",
  "steps_landings": "Gangi (parallel flights along the quay), stone ramps (boat slips), plank jetties on lakes.",
  "mooring": "Mooring stones and posts; channel stakes (miotsukushi) marking the fairway.",
  "outfalls": "River or canal mouth.",
  "bridges": "None on the shore itself.",
  "planting": "Coastal black-pine belt; reeds on lake shores.",
  "buildings": "Warehouses and boat sheds; houses gable-end to the beach in fishing villages.",
  "boats": "Fishing boats and beached boats (shore kit), tenmasen lighters, ferry boats; big cargo ships at anchor as landmarks.",
  "abandoned": "Boats hauled up and left to rot or overturned; a swamped boat at the quay; nets rotted on the racks; driftwood and wrack piled on the quay steps; the lantern's paper gone.",
  "terrain": "Beach, quay platform, harbour basin. Mostly [terrain].",
  "placeable": "Wall modules, gangi, mooring kit, lighthouse lantern, jetty, boats and shore kit (KEEP_OUTDOOR 'Shore and salt').",
  "water": "SEA for coast; POND (lake) for Biwa / Ashi / Suwa; Hamana is brackish and joined to the sea since 1498, so SEA-level works.",
  "refs": ["l01"],
 },
]

# Parts: status = kit (in parts/manifest.json or the outdoor core kit build list), catalogued (named in a KEEP list or
# OUTDOOR_LIST 7.x but no build list yet), new (in no list, or only as a [terrain] tag).
PARTS = [
 {"id": "jp_s_ww_wall_dressed", "name": "Dressed-stone canal / quay wall module", "status": "catalogued",
  "xref": "OUTDOOR_LIST 7.14 canal-edge kit 'stone wall section'; not in KEEP_CIVIC (its 'stone rampart' is castle scale)",
  "sizes": "1 ken (1.82 m) long; heights 1.5 / 2.5 / 3.5 m; batter 1:0.1-0.2",
  "variants": "straight, outer corner, inner corner, end, with a gangi notch, with an outfall block; ABANDONED: bulged / slumped with fallen stones and exposed sill logs",
  "types": ["a", "b", "f", "g"], "materials": "jp_m_stone_cut + new wet-stone waterline band + jp_m_decal_moss"},
 {"id": "jp_s_ww_wall_rough", "name": "Rough-stone (nozura / river-stone) bank wall module", "status": "new",
  "xref": "OUTDOOR_LIST R 2 'stone-lined village channel' ([terrain] + stone); the small sibling of the castle ishigaki",
  "sizes": "1 ken long; heights 0.8 / 1.5 / 2.5 m; batter 1:0.3",
  "variants": "straight, corner, end, with a wash-step notch; ABANDONED: a few stones fallen out, grass on top",
  "types": ["a", "c", "d", "e", "f"], "materials": "jp_m_stone_field / jp_m_stone_river"},
 {"id": "jp_s_ww_rev_timber", "name": "Timber revetment: pile-and-board (kui-dome) and stake-and-wattle (shigarami)", "status": "new",
  "xref": "OUTDOOR_LIST U water 'timber-piled embankment' is tagged [terrain] only; Hiroshige's Onagi-gawa shows it [l08]",
  "sizes": "1 ken long; pile-and-board 1.0 / 1.8 m high, posts ~0.15 m every half ken; wattle 0.6 m",
  "variants": "boards, wattle; ABANDONED: leaning, boards missing, piles snapped",
  "types": ["a", "c", "e"], "materials": "jp_m_wood_weathered (wet, dark lower third), jp_m_bamboo_weathered"},
 {"id": "jp_s_ww_gangi", "name": "Quay steps (gangi)", "status": "catalogued",
  "xref": "KEEP_CIVIC civic 11; OUTDOOR_LIST 7.14",
  "sizes": "flights parallel to the wall or square to it; 1.8 / 2.7 m wide; rise to match 1.5 / 2.5 / 3.5 m walls; rise ~0.2, tread ~0.35 (assumed)",
  "variants": "parallel, perpendicular, funairi corner; ABANDONED: silted bottom steps, slime, one tread missing",
  "types": ["a", "b", "g"], "materials": "jp_m_stone_cut"},
 {"id": "jp_s_ww_landing", "name": "Plank landing stage on piles (sanbashi)", "status": "new",
  "xref": "not in any list; seen in Edo canal prints [l02]",
  "sizes": "1 x 2 ken and 1 x 4 ken; deck 0.3-0.6 m above water",
  "variants": "intact, half-planked (ABANDONED), collapsed at one end",
  "types": ["a", "b", "c", "g"], "materials": "jp_m_wood_weathered"},
 {"id": "jp_s_ww_washstep", "name": "Wash step (arai-ba)", "status": "new",
  "xref": "BL mentions only (public wash place, Omi kabata); OUTDOOR_LIST R 2 'step down to the water at each house'",
  "sizes": "half ken and 1 ken wide; 2-4 steps to a slab at the water",
  "variants": "stone (set in a rough wall or an earth bank), timber board-on-posts; ABANDONED: tub and broken bucket left on it, slab tilted",
  "types": ["d", "e"], "materials": "jp_m_stone_field; reuses jp_p_found_step_natural / _cut shapes"},
 {"id": "jp_s_ww_mooring", "name": "Mooring post and mooring stones", "status": "catalogued",
  "xref": "OUTDOOR_LIST 7.14, seam S147",
  "sizes": "post 0.2 m thick, 1.5 / 2.5 / 3.5 m; holed stone block for the wall top; free-standing stone",
  "variants": "upright, leaning (ABANDONED), with a rope end",
  "types": ["a", "b", "c", "g"], "materials": "jp_m_wood_weathered, jp_m_stone_cut"},
 {"id": "jp_s_ww_outfall", "name": "Drain outfall set in a wall", "status": "catalogued",
  "xref": "OUTDOOR_LIST 7.14 'outfall' and U streets 'drain outfall into canal'; the gutter-end piece jp_s_gutter _outfall already exists (kit, W1)",
  "sizes": "0.3 and 0.6 m mouths in a 1-ken wall block",
  "variants": "dressed, rough; ABANDONED: stain streak and a dead-leaf plug",
  "types": ["a", "b", "c", "f", "g"], "materials": "jp_m_stone_cut"},
 {"id": "jp_s_ww_slabbridge", "name": "Stone slab footbridge (ishi-bashi)", "status": "catalogued",
  "xref": "OUTDOOR_LIST 7.6 kit 3 (seam S073), not among KEEP_CIVIC's five bridges; jp_s_gutter _slab (kit) covers only the 0.3 m gutter",
  "sizes": "1 slab 0.9-1.8 m; 2 slabs end to end on a stone post up to ~3.6 m (Morse: a single 10-12 ft slab [m269]); 2 slabs side by side but offset [m268]",
  "variants": "single, double on post, offset pair, slab + stepping stones; ABANDONED: one slab tipped into the water",
  "types": ["d", "e", "b"], "materials": "jp_m_stone_cut / jp_m_stone_field"},
 {"id": "civic_plank_bridge", "name": "Plank bridge (KEEP_CIVIC 1)", "status": "catalogued",
  "xref": "KEEP_CIVIC civic 1; OUTDOOR_LIST 7.6 kit 1 (scales from gutter plank to Nihonbashi)", "sizes": "1-ken bays, 3-30 m",
  "variants": "with / without railings; ABANDONED: missing deck boards, one rail down", "types": ["a", "b", "c", "e", "f"], "materials": "-"},
 {"id": "civic_trestle_bridge", "name": "Trestle bridge (KEEP_CIVIC 5)", "status": "catalogued",
  "xref": "KEEP_CIVIC civic 5; the hero lengths are KEEP_LANDMARKS famous bridges", "sizes": "Sanjo ~109 m, Yahagi ~378 m",
  "variants": "ABANDONED: 1-2 bays washed out, stumps left", "types": ["a", "c"], "materials": "-"},
 {"id": "civic_arched_bridge", "name": "Arched bridge (KEEP_CIVIC 2)", "status": "catalogued", "xref": "KEEP_CIVIC civic 2",
  "sizes": "-", "variants": "-", "types": ["a"], "materials": "-"},
 {"id": "civic_earth_bridge", "name": "Earth-covered bridge (KEEP_CIVIC 3)", "status": "catalogued", "xref": "KEEP_CIVIC civic 3",
  "sizes": "-", "variants": "-", "types": ["e", "f"], "materials": "-"},
 {"id": "civic_boat_bridge", "name": "Boat bridge (KEEP_CIVIC 4)", "status": "catalogued", "xref": "KEEP_CIVIC civic 4",
  "sizes": "-", "variants": "-", "types": ["c"], "materials": "-"},
 {"id": "civic_ferry_landing", "name": "Ferry landing + bell post (KEEP_CIVIC 10)", "status": "catalogued", "xref": "KEEP_CIVIC civic 10; OUTDOOR_LIST W 4",
  "sizes": "-", "variants": "ABANDONED: ferry stranded on the gravel, rope across the river", "types": ["c", "g"], "materials": "-"},
 {"id": "civic_sluice", "name": "Sluice / water gate (KEEP_CIVIC 8)", "status": "catalogued",
  "xref": "KEEP_CIVIC civic 8; OUTDOOR_LIST 7.5 'boards in a frame' at 3 sizes (field notch, channel gate, canal / moat water gate); tide gate = the big size",
  "sizes": "3 sizes", "variants": "open, shut, ABANDONED jammed half-open", "types": ["a", "d", "e", "f"], "materials": "-"},
 {"id": "civic_weir", "name": "Weir (KEEP_CIVIC 9)", "status": "catalogued", "xref": "KEEP_CIVIC civic 9; OUTDOOR_LIST R 2 stone-and-timber and brushwood-and-stake",
  "sizes": "-", "variants": "ABANDONED: breached at one end", "types": ["b", "c", "e"], "materials": "-"},
 {"id": "civic_lighthouse_lantern", "name": "Lighthouse lantern (KEEP_CIVIC 12)", "status": "catalogued", "xref": "KEEP_CIVIC civic 12; Ogaki Sumiyoshi lantern ~8 m",
  "sizes": "-", "variants": "-", "types": ["g", "b"], "materials": "-"},
 {"id": "river_works_kit", "name": "River-works kit: bamboo gabion (jakago), crib spur (seigyu), groyne", "status": "catalogued",
  "xref": "OUTDOOR_LIST 7.5 '1 river-works kit'; KEEP_OUTDOOR 'wells, water control, river works' (15)",
  "sizes": "crib ~6 x 4 m [OL W 12]", "variants": "ABANDONED: gabion split, stones spilled", "types": ["c", "e"], "materials": "-"},
 {"id": "crossings_unbuilt", "name": "Stepping stones, log bridge, marked ford stakes", "status": "catalogued",
  "xref": "KEEP_OUTDOOR 'bridges and crossings (unbuilt)' (8); OUTDOOR_LIST W 4",
  "sizes": "-", "variants": "-", "types": ["d", "e", "c"], "materials": "-"},
 {"id": "boats_set", "name": "Boats: chokibune, yanebune, flat cargo boat (hirata 2 lengths incl. the 13 x 2 m takasebune), sanjikkoku-bune, ferry", "status": "catalogued",
  "xref": "OUTDOOR_LIST 7.14 boats; KEEP_OUTDOOR 'canals and boats' (8); fishing boats are in the shore kit",
  "sizes": "takasebune 13 x 2 m [S-TAK]; sanjikkoku-bune 17 x 2.5 m [S-FSM]",
  "variants": "each hull x 3 dead states: moored-swamped, sunk to the gunwale, stranded / overturned", "types": ["a", "b", "c", "f", "g"], "materials": "jp_m_wood_weathered"},
 {"id": "jp_s_ww_debris", "name": "Flotsam and debris: planks, straw bales, reed, leaf mats", "status": "new",
  "xref": "not in any list", "sizes": "pier-jam pile 2-4 m; floating leaf-mat decal",
  "variants": "at a pier, at a weir, at a grate", "types": ["a", "b", "c", "d", "e"], "materials": "jp_m_ground_leaf_litter (new, outdoor kit), jp_m_straw_stack"},
 {"id": "jp_s_ww_trough", "name": "Street water trough and spring basin", "status": "catalogued",
  "xref": "setting kits 'horse / animal trough (mizu-bune)'; OUTDOOR_LIST R 2 spring pool with stone surround",
  "sizes": "log trough 2-3 m; stone basin 1 m; roofed variant (Narai)", "variants": "ABANDONED: overflowing, leaf-filled",
  "types": ["d"], "materials": "jp_m_wood_weathered, jp_m_stone_field"},
 {"id": "kakehi", "name": "Bamboo pipe on forked sticks (kakehi)", "status": "catalogued", "xref": "OUTDOOR_LIST R 2 (seam S068)",
  "sizes": "-", "variants": "ABANDONED: split, dripping", "types": ["d", "e"], "materials": "-"},
 {"id": "water_lifting", "name": "Water lifting: lever sweep, treadwheel, river lift wheel (Yodo castle wheel = hero, 8 ken across)", "status": "catalogued",
  "xref": "OUTDOOR_LIST 7.5 (3 props); the lever sweep = jp_s_well_hanetsurube (kit, W1) field variant; Yodo wheels [S-YODO]",
  "sizes": "Yodo wheels 8 and 6 ken diameter", "variants": "ABANDONED: wheel stopped, paddles missing", "types": ["c", "e", "f"], "materials": "-"},
 {"id": "jp_s_ww_levee_steps", "name": "Levee steps (earth treads with log risers)", "status": "new",
  "xref": "variant of jp_s_stone_steps (kit, W2); seen on the Sumida levee [l09]",
  "sizes": "0.9-1.8 m wide, 4-12 risers", "variants": "log risers, stone risers; ABANDONED: risers rotted, treads washed out",
  "types": ["c", "f"], "materials": "jp_m_wood_weathered, ground"},
 {"id": "yuka_remains", "name": "Riverbed platform remains (noryo-yuka), stacked for winter", "status": "catalogued",
  "xref": "OUTDOOR_LIST U water 'summer riverbed platforms'; not in KEEP_OUTDOOR: optional", "sizes": "benches ~2 x 1 m, platforms 1 x 2 ken",
  "variants": "stacked frames, one collapsed", "types": ["c"], "materials": "jp_m_wood_weathered, jp_m_reed_yoshizu"},
 {"id": "water_level_post", "name": "Water-level post and flood mark", "status": "catalogued", "xref": "OUTDOOR_LIST U water; W 12",
  "sizes": "-", "variants": "-", "types": ["c"], "materials": "-"},
 {"id": "gutter_kit", "name": "Street gutter kit (jp_s_gutter)", "status": "kit",
  "xref": "research/outdoor_kit build list item 10 (W1): stone run, half, corner, slab, dobu-ita, outfall, earth, silted",
  "sizes": "0.30 x 0.25-0.30 m", "variants": "ADD for d2: 0.6 / 1.2 m wide channel runs + a 1-slab bridge piece", "types": ["d"], "materials": "-"},
 {"id": "kit_reuse", "name": "Reused building parts", "status": "kit",
  "xref": "parts/manifest.json: jp_p_found_step_natural / _cut (wash-step and landing slabs), jp_p_found_dodai_stones_rough / _dressed (kura sills on a canal wall), jp_p_wall_okabe_kura, jp_p_wall_namako_imo / _shihan, jp_p_open_kura_door_* (kura backs with water doors); jp_s_stone_steps (outdoor kit W2), jp_s_oke, jp_s_laundry_pole, jp_s_well_* (outdoor kit W1)",
  "sizes": "-", "variants": "-", "types": ["a", "d", "e"], "materials": "-"},
]
