// JP_Buildings - buildings assembled from the JP parts library (japan_dev/buildings/*).
// GENERATED by japan_dev/buildings/machiya_t3_01/build.py - edit the generator, not this file.
class CfgPatches
{
	class JP_Buildings
	{
		units[]={};
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"DZ_Data",
			"DZ_Structures_Residential",
			"JP_Common"
		};
	};
};
class CfgVehicles
{
	class HouseNoDestruct;
	class Land_JP_Machiya_T3_01: HouseNoDestruct
	{
		scope=1;
		displayName="Machiya (tier 3)";
		model="\JP\buildings\machiya\jp_machiya_t3_01.p3d";
		class Doors
		{
			class DoorsTwin1
			{
				displayName="Entrance (street)";
				component="DoorsTwin1";
				soundPos="doorsTwin1_action";
				animPeriod=1;
				initPhase=0;
				initOpened=0.3;
				soundOpen="doorWoodSlideOpen";
				soundClose="doorWoodSlideClose";
				soundLocked="doorWoodSlideRattle";
				soundOpenABit="doorWoodSlideOpenABit";
			};
			class DoorsTwin2
			{
				displayName="Toriniwa -> zashiki";
				component="DoorsTwin2";
				soundPos="doorsTwin2_action";
				animPeriod=0.8;
				initPhase=0;
				initOpened=0.5;
				soundOpen="doorWoodSlideOpen";
				soundClose="doorWoodSlideClose";
				soundLocked="doorWoodSlideRattle";
				soundOpenABit="doorWoodSlideOpenABit";
			};
			class DoorsTwin3
			{
				displayName="Toriniwa -> mise";
				component="DoorsTwin3";
				soundPos="doorsTwin3_action";
				animPeriod=0.8;
				initPhase=0;
				initOpened=0.5;
				soundOpen="doorWoodSlideOpen";
				soundClose="doorWoodSlideClose";
				soundLocked="doorWoodSlideRattle";
				soundOpenABit="doorWoodSlideOpenABit";
			};
			class DoorsTwin4
			{
				displayName="Mise <-> zashiki";
				component="DoorsTwin4";
				soundPos="doorsTwin4_action";
				animPeriod=0.8;
				initPhase=0;
				initOpened=0.5;
				soundOpen="doorWoodSlideOpen";
				soundClose="doorWoodSlideClose";
				soundLocked="doorWoodSlideRattle";
				soundOpenABit="doorWoodSlideOpenABit";
			};
			class DoorsTwin5
			{
				displayName="Kitchen back door (yard)";
				component="DoorsTwin5";
				soundPos="doorsTwin5_action";
				animPeriod=1;
				initPhase=0;
				initOpened=0.3;
				soundOpen="doorWoodSlideOpen";
				soundClose="doorWoodSlideClose";
				soundLocked="doorWoodSlideRattle";
				soundOpenABit="doorWoodSlideOpenABit";
			};
			class DoorsTwin6
			{
				displayName="Kitchen -> storage";
				component="DoorsTwin6";
				soundPos="doorsTwin6_action";
				animPeriod=1;
				initPhase=0;
				initOpened=0.3;
				soundOpen="doorWoodSlideOpen";
				soundClose="doorWoodSlideClose";
				soundLocked="doorWoodSlideRattle";
				soundOpenABit="doorWoodSlideOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth
			{
				class Health
				{
					hitpoints=1000;
				};
			};
			class GlobalArmor
			{
				class Projectile
				{
					class Health
					{
						damage=0;
					};
					class Blood
					{
						damage=0;
					};
					class Shock
					{
						damage=0;
					};
				};
				class Melee
				{
					class Health
					{
						damage=0;
					};
					class Blood
					{
						damage=0;
					};
					class Shock
					{
						damage=0;
					};
				};
				class FragGrenade
				{
					class Health
					{
						damage=0;
					};
					class Blood
					{
						damage=0;
					};
					class Shock
					{
						damage=0;
					};
				};
			};
			class DamageZones
			{
				class DoorsTwin1
				{
					class Health
					{
						hitpoints=1000;
						transferToGlobalCoef=0;
					};
					componentNames[]=
					{
						"doorstwin1"
					};
					fatalInjuryCoef=-1;
					class ArmorType
					{
						class Projectile
						{
							class Health
							{
								damage=3;
							};
							class Blood
							{
								damage=0;
							};
							class Shock
							{
								damage=0;
							};
						};
						class Melee
						{
							class Health
							{
								damage=5;
							};
							class Blood
							{
								damage=0;
							};
							class Shock
							{
								damage=0;
							};
						};
						class FragGrenade
						{
							class Health
							{
								damage=10;
							};
							class Blood
							{
								damage=0;
							};
							class Shock
							{
								damage=0;
							};
						};
					};
				};
				class DoorsTwin2
				{
					class Health
					{
						hitpoints=1000;
						transferToGlobalCoef=0;
					};
					componentNames[]=
					{
						"doorstwin2"
					};
					fatalInjuryCoef=-1;
					class ArmorType
					{
						class Projectile
						{
							class Health
							{
								damage=3;
							};
							class Blood
							{
								damage=0;
							};
							class Shock
							{
								damage=0;
							};
						};
						class Melee
						{
							class Health
							{
								damage=5;
							};
							class Blood
							{
								damage=0;
							};
							class Shock
							{
								damage=0;
							};
						};
						class FragGrenade
						{
							class Health
							{
								damage=10;
							};
							class Blood
							{
								damage=0;
							};
							class Shock
							{
								damage=0;
							};
						};
					};
				};
				class DoorsTwin3
				{
					class Health
					{
						hitpoints=1000;
						transferToGlobalCoef=0;
					};
					componentNames[]=
					{
						"doorstwin3"
					};
					fatalInjuryCoef=-1;
					class ArmorType
					{
						class Projectile
						{
							class Health
							{
								damage=3;
							};
							class Blood
							{
								damage=0;
							};
							class Shock
							{
								damage=0;
							};
						};
						class Melee
						{
							class Health
							{
								damage=5;
							};
							class Blood
							{
								damage=0;
							};
							class Shock
							{
								damage=0;
							};
						};
						class FragGrenade
						{
							class Health
							{
								damage=10;
							};
							class Blood
							{
								damage=0;
							};
							class Shock
							{
								damage=0;
							};
						};
					};
				};
				class DoorsTwin4
				{
					class Health
					{
						hitpoints=1000;
						transferToGlobalCoef=0;
					};
					componentNames[]=
					{
						"doorstwin4"
					};
					fatalInjuryCoef=-1;
					class ArmorType
					{
						class Projectile
						{
							class Health
							{
								damage=3;
							};
							class Blood
							{
								damage=0;
							};
							class Shock
							{
								damage=0;
							};
						};
						class Melee
						{
							class Health
							{
								damage=5;
							};
							class Blood
							{
								damage=0;
							};
							class Shock
							{
								damage=0;
							};
						};
						class FragGrenade
						{
							class Health
							{
								damage=10;
							};
							class Blood
							{
								damage=0;
							};
							class Shock
							{
								damage=0;
							};
						};
					};
				};
				class DoorsTwin5
				{
					class Health
					{
						hitpoints=1000;
						transferToGlobalCoef=0;
					};
					componentNames[]=
					{
						"doorstwin5"
					};
					fatalInjuryCoef=-1;
					class ArmorType
					{
						class Projectile
						{
							class Health
							{
								damage=3;
							};
							class Blood
							{
								damage=0;
							};
							class Shock
							{
								damage=0;
							};
						};
						class Melee
						{
							class Health
							{
								damage=5;
							};
							class Blood
							{
								damage=0;
							};
							class Shock
							{
								damage=0;
							};
						};
						class FragGrenade
						{
							class Health
							{
								damage=10;
							};
							class Blood
							{
								damage=0;
							};
							class Shock
							{
								damage=0;
							};
						};
					};
				};
				class DoorsTwin6
				{
					class Health
					{
						hitpoints=1000;
						transferToGlobalCoef=0;
					};
					componentNames[]=
					{
						"doorstwin6"
					};
					fatalInjuryCoef=-1;
					class ArmorType
					{
						class Projectile
						{
							class Health
							{
								damage=3;
							};
							class Blood
							{
								damage=0;
							};
							class Shock
							{
								damage=0;
							};
						};
						class Melee
						{
							class Health
							{
								damage=5;
							};
							class Blood
							{
								damage=0;
							};
							class Shock
							{
								damage=0;
							};
						};
						class FragGrenade
						{
							class Health
							{
								damage=10;
							};
							class Blood
							{
								damage=0;
							};
							class Shock
							{
								damage=0;
							};
						};
					};
				};
			};
		};
	};
};
