// JapanTestIsland - 2048 m test world for the feudal Japan project (japan_dev/, spike T).
// GENERATED by japan_dev/spikes/T_terrain/build_world.py - edit the template there, not this file.
// Inherits ChernarusPlus for sky, weather, lighting, ambient life and sounds; overrides everything map-specific.
class CfgPatches
{
	class JP_Worlds_TestIsland
	{
		units[]={};
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"DZ_Data",
			"DZ_Surfaces",
			"DZ_Worlds_Chernarusplus_World"
		};
	};
};
class CfgWorldList
{
	class JapanTestIsland
	{
	};
};
class CfgWorlds
{
	class CAWorld;
	class ChernarusPlus;
	class JapanTestIsland: ChernarusPlus
	{
		description="Japan Test Island";
		worldName="JP\worlds\testisland\world\japantestisland.wrp";
		ceFiles="JP\worlds\testisland\ce";
		cutscenes[]={};
		// A missing navmesh is FATAL ("Unable to load navmesh", server dies - Stephen's first boot, 2026-09-27).
		// Until NavMeshGenerator has produced our own .nm, build_world.py points navmeshName at vanilla Livonia's
		// navmesh as a stopgap so the world boots; AI then paths on Livonia's mesh (wrong, irrelevant for dummies).
		// GenParams are the vanilla ones, ready for NavMeshGenerator - see spikes/T_terrain/REPORT.md.
		class Navmesh
		{
			navmeshName="\DZ\worlds\enoch\navmesh\navmesh.nm";
			filterIsolatedIslandsOnLoad=1;
			visualiseOffset=0;
			class GenParams
			{
				tileWidth=50;
				cellSize1=0.25;
				cellSize2=0.1;
				cellSize3=0.1;
				filterIsolatedIslands=1;
				seedPosition[]={1024,0,1024};
				class Agent
				{
					diameter=0.60000002;
					standHeight=1.5;
					crouchHeight=1;
					proneHeight=0.5;
					maxStepHeight=0.44999999;
					maxSlope=60;
				};
				class Links
				{
					class ZedJump387_050
					{
						jumpLength=1.5;
						jumpHeight=0.5;
						minCenterHeight=0.30000001;
						jumpDropdownMin=0.5;
						jumpDropdownMax=-0.5;
						areaType="jump0";
						flags[]={"jumpOver"};
						color=1728004096;
					};
					class ZedJump388_050
					{
						jumpLength=1.5;
						jumpHeight=0.5;
						minCenterHeight=-0.5;
						jumpDropdownMin=0.5;
						jumpDropdownMax=-0.5;
						areaType="jump0";
						flags[]={"jumpOver"};
						color=1725781248;
					};
					class ZedJump387_110
					{
						jumpLength=3.9000001;
						jumpHeight=1.1;
						minCenterHeight=0.5;
						jumpDropdownMin=0.5;
						jumpDropdownMax=-0.5;
						areaType="jump0";
						flags[]={"jumpOver"};
						color=1711308800;
					};
					class ZedJump420_160
					{
						jumpLength=4;
						jumpHeight=1.6;
						minCenterHeight=1.1;
						jumpDropdownMin=0.5;
						jumpDropdownMax=-0.5;
						areaType="jump0";
						flags[]={"jumpOver"};
						color=1711276287;
					};
					class ZedJump265_210
					{
						jumpLength=2.45;
						jumpHeight=2.5;
						minCenterHeight=1.8;
						jumpDropdownMin=0.5;
						jumpDropdownMax=-0.5;
						areaType="jump0";
						flags[]={"climb"};
						color=1721024723;
					};
				};
			};
		};
		// Hakone, Japan (the DEM patch). latitude: positive is SOUTH in this engine (Chernarus is -56)
		longitude=139.07;
		latitude=-35.19;
		startTime="10:00";
		startDate="5/4/2026";
		centerPosition[]={1024,1024,300};
		ilsPosition[]={1024,1024};
		ilsDirection[]={1,0.079999998,0};
		ilsTaxiIn[]={};
		ilsTaxiOff[]={};
		drawTaxiway=0;
		class SecondaryAirports
		{
		};
		// repeated from ChernarusPlus so binarize finds them even when it cannot resolve the base class
		soundMapAttenCoef=0.0099999998;
		class SoundMapValues
		{
			treehard=0.029999999;
			treesoft=0.029999999;
			bushhard=0;
			bushsoft=0;
			forest=1;
			house=0.30000001;
			church=0.5;
		};
		minTreesInForestSquare=10;
		minRocksInRockSquare=5;
		clutterGrid=1;
		clutterDist=125;
		noDetailDist=40;
		fullDetailDist=15;
		midDetailTexture="DZ\worlds\chernarusplus\data\middle_sat_mco.paa";
		terrainNormalTexture="JP\worlds\testisland\data\japantestisland_normal_nohq.paa";
		class UsedTerrainMaterials
		{
			material0="dz\surfaces\data\terrain\cp_grass.rvmat";
			material1="dz\surfaces\data\terrain\cp_grass_tall.rvmat";
			material2="dz\surfaces\data\terrain\cp_broadleaf_sparse1.rvmat";
			material3="dz\surfaces\data\terrain\cp_rock.rvmat";
			material4="dz\surfaces\data\terrain\cp_gravel.rvmat";
			material5="dz\surfaces\data\terrain\cp_dirt.rvmat";
		};
		class OutsideTerrain
		{
			satellite="JP\worlds\testisland\data\outside_sat_co.paa";
			enableTerrainSynth=0;
			class Layers
			{
				class Layer0
				{
					nopx="DZ\surfaces\data\terrain\cp_gravel_nopx.paa";
					texture="DZ\surfaces\data\terrain\cp_gravel_ca.paa";
				};
			};
		};
		class Grid
		{
			offsetX=0;
			offsetY=0;
			class Zoom1
			{
				zoomMax=0.15000001;
				format="XY";
				formatX="000";
				formatY="000";
				stepX=100;
				stepY=100;
			};
			class Zoom2
			{
				zoomMax=0.85000002;
				format="XY";
				formatX="00";
				formatY="00";
				stepX=1000;
				stepY=1000;
			};
			class Zoom3
			{
				zoomMax=1e+30;
				format="XY";
				formatX="0";
				formatY="0";
				stepX=10000;
				stepY=10000;
			};
		};
		class Names
		{
			class JP_Yard
			{
				name="Shiken-jima (test yard)";
				position[]={1024.0,1024.0};
				type="Village";
			};
			class JP_Summit
			{
				name="Hakone-dake";
				position[]={804.0,1492.0};
				type="Hill";
			};
			class JP_Canal
			{
				name="Unga";
				position[]={1446.0,903.0};
				type="Local";
			};
			class JP_Pond
			{
				name="Ike";
				position[]={800.0,905.0};
				type="Local";
			};
		};
	};
};
