#!/usr/bin/env python3
r"""assemble_config.py - ONE config assembler per multi-builder PBO (agent CA1, 2026-10-01).

  python tools/assemble_config.py [pbo ...] [--pack] [--check] [--list]

  pbo      jp_furniture | jp_site (default: both)
  (none)   merge every fragment of the PBO into config.cpp + model.cfg (+ generated scripts), CfgConvert-check them
  --pack   ... then pack src/JP/<area> (minus model.cfg, sidecars, fragments, md) -> ..\@Japan\addons\<pbo>.pbo
  --check  write nothing: report whether the files on disk equal what the fragments assemble to (exit 1 if stale)
  --list   the fragments of each PBO: builder, order, classes, models

Why: several builders feed one PBO (jp_furniture: B3a + B4, L1, S1, W2F; jp_site: B3b + W2/FP1/FX2, L2). Each used to
rewrite the WHOLE config.cpp from its own view of the registry, so rebuilding an older builder dropped the newer
builders' classes ("re-run W2F / L2 --pack afterwards"). Now every builder writes ONLY its own fragment
    src/JP/<area>/_frags/<builder>.json
and this assembler merges ALL fragments of the PBO. Rebuilding any builder alone never drops another builder's classes.

Fragment (JSON, written by the builder; tracked in git so the PBO can be assembled without the MLOD masters):
  {"pbo": "jp_furniture", "builder": "B3a", "writer": "spikes/B3a/build.py", "order": 10,
   "requiredAddons": ["DZ_Data", "JP_Common"],
   "classes": [{"group": "jp_f_kama (kitchen)", "class": "StaticObj_JP_F_Kama", "base": "HouseNoDestruct",
                "body": ["scope=1;", "displayName=\"Kama\";", "model=\"\\JP\\furniture\\kitchen\\jp_f_kama.p3d\";"]}],
   "models": ["jp_f_kama", ...],                      model.cfg CfgModels entries (class <p3d>: Default {};)
   "scripts": {"scripts\\4_World\\JP_Site\\jp_site_wells.c": ["class Land_X extends Well {};", ...]}}   optional
Merge rules: fragments in (order, builder) order, each fragment's entries in its own order (stable output);
requiredAddons = union in first-seen order; a class or model named by two fragments with the SAME base + body is kept
once, with a DIFFERENT base or body the assembler fails loudly (AssembleError) and writes nothing.
Builders call write_fragment() then assemble(); their pack() calls pack() here, which assembles first.
Never starts or stops the server, the game or any GUI program. A PBO locked by a running server is reported.
"""
import json
import os
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DEV = os.path.abspath(os.path.join(HERE, ".."))
ROOT = os.path.abspath(os.path.join(DEV, ".."))
TOOLS = r"C:\Program Files (x86)\Steam\steamapps\common\DayZ Tools\Bin"
CFGCONVERT = os.path.join(TOOLS, "CfgConvert", "CfgConvert.exe")
WORK = os.path.join(DEV, "data", "cfgasm")          # CfgConvert scratch + default PBO stage (git-ignored)
FRAG_DIR = "_frags"
PACK_IGNORE = ("model.cfg", "*.json", "*.md", "*.png", "*.log", FRAG_DIR)

_SITE_MODS = ("class CfgMods\n{\n\tclass JP_Site\n\t{\n\t\tdir=\"Japan\";\n\t\tpicture=\"\";\n\t\taction=\"\";\n\t\thideName=1;\n"
              "\t\thidePicture=1;\n\t\tname=\"JP Site\";\n\t\tcredits=\"\";\n\t\tauthor=\"japan_dev\";\n\t\tauthorID=\"0\";\n"
              "\t\tversion=\"0.1\";\n\t\textra=0;\n\t\ttype=\"mod\";\n\t\tdependencies[]={\"World\"};\n\t\tclass defs\n\t\t{\n"
              "\t\t\tclass worldScriptModule\n\t\t\t{\n\t\t\t\tvalue=\"\";\n\t\t\t\tfiles[]={\"JP/site/scripts/4_World\"};\n"
              "\t\t\t};\n\t\t};\n\t};\n};\n")

PBOS = {
    "jp_furniture": {
        "area": "furniture", "patch": "JP_Furniture", "prefix": "JP\\furniture",
        "header": ["// JP_Furniture - interior props (jp_f_*), placed as proxies inside JP buildings like vanilla",
                   "// \\dz\\structures\\furniture, plus a StaticObj_JP_F_<name> class each (HouseNoDestruct, scope 1) as vanilla",
                   "// StaticObj_Furniture_<name>. No script, no vanilla change, no map dependency.",
                   "// GENERATED by japan_dev/tools/assemble_config.py from src/JP/furniture/_frags/*.json (one fragment per",
                   "// builder: B3a, L1, S1, W2F, ...) - edit the builders, not this file."],
        "mods": "",
        "scripts": {},
    },
    "jp_site": {
        "area": "site", "patch": "JP_Site", "prefix": "JP\\site",
        "header": ["// JP_Site - outdoor site objects (jp_s_*), stage S, B3b wave 1. Map objects: StaticObj_JP_S_<name>",
                   "// (HouseNoDestruct, scope 1, like vanilla StaticObj_Misc_*); the wells Land_JP_S_Well_* with a one-line",
                   "// script class 'extends Well' each (drink + wash hands + fill, exactly as vanilla Land_Misc_Well_Pump_*).",
                   "// Shop-front dressing is meant as proxies on shop buildings; it also has classes for loose placement.",
                   "// No vanilla change, no map dependency. GENERATED by japan_dev/tools/assemble_config.py from",
                   "// src/JP/site/_frags/*.json (one fragment per builder: B3b, L2, ...) - edit the builders, not this file."],
        "mods": _SITE_MODS,
        "scripts": {
            "scripts\\4_World\\JP_Site\\jp_site_wells.c": [
                "// JP_Site wells: vanilla declares one script class per well config (P:\\scripts\\4_world\\entities\\",
                "// building\\residential\\misc\\land_misc_well_pump_yellow.c: 'class Land_Misc_Well_Pump_Yellow extends Well'),",
                "// and Well (4_world\\entities\\building\\well.c) adds ActionDrinkWellContinuous + ActionWashHandsWell and makes",
                "// the object a WELL water source (bottles fill from it). These mirror that for our wells; nothing else.",
                "// GENERATED by japan_dev/tools/assemble_config.py from the site fragments (spikes/B3b/build.py wells) - edit",
                "// the generator."],
        },
    },
}


class AssembleError(Exception):
    pass


def _wb(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "wb") as f:
        f.write(text if isinstance(text, bytes) else text.replace("\r\n", "\n").encode("utf-8"))


def src_dir(pbo):
    return os.path.join(DEV, "src", "JP", PBOS[pbo]["area"])


def pbo_path(pbo):
    return os.path.join(ROOT, "@Japan", "addons", pbo + ".pbo")


def frag_path(pbo, builder):
    return os.path.join(src_dir(pbo), FRAG_DIR, builder + ".json")


def write_fragment(pbo, builder, writer, order, classes, models, required=("DZ_Data", "JP_Common"), scripts=None):
    """Called by a builder: its OWN classes / models only. classes = [{group, class, base, body[]}]."""
    if pbo not in PBOS:
        raise AssembleError("unknown PBO %r" % pbo)
    names = [c["class"] for c in classes]
    dup = sorted({n for n in names if names.count(n) > 1})
    if dup:
        raise AssembleError("%s fragment %s names a class twice: %s" % (pbo, builder, dup))
    frag = {"pbo": pbo, "builder": builder, "writer": writer, "order": order, "requiredAddons": list(required),
            "classes": classes, "models": list(models), "scripts": scripts or {}}
    _wb(frag_path(pbo, builder), json.dumps(frag, indent=1, ensure_ascii=False) + "\n")
    return frag_path(pbo, builder)


def fragments(pbo):
    d = os.path.join(src_dir(pbo), FRAG_DIR)
    out = []
    for f in sorted(os.listdir(d)) if os.path.isdir(d) else []:
        if f.endswith(".json"):
            fr = json.load(open(os.path.join(d, f), encoding="utf-8"))
            if fr.get("pbo") != pbo:
                raise AssembleError("%s: fragment for %r found in %s's folder" % (f, fr.get("pbo"), pbo))
            if fr["builder"] + ".json" != f:
                raise AssembleError("%s: builder %r does not match its file name" % (f, fr["builder"]))
            out.append(fr)
    out.sort(key=lambda fr: (fr["order"], fr["builder"]))
    return out


def merge(pbo):
    """-> {"classes": [(builder, entry)], "models": [name], "required": [...], "scripts": {path: [blocks]}, "frags"}"""
    frs = fragments(pbo)
    if not frs:
        raise AssembleError("%s: no fragments in %s" % (pbo, os.path.join(src_dir(pbo), FRAG_DIR)))
    classes, seen = [], {}
    models, mseen = [], set()
    required = []
    scripts = {k: [] for k in PBOS[pbo]["scripts"]}
    errors = []
    for fr in frs:
        for a in fr["requiredAddons"]:
            if a not in required:
                required.append(a)
        for c in fr["classes"]:
            key = c["class"].lower()                    # config class names are case-insensitive
            if key in seen:
                b0, c0 = seen[key]
                if (c0["base"], c0["body"]) != (c["base"], c["body"]):
                    errors.append("class %s: %s and %s give DIFFERENT bodies (%s : %s vs %s : %s)" % (
                        c["class"], b0, fr["builder"], c0["base"], c0["body"], c["base"], c["body"]))
                continue                                 # same body: keep the first
            seen[key] = (fr["builder"], c)
            classes.append((fr["builder"], c))
        for m in fr["models"]:
            if m.lower() not in mseen:
                mseen.add(m.lower())
                models.append(m)
        for path, blocks in fr.get("scripts", {}).items():
            if path not in scripts:
                raise AssembleError("%s: fragment %s writes an unknown script %s" % (pbo, fr["builder"], path))
            for b in blocks:
                if b not in scripts[path]:
                    scripts[path].append(b)
    if errors:
        raise AssembleError("%s: %d conflicting duplicate class(es):\n  %s" % (pbo, len(errors), "\n  ".join(errors)))
    return {"classes": classes, "models": models, "required": required, "scripts": scripts, "frags": frs}


def render(pbo, mg):
    spec = PBOS[pbo]
    req = ",\n".join("\t\t\t\"%s\"" % a for a in mg["required"])
    defined = {c["class"].lower() for _, c in mg["classes"]}
    bases = []
    for _, c in mg["classes"]:
        if c["base"] and c["base"].lower() not in defined and c["base"] not in bases:
            bases.append(c["base"])
    body = "".join("\tclass %s;\n" % b for b in bases)
    last = None
    for _, c in mg["classes"]:
        if c.get("group") and c["group"] != last:
            body += "\t// %s\n" % c["group"]
            last = c["group"]
        body += "\tclass %s%s\n\t{\n%s\t};\n" % (c["class"], (": " + c["base"]) if c["base"] else "",
                                                 "".join("\t\t%s\n" % l for l in c["body"]))
    config = ("\n".join(spec["header"]) + "\n" +
              "class CfgPatches\n{\n\tclass %s\n\t{\n\t\tunits[]={};\n\t\tweapons[]={};\n\t\trequiredVersion=0.1;\n"
              "\t\trequiredAddons[]=\n\t\t{\n%s\n\t\t};\n\t};\n};\n" % (spec["patch"], req) +
              spec["mods"] +
              "class CfgVehicles\n{\n%s};\n" % body)
    ms = "".join("\tclass %s: Default\n\t{\n\t};\n" % m for m in mg["models"])
    model_cfg = ("class CfgSkeletons\n{\n\tclass Default\n\t{\n\t\tisDiscrete=1;\n\t\tskeletonInherit=\"\";\n"
                 "\t\tskeletonBones[]={};\n\t};\n};\nclass CfgModels\n{\n\tclass Default\n\t{\n\t\tsectionsInherit=\"\";\n"
                 "\t\tsections[]={};\n\t\tskeletonName=\"\";\n\t};\n%s};\n" % ms)
    files = {"config.cpp": config, "model.cfg": model_cfg}
    for path, head in spec["scripts"].items():
        files[path] = "\n".join(head + mg["scripts"][path]) + "\n"
    return files


def cfgconvert(path):
    """CfgConvert to bin and back (syntax check), scratch in data/cfgasm."""
    os.makedirs(WORK, exist_ok=True)
    dst = os.path.join(WORK, os.path.basename(os.path.dirname(path)) + "_" + os.path.basename(path) + ".bin")
    if os.path.exists(dst):
        os.remove(dst)
    r = subprocess.run([CFGCONVERT, "-bin", "-dst", dst, path], capture_output=True, text=True, errors="replace")
    ok = r.returncode == 0 and os.path.isfile(dst)
    if ok:
        r2 = subprocess.run([CFGCONVERT, "-txt", "-dst", dst + ".cpp", dst], capture_output=True, text=True,
                            errors="replace")
        ok = r2.returncode == 0
    return ok, "CfgConvert %s: %s %s" % (os.path.basename(path), "OK" if ok else "FAILED", (r.stdout + r.stderr).strip())


def assemble(pbo, check_only=False, verbose=True):
    """Merge every fragment of <pbo> and write config.cpp, model.cfg and the generated scripts (or, check_only, report
    the stale ones). Returns {"classes": n, "models": n, "builders": {builder: n}, "stale": [paths], "files": [paths]}."""
    mg = merge(pbo)
    files = render(pbo, mg)
    stale, written = [], []
    for rel, text in files.items():
        p = os.path.join(src_dir(pbo), rel)
        data = text.encode("utf-8")
        old = open(p, "rb").read() if os.path.isfile(p) else None
        if old != data:
            stale.append(p)
            if not check_only:
                _wb(p, data)
        written.append(p)
    per = {}
    for b, _ in mg["classes"]:
        per[b] = per.get(b, 0) + 1
    res = {"pbo": pbo, "classes": len(mg["classes"]), "models": len(mg["models"]), "builders": per,
           "stale": stale, "files": written}
    if verbose:
        print("assemble %s: %d classes (%s), %d model.cfg entries; %s" % (
            pbo, res["classes"], ", ".join("%s %d" % kv for kv in per.items()), res["models"],
            ("STALE: " if check_only else "rewritten: ") + ", ".join(os.path.relpath(s, DEV) for s in stale)
            if stale else "unchanged"))
    return res


def pack(pbo, stage=None):
    """Assemble, then pack src/JP/<area> -> @Japan/addons/<pbo>.pbo. -> (ok, path or error text)."""
    assemble(pbo)
    stage = stage or os.path.join(WORK, pbo + "_stage")
    shutil.rmtree(stage, ignore_errors=True)
    shutil.copytree(src_dir(pbo), stage, ignore=shutil.ignore_patterns(*PACK_IGNORE))
    sys.path.insert(0, os.path.join(DEV, "tools", "common"))
    import pbo as pbotool
    out = pbo_path(pbo)
    try:
        pbotool.cmd_pack(stage, out, PBOS[pbo]["prefix"])
        return True, out
    except PermissionError as e:
        print("PBO write to @Japan FAILED (locked by a running server/game?):", e)
        return False, str(e)


def main(argv):
    want = [a for a in argv if not a.startswith("--")] or sorted(PBOS)
    bad = [p for p in want if p not in PBOS]
    if bad or "--help" in argv or "-h" in argv:
        print(__doc__)
        return 2 if bad else 0
    rc = 0
    for p in want:
        try:
            if "--list" in argv:
                for fr in fragments(p):
                    print("%-13s %-4s order %3d  classes %4d  models %4d  requiredAddons %s  (%s)" % (
                        p, fr["builder"], fr["order"], len(fr["classes"]), len(fr["models"]),
                        ",".join(fr["requiredAddons"]), fr["writer"]))
                continue
            r = assemble(p, check_only="--check" in argv)
            if "--check" in argv:
                rc = rc or (1 if r["stale"] else 0)
                continue
            for f in ("config.cpp", "model.cfg"):
                ok, msg = cfgconvert(os.path.join(src_dir(p), f))
                print("  " + msg)
                rc = rc or (0 if ok else 1)
            if "--pack" in argv:
                ok, det = pack(p)
                print("  packed:", ok, det)
                rc = rc or (0 if ok else 3)
        except AssembleError as e:
            print("ASSEMBLE FAILED:", e)
            rc = 1
    return rc


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
