// JP_Site wells: vanilla declares one script class per well config (P:\scripts\4_world\entities\
// building\residential\misc\land_misc_well_pump_yellow.c: 'class Land_Misc_Well_Pump_Yellow extends Well'),
// and Well (4_world\entities\building\well.c) adds ActionDrinkWellContinuous + ActionWashHandsWell and makes
// the object a WELL water source (bottles fill from it). These mirror that for our wells; nothing else.
// GENERATED by japan_dev/spikes/B3b/build.py - edit the generator.
class Land_JP_S_Well_Tsurube_Curb_Tub extends Well {};
class Land_JP_S_Well_Tsurube_Curb_Igeta extends Well {};
class Land_JP_S_Well_Tsurube_Curb_Stone extends Well {};
class Land_JP_S_Well_Tsurube_Roofed extends Well {};
class Land_JP_S_Well_Tsurube_Lid extends Well {};
class Land_JP_S_Well_Tsurube_Ab_Open extends Well {};
class Land_JP_S_Well_Hanetsurube_Well extends Well {};
class Land_JP_S_Well_Hanetsurube_Ab_Down extends Well {};
