// JP_Site wells: vanilla declares one script class per well config (P:\scripts\4_world\entities\
// building\residential\misc\land_misc_well_pump_yellow.c: 'class Land_Misc_Well_Pump_Yellow extends Well'),
// and Well (4_world\entities\building\well.c) adds ActionDrinkWellContinuous + ActionWashHandsWell and makes
// the object a WELL water source (bottles fill from it). These mirror that for our wells; nothing else.
// GENERATED by japan_dev/spikes/B3b/build.py - edit the generator.
//
// F1 TEMPORARY DIAGNOSTIC (2026-09-30) - REMOVE after the next well test (spikes/B3b/build.py WELL_DIAG).
// Prints '[JPWell] <type> at <pos> IsWell=<0|1>' once per well from DeferredInit.
class Land_JP_S_Well_Tsurube_Curb_Tub extends Well
{
	protected bool m_JPWellDiagDone; // F1 TEMP DIAGNOSTIC - remove
	override void DeferredInit() // F1 TEMP DIAGNOSTIC - remove
	{
		super.DeferredInit();
		if (m_JPWellDiagDone)
			return;
		m_JPWellDiagDone = true;
		string w = "0";
		if (IsWell())
			w = "1";
		Print("[JPWell] " + GetType() + " at " + GetPosition().ToString() + " IsWell=" + w);
	}
};
class Land_JP_S_Well_Tsurube_Curb_Igeta extends Well
{
	protected bool m_JPWellDiagDone; // F1 TEMP DIAGNOSTIC - remove
	override void DeferredInit() // F1 TEMP DIAGNOSTIC - remove
	{
		super.DeferredInit();
		if (m_JPWellDiagDone)
			return;
		m_JPWellDiagDone = true;
		string w = "0";
		if (IsWell())
			w = "1";
		Print("[JPWell] " + GetType() + " at " + GetPosition().ToString() + " IsWell=" + w);
	}
};
class Land_JP_S_Well_Tsurube_Curb_Stone extends Well
{
	protected bool m_JPWellDiagDone; // F1 TEMP DIAGNOSTIC - remove
	override void DeferredInit() // F1 TEMP DIAGNOSTIC - remove
	{
		super.DeferredInit();
		if (m_JPWellDiagDone)
			return;
		m_JPWellDiagDone = true;
		string w = "0";
		if (IsWell())
			w = "1";
		Print("[JPWell] " + GetType() + " at " + GetPosition().ToString() + " IsWell=" + w);
	}
};
class Land_JP_S_Well_Tsurube_Roofed extends Well
{
	protected bool m_JPWellDiagDone; // F1 TEMP DIAGNOSTIC - remove
	override void DeferredInit() // F1 TEMP DIAGNOSTIC - remove
	{
		super.DeferredInit();
		if (m_JPWellDiagDone)
			return;
		m_JPWellDiagDone = true;
		string w = "0";
		if (IsWell())
			w = "1";
		Print("[JPWell] " + GetType() + " at " + GetPosition().ToString() + " IsWell=" + w);
	}
};
class Land_JP_S_Well_Tsurube_Lid extends Well
{
	protected bool m_JPWellDiagDone; // F1 TEMP DIAGNOSTIC - remove
	override void DeferredInit() // F1 TEMP DIAGNOSTIC - remove
	{
		super.DeferredInit();
		if (m_JPWellDiagDone)
			return;
		m_JPWellDiagDone = true;
		string w = "0";
		if (IsWell())
			w = "1";
		Print("[JPWell] " + GetType() + " at " + GetPosition().ToString() + " IsWell=" + w);
	}
};
class Land_JP_S_Well_Tsurube_Ab_Open extends Well
{
	protected bool m_JPWellDiagDone; // F1 TEMP DIAGNOSTIC - remove
	override void DeferredInit() // F1 TEMP DIAGNOSTIC - remove
	{
		super.DeferredInit();
		if (m_JPWellDiagDone)
			return;
		m_JPWellDiagDone = true;
		string w = "0";
		if (IsWell())
			w = "1";
		Print("[JPWell] " + GetType() + " at " + GetPosition().ToString() + " IsWell=" + w);
	}
};
class Land_JP_S_Well_Hanetsurube_Well extends Well
{
	protected bool m_JPWellDiagDone; // F1 TEMP DIAGNOSTIC - remove
	override void DeferredInit() // F1 TEMP DIAGNOSTIC - remove
	{
		super.DeferredInit();
		if (m_JPWellDiagDone)
			return;
		m_JPWellDiagDone = true;
		string w = "0";
		if (IsWell())
			w = "1";
		Print("[JPWell] " + GetType() + " at " + GetPosition().ToString() + " IsWell=" + w);
	}
};
class Land_JP_S_Well_Hanetsurube_Ab_Down extends Well
{
	protected bool m_JPWellDiagDone; // F1 TEMP DIAGNOSTIC - remove
	override void DeferredInit() // F1 TEMP DIAGNOSTIC - remove
	{
		super.DeferredInit();
		if (m_JPWellDiagDone)
			return;
		m_JPWellDiagDone = true;
		string w = "0";
		if (IsWell())
			w = "1";
		Print("[JPWell] " + GetType() + " at " + GetPosition().ToString() + " IsWell=" + w);
	}
};
